---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - backup-ssh-key.yaml
  - daily-to-consume.yaml
  - helm-offsite-sync.yaml
  - helm-onsite-sync.yaml
  - helm-release-exporter.yaml
  - helm-release-redis.yaml
  - helm-release.yaml
  - namespace.yaml
  - pvc.yaml
  - secret.yaml
  - volsync.yaml