---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  #- daily-to-consume.yaml
  - helm-release-redis.yaml
  - helm-release.yaml
  - namespace.yaml
  - pvc.yaml
  - secret.yaml