---

- name: Installing kubectl
  ansible.builtin.include_tasks:
    file: kubectl.yml

- name: Installing flux
  ansible.builtin.include_tasks:
    file: flux.yml

- name: Installing sops
  ansible.builtin.include_tasks:
    file: sops.yml

- name: Installing talosctl
  ansible.builtin.include_tasks:
    file: talosctl.yml