apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: mbsync
    namespace: mailbackup
data:
    mbsync.rc: ENC[AES256_GCM,data:b7a2UpVNhMJu2j/q5MV+Ff2kQMe2gvOFXuBZ0VzD6YWIocpfeyMsfFJrpPR8Swm7AU0zF8cfFP152Rhljzi5nJEeybRfr37cR6EI5KodR26W+FPoB84aMq2NieStGFksObjB5u7/+mNaBU5UbxFE1H4EvzvE2bdG9i4n68KuxRGPHgG2vnuWBvRWeUX01ALuBnME4CoLtiT7duxSFYhlJJbqCJZzyVCTN0xlqtLebb1v7vd49hm6leJEWQ1zCRKcp1ElQ3yJLM+5p9VW7D22eqv9Gqk0mC6sQ0udkZmeTanvIM+O9kg7AaYSvjlNsPugtF6IFfT9mCUMWQHMmyBBFAAn5NFRXRQtGpKDMxs7NsM4y3KJvnlGH3j0kEB/Itk4SUclj07OGOeRpa7oIwZRlYmhnmBnoYqMgZ41msD/woPkwYPKKQAWXnfjlJYILwwdVxndgvbbY4Zm9hqHU7udBvmg/xGYTk3IP4dYwYULF0e1U4kBsyVtADuNaDdXRIKb7zhE6upvhZ+grmBG1a6we4oG2AzvIlchYVYVR3bVRRjguSUd/gAMFqWRE6pPpTvEnFFsXfTEg3xHip5xZAajtQjq0sjeo9Q+huLAHBya/+ZVmp6y89tihYVbAQwju0Z94wKCBjPhZ0h4T0S+1IO0Y1UTX71+3DWHrMFm+3O13jnLuSru,iv:Vd7Lmnj9Zfl2qINL1ljWEYkWCi1Tgh8g53MNeSxwT5U=,tag:zUzlF+C3UFBhkOKrRIXPxA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4eDlRdk10UjRKVW1lUkhI
            VlpSbHlNYzh1aG56RzNvOGtpQ3JhZGNxOUg4Cmh0SUdyYkRWQUFDVWJwdHhBMEt6
            dGFuV2lCU1F0L1M4VFdIODg5WVFCMHcKLS0tIGQzYjUxWDV4L2JaQ1AwejRoZzFv
            cENvMmkxdk5xdDNjUUtYYTBoYi9JR00KbFJBDFLs7Yw3NAEYnZtB6s2ix1Nf/IjM
            jLIg4Lads2jF/pgS6RjuKmJXD60inNH0WCQqQkL7dbBqY0QpcCXJ7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-21T21:21:45Z"
    mac: ENC[AES256_GCM,data:OMY10ZwhQMwcBUP/y1qguDE5k4MjtbIejJVf6z+xaq7xGBIK8+RToyWsBrc/9oJBCxvffoE54XsvYFInm6N/5x6MeLdpwZLC9rtehlCL6Ar0xXTA2i8CkMU7gVUceYX0SBR5TNypV8szt9+uWv8+Fs3ThanLRFd2rehXlL9jPdE=,iv:PDo8mK855thxZ0AdFwfrttgLB4fPdhoLMnfGHx0aKoE=,tag:4wexpDfj4TSPcTBzFLkgKQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
