---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: teddit
  namespace: teddit
  annotations:
    haproxy.org/whitelist: "${HAPROXY_WHITELIST}"
    haproxy.org/response-set-header: |
      Strict-Transport-Security "max-age=31536000"
      X-Frame-Options "DENY"
      X-Content-Type-Options "nosniff"
      Referrer-Policy "no-referrer-when-downgrade"
spec:
  rules:
    - host: "r.${SECRET_PRIVATE_DOMAIN}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: teddit
                port:
                  number: 8080
  tls:
    - secretName: ${SECRET_PRIVATE_DOMAIN_CERT}
      hosts:
        - "r.${SECRET_PRIVATE_DOMAIN}"
