---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - awx-deployment.yaml
  - database-secret.yaml
  - helm-bucket.yaml
  - helm-release-db-v17.yaml
  - helm-release.yaml
  - namespace.yaml
  - networkpolicy.yaml
  - probes.yaml
  - secret.yaml
