apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: awx-secrets
    namespace: awx
stringData:
    host: ENC[AES256_GCM,data:ASnLYc3CnVupDwueDSU+IMO0ubIWoMmRjNsKVb9xWXcDUOu/GglHpPo=,iv:11rWzpSdEPG638InouC7q7ENoEGkFuGTlDUeWZmw1A0=,tag:9cnM1hl6emvFyPkIuLgRjA==,type:str]
    port: ENC[AES256_GCM,data:yWvehw==,iv:jDCCElGhliLPlIeHWPcqjUHZMy1tKT58TUKp9Ri+fnE=,tag:MuwY3nfv8Qmx6tvHjIlkkA==,type:str]
    database: ENC[AES256_GCM,data:Xsrv,iv:44X9vePHQbVz0S+vANAC7tvshHNNJ+Wd5nf8gPiNCWA=,tag:Bh1D3EyctymGoZeGndDChw==,type:str]
    username: ENC[AES256_GCM,data:10fq,iv:WVqIjN9q65JKURmw1lKuCCJ9JEdocs4CmiMP3FcBTGM=,tag:NGqRyH/wDsN3SPljHKYJjQ==,type:str]
    password: ENC[AES256_GCM,data:kicMP0pdOaYzYHvpyw5Fh5oaFk1AYuBokYfwhCBHkTpeGHskQCw6VWRuF9OeKEVow1B6x0sSHbDUoFIPQ+zYnA==,iv:3ppkIyiIgaOvTfBVQq+QyDjahjsDZ4DOpTP4kTD0GiY=,tag:eC1TQh7bsvXj+HAWipRYZQ==,type:str]
    sslmode: ENC[AES256_GCM,data:Zys6jHS1,iv:JFO+1kOcgIGA6Mw8ogs2vay1GuKfMXRGjzI6fJQ1ols=,tag:P5vf3CbcQ44CNUzDpKM8rA==,type:str]
    type: ENC[AES256_GCM,data:IoV4YOWT4jZV,iv:tislfiPWxTxTjzASHATQptka4CLWIFcDK2QVypUCPGs=,tag:Jio2E7EdtP7m7CZSk5gtuw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIc0M2c3lvRW9mdHZ1M1BN
            dUpHcU1IZnhZS2ZWN3ZTQ0UxdmpHUzlwcWlJCmIya0lIMjRNd1E2UEp6Y1BIY05x
            VXB0L1RmdVdIMXFPcTlrM2RCelc1WW8KLS0tIE9RSXBZYU1tS2xkSmlCTlk3Z3Ex
            NFVQMEVrbi9wTWJXNCsxZEFCNkUraTgKhCJluqiVNaLSqKlQ6FQUWfIOGs2KlEpZ
            mSzyCmVuX8tDa7c0zzXVwLhYTX+kDlPkNhAshgGQxpsVZF5LgPLO8A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T22:42:10Z"
    mac: ENC[AES256_GCM,data:U/8O94TyXOm+7u6BCYH+HGLXln777t8/DFr6mDazojm7NKRZhHuFSE5N28q2h5B4yOBMuyIWrm4FGxRApNm2qarrIfKsgpB8Yf2im2a1MOLh6xgJPayDjd6R6j3GOUutLbSD61F3d9aw4hxpDKgd3vQ/9gXgvCcGSdXG1fl2ahM=,iv:8tz+thX+Ez6nHiSy2JVjjSkICT1RaLfxfk5IQz/kU1M=,tag:xaUB5mI8o0/6xk6eVv7Gjg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: awx-secret-key
    namespace: awx
data:
    secret_key: ENC[AES256_GCM,data:FP5rX/2iYWseOOP5XEV6WMVFI55BXOaOmVQpmz9EdHr2MScNIkNOBlqAqHY=,iv:KtxzODphKv/NgKh80ZnnOV72w4NwCvrWSuBnD7+xiYw=,tag:g3OGk8aJInhvFzZZuUTgqg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIc0M2c3lvRW9mdHZ1M1BN
            dUpHcU1IZnhZS2ZWN3ZTQ0UxdmpHUzlwcWlJCmIya0lIMjRNd1E2UEp6Y1BIY05x
            VXB0L1RmdVdIMXFPcTlrM2RCelc1WW8KLS0tIE9RSXBZYU1tS2xkSmlCTlk3Z3Ex
            NFVQMEVrbi9wTWJXNCsxZEFCNkUraTgKhCJluqiVNaLSqKlQ6FQUWfIOGs2KlEpZ
            mSzyCmVuX8tDa7c0zzXVwLhYTX+kDlPkNhAshgGQxpsVZF5LgPLO8A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T22:42:10Z"
    mac: ENC[AES256_GCM,data:U/8O94TyXOm+7u6BCYH+HGLXln777t8/DFr6mDazojm7NKRZhHuFSE5N28q2h5B4yOBMuyIWrm4FGxRApNm2qarrIfKsgpB8Yf2im2a1MOLh6xgJPayDjd6R6j3GOUutLbSD61F3d9aw4hxpDKgd3vQ/9gXgvCcGSdXG1fl2ahM=,iv:8tz+thX+Ez6nHiSy2JVjjSkICT1RaLfxfk5IQz/kU1M=,tag:xaUB5mI8o0/6xk6eVv7Gjg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
