---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - audiobookshelf
  - bazarr
  - beets
  - cronjobs
  - ersatztv
  - filebrowser
  - gogrepoc
  - jellyfin
  - jellyplex-watched
  - jellystat
  - lidarr
  - metube
  - mpd
  - multiscrobbler
  - navidrome
  - pinchflat
  - pvc.yaml
  - plex
  - prowlarr
  - qbittorrent
  - radarr
  - readarr
  - recyclarr
  - rreading-glasses
  - scraparr
  - seerr
  - sonarr
  - speakarr
  - streamripper
  - tautulli
  - tdarr
  - unpackerr
  - utility
  - namespace.yaml
  - networkpolicy.yaml
