apiVersion: v1
kind: Secret
metadata:
    name: speakarr-basic-auth
    namespace: media
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:ny9uf3eNrn4=,iv:Ka9pokssLaGjZIL0O+ayt8MM+y1lghV8pNjpaz6fZsA=,tag:GT0aermPbw/+oD7WfWjgVA==,type:str]
    password: ENC[AES256_GCM,data:1wEn3KluSuEIVahFlUzYXJ9nayz6XMgePS1jDB4glBiWEVkATdA6voBufvQGxPGPrNEoWdTz7WHVve0yKYG5JA==,iv:2RVyMZterv31zIyHedZvqM3PAkfLTtaw6mxYovPe6S8=,tag:7LP9853p3RYl/+WZb5FquA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBscHoxdjdaK2F1L1hVaG1E
            Q2U5NXhIZnVrYi9WRkxzaCtlSFJ5ZGZXMmlFCnhIZEFwNEZzK3lpbGFnNVE3Vk9o
            Qk5PRFZQMVgxcHVLYytqN2Z1d292K00KLS0tIDg2Um5NU3pvMVdOZUFXNXRBQTNI
            ZW51WWdQM1NKVFRzUUsraC8rakhHVVUKKOabMDPcx6BjEJCtya6ZamsWJBOcb+4B
            w4DQPZsj0cmmueDo9N6S2nzUHfAf9yaAsRGyDhwkX7FgQT6c0MZ/HA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T01:45:17Z"
    mac: ENC[AES256_GCM,data:PuLhT+zRBPgTeP9p6ldK6ibbArYChIKwhPrzZnPYueQN+Q7IqCIPQ3gQISvAcP/yuG/w0c8mPrhp5lq3WnJOhGl8yIpJIxTtCMegNdRNTxbK0q1Sm1jIdNyS0rfkZOTOeJxqjCZmMOstOG6T2lqUgHnFmFvoOg3yCib+8ujDgzs=,iv:QSxo4ouQgmVNkNm0CmNM8avQxkZMF5KfhsCo5HKf92g=,tag:UYPTEGj8W3IHot3wk+bpYQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: speakarr-postgres-v17
    namespace: media
type: Opaque
stringData:
    s3-access-key: ENC[AES256_GCM,data:xByPJRuex14DzxNsubyj1W2ZYfo=,iv:P+EL3+dn2RGZGcbLVyeq/c3XRffBJFTt6/xhxU2naGQ=,tag:ZGsLwjOllEThgnO3IRJW2w==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:d/8RTqVhS33M4siwoOKAjjm4VR2JYAABC5R7dk6uZfxiZFGkXpwPLA==,iv:YkXhecIPmLpYs3WgwTalrGG4txP7wRXt/358GWEfLtQ=,tag:KPcUoIJcDqJMYkzyKO7TKQ==,type:str]
    password: ENC[AES256_GCM,data:dcLTqe6VuAs0ry6upoOpNA2740NlNr6858BmlekeEN47TEbAFYXGtGVJKh5QJYJti4vaR53NC2D2S+c5yHw6gw==,iv:9ss4F5oG2CxJxknv2O63fiI2ViVaqZSp+N5V/fT9VTI=,tag:2GKJHUMuWPa6BDrJRzfwvg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBscHoxdjdaK2F1L1hVaG1E
            Q2U5NXhIZnVrYi9WRkxzaCtlSFJ5ZGZXMmlFCnhIZEFwNEZzK3lpbGFnNVE3Vk9o
            Qk5PRFZQMVgxcHVLYytqN2Z1d292K00KLS0tIDg2Um5NU3pvMVdOZUFXNXRBQTNI
            ZW51WWdQM1NKVFRzUUsraC8rakhHVVUKKOabMDPcx6BjEJCtya6ZamsWJBOcb+4B
            w4DQPZsj0cmmueDo9N6S2nzUHfAf9yaAsRGyDhwkX7FgQT6c0MZ/HA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T01:45:17Z"
    mac: ENC[AES256_GCM,data:PuLhT+zRBPgTeP9p6ldK6ibbArYChIKwhPrzZnPYueQN+Q7IqCIPQ3gQISvAcP/yuG/w0c8mPrhp5lq3WnJOhGl8yIpJIxTtCMegNdRNTxbK0q1Sm1jIdNyS0rfkZOTOeJxqjCZmMOstOG6T2lqUgHnFmFvoOg3yCib+8ujDgzs=,iv:QSxo4ouQgmVNkNm0CmNM8avQxkZMF5KfhsCo5HKf92g=,tag:UYPTEGj8W3IHot3wk+bpYQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: speakarr-postgres-v18
    namespace: media
type: Opaque
stringData:
    s3-access-key: ENC[AES256_GCM,data:SkyuJpTjXG/UHEqBBYh16ovEL1k=,iv:TynqC2j7Sg+wuEbPZmwEVwmYcRUl0/nhmCAsd8oER1I=,tag:Uel9BWkGnfk1aXfEZBgkrg==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:o9Uo4x5GjYpF/J9XEI0VYCeA9wNRFvZKOrAf/7TFbJmWLbylcN/Luw==,iv:WbrJIeCt00aiTguPj/1AT2Gd1fxa/F5T1s5lRNKo818=,tag:rBDvxOC2oK+KUIj7M0k51g==,type:str]
    password: ENC[AES256_GCM,data:8vBW5ogsv39FfuJA+J6oqa+mLFuTVVWoRsIDZQ0jF45Fz4pfH6JDpdahdJYXIKDkgWebgXasC/+MyMPfDwvL+Q==,iv:QH/exs5ozZHhnkhchf1dKXZeLB6kCwtH1lan+QY4h00=,tag:Xrh0TmEZ2OYm8Zz+k8ZB4w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBscHoxdjdaK2F1L1hVaG1E
            Q2U5NXhIZnVrYi9WRkxzaCtlSFJ5ZGZXMmlFCnhIZEFwNEZzK3lpbGFnNVE3Vk9o
            Qk5PRFZQMVgxcHVLYytqN2Z1d292K00KLS0tIDg2Um5NU3pvMVdOZUFXNXRBQTNI
            ZW51WWdQM1NKVFRzUUsraC8rakhHVVUKKOabMDPcx6BjEJCtya6ZamsWJBOcb+4B
            w4DQPZsj0cmmueDo9N6S2nzUHfAf9yaAsRGyDhwkX7FgQT6c0MZ/HA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T01:45:17Z"
    mac: ENC[AES256_GCM,data:PuLhT+zRBPgTeP9p6ldK6ibbArYChIKwhPrzZnPYueQN+Q7IqCIPQ3gQISvAcP/yuG/w0c8mPrhp5lq3WnJOhGl8yIpJIxTtCMegNdRNTxbK0q1Sm1jIdNyS0rfkZOTOeJxqjCZmMOstOG6T2lqUgHnFmFvoOg3yCib+8ujDgzs=,iv:QSxo4ouQgmVNkNm0CmNM8avQxkZMF5KfhsCo5HKf92g=,tag:UYPTEGj8W3IHot3wk+bpYQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
