apiVersion: v1
kind: Secret
metadata:
    name: speakarr-basic-auth
    namespace: media
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:P2TY1U9hakc=,iv:6pt1SpfTRt9H+kv3YvngbEm/SKJjXLC8VAdLTENLMEs=,tag:bibPq/GkVpdrjjSeYPWF+g==,type:str]
    password: ENC[AES256_GCM,data:cmdzlSYLlVKT0mPluHryxD3p9OKJ5+XPjWAbbr6N6Elq/mtEIvaHmBNRQMDlGf8Bd1buRh/C3VO5ZiRJ1Dl17w==,iv:yVdfmGECM/mjKISpneMP0++/68RXeiOfkyiMjQNPm6o=,tag:gyIUmVGm50SUtXtMxW2sTA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBISHIvbG5PYzdzTm9zVGF3
            NHBqY2dDSEJDYW1nOUVJbEdUdGFiMU14SWtFCitkVkh4Q2libjNRWTFuVzc2MTN5
            T3JlQWVaZ3VnQ0hIUlVHZ0NhZjZxd28KLS0tIFJ2di8vazB5M1U4Tm5RNTQ3VVgv
            SmR0cS82ekRmeXRYOUVucDBDY000ekkKybZKNZupZMYJYGT6NJjkhasdYUsP3KiP
            Ca1s8s5Q6WHfANt3hcLUTVmwS+kv1P3I+fOLSD0774OTzZ6e1El0qA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T11:32:04Z"
    mac: ENC[AES256_GCM,data:k2RIy1hY3GoCaWAjVEyXdcxqxGGOARod923w+oFw06tFwuF/t4vKq/wFVerdMjxm4KdMFarjU/j9qdhxWLoUS0ccojf+I3OaqH2kR/FG6w7tkBO35ICwjbs1HkFn/bGUpHww7ichDaOxMmnKI0J7JHyVj1eW2g67SZglDxx3+pU=,iv:8jSW0pNX96wWFBNKvovNL5Dk+mzzH2Wr24VDah+aY4I=,tag:acZz2xpHpKjU8U4BVyDroA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: speakarr-postgres-v18
    namespace: media
type: Opaque
stringData:
    s3-access-key: ENC[AES256_GCM,data:jdE8Fvgf1z+sl/7RP+ZBjelPkKk=,iv:lF64WzlNM0RtrSHkszBzGyha/GWAJdZcIkCDC9dCvFM=,tag:QbV/jiPN5M5v9eMEggcikQ==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:6cb6Ugcr+UTfdoqDwocK2OTawetJubLKfBse5j5Wf4HJ/GJJ56Ak1Q==,iv:pI0LhtHbcfRm9CXZ4fEdl2G+KOKw3GJ/yVxgMAnOfFc=,tag:Wifrk8HXwA2SubjT5idkZw==,type:str]
    password: ENC[AES256_GCM,data:qnQ+i/W7bsC2JpmotJdIStctTCQV2MwPxZ54QxHj0VsXJNapqP3vOeom/LixUsVzclShI7nAqSL7txrTygX+7w==,iv:LajzRnser8iXbaxKsJlZWSk0GyMNThQL5BSzmf4qvaQ=,tag:kWpVT6yF3pp2K+V5Tco3lQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBISHIvbG5PYzdzTm9zVGF3
            NHBqY2dDSEJDYW1nOUVJbEdUdGFiMU14SWtFCitkVkh4Q2libjNRWTFuVzc2MTN5
            T3JlQWVaZ3VnQ0hIUlVHZ0NhZjZxd28KLS0tIFJ2di8vazB5M1U4Tm5RNTQ3VVgv
            SmR0cS82ekRmeXRYOUVucDBDY000ekkKybZKNZupZMYJYGT6NJjkhasdYUsP3KiP
            Ca1s8s5Q6WHfANt3hcLUTVmwS+kv1P3I+fOLSD0774OTzZ6e1El0qA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T11:32:04Z"
    mac: ENC[AES256_GCM,data:k2RIy1hY3GoCaWAjVEyXdcxqxGGOARod923w+oFw06tFwuF/t4vKq/wFVerdMjxm4KdMFarjU/j9qdhxWLoUS0ccojf+I3OaqH2kR/FG6w7tkBO35ICwjbs1HkFn/bGUpHww7ichDaOxMmnKI0J7JHyVj1eW2g67SZglDxx3+pU=,iv:8jSW0pNX96wWFBNKvovNL5Dk+mzzH2Wr24VDah+aY4I=,tag:acZz2xpHpKjU8U4BVyDroA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
