apiVersion: v1
kind: Secret
metadata:
    name: speakarr-basic-auth
    namespace: media
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:SWTH0mwavpM=,iv:kQ30LrGtxnTP3oLLItQ+H/BM4D4Tq09MeCGkkLPrQCU=,tag:ML/o48wSrCnV5hvvLlwFjg==,type:str]
    password: ENC[AES256_GCM,data:VnKylalTcQWzGTG2sLnL8hrOqgSfxJc/goet9hBeMxe9dH40mM1QBflzfAK5Ip2JGxZOPLK/pY2OrL3sb6gCgw==,iv:1dOIv1ufEzhvRXWk1A/186zZSb+Zrg+UfVHNWQc2O/M=,tag:Cf5PeVxd/09CqLdNKFAJPQ==,type:str]
sops:
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEM2ZXZktIaGhaUnhKMGd3
            UW9iQXJYdlFjWS9pL2hqdEt3MjRhMXVhWFVnCjF4TGtZb0RRNmdtd2RnVUdXZ1Bu
            ZjQ5cU1ibUpqUEVXQ296WUtTZmpKU2MKLS0tIDBJcG9OREUyaUEwcmJZcVZTMWJU
            TWNZVk12M3RqQnFUWkdKSS9pa1RKS00KlRyVnSNiTVDUR6j0OIF5Cpz81qdUidm8
            gf3pSXuAKMIgIbPNmMXh4CO30zIJSpgLrd4bHEHo+3ZJUDFkiSXexw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-17T21:13:23Z"
    mac: ENC[AES256_GCM,data:x8pC6K2esHmX+SQ4g8RbiQR3lZmzGm9BPr3ctFful/tQ1GSTcCMOltk7JxZJRLC38TrnB4VmMTX/oA82kHv4oyTG9/Q1sjRlQX4heV4gWeMnqyuNrk7T0G5EouEexvCIhsGCtqqcDm811wOQpMc11NUSorr01LK8DPnLWkCgDVc=,iv:fs/9GrKWKlWitCJrobljX5xy8R6J7zXCqO3a2sAja9g=,tag:dOq022asgdZyK4T1VeayKw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: speakarr-postgres-v18
    namespace: media
type: Opaque
stringData:
    s3-access-key: ENC[AES256_GCM,data:tghQ6bXr7uyvpAGFOX3R1sE1piXcPl7zdOU=,iv:oCLZfOIyULaHnTVfjbDWOHD3pxUQd/nN97oSpjLcVjs=,tag:ttgII2/jL6tJ/BLOa3mdSA==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:zrah1gWGXzFl1A4dW5pnAHjyfTXiqdQDm3NlfCf9QGrJAPboeCXQOKbXr9MMkMO6AVBENOAH+/c9CmcuurU1UQ==,iv:6DkMBUq95kR5OJ8jP+/ji/TGh9iMiXrB0Eih/sWucpc=,tag:JGcrw+M0SzO7Llj7VAqtkQ==,type:str]
    region: ENC[AES256_GCM,data:+iDwcza7,iv:zzplkd+UsidPozMEtrknqTDN8wVt1sb3w93y07CIkLI=,tag:ULHsnw22IQ2yREK/bBhrtQ==,type:str]
    password: ENC[AES256_GCM,data:hvMXbiRgLYh77hLqyZDyIFkDdAuOGRRJsX01QLtbVPRRwYNs1icJ/3+q9UEC7zNpIql+UOpHrMz3gcxX5YKJow==,iv:HCgVBLtP1/qk7aK6r6snDvPxVJQadoOGjqde2wFJyxc=,tag:EI0sUgmwaVlktSP1uqX8Bw==,type:str]
sops:
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEM2ZXZktIaGhaUnhKMGd3
            UW9iQXJYdlFjWS9pL2hqdEt3MjRhMXVhWFVnCjF4TGtZb0RRNmdtd2RnVUdXZ1Bu
            ZjQ5cU1ibUpqUEVXQ296WUtTZmpKU2MKLS0tIDBJcG9OREUyaUEwcmJZcVZTMWJU
            TWNZVk12M3RqQnFUWkdKSS9pa1RKS00KlRyVnSNiTVDUR6j0OIF5Cpz81qdUidm8
            gf3pSXuAKMIgIbPNmMXh4CO30zIJSpgLrd4bHEHo+3ZJUDFkiSXexw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-17T21:13:23Z"
    mac: ENC[AES256_GCM,data:x8pC6K2esHmX+SQ4g8RbiQR3lZmzGm9BPr3ctFful/tQ1GSTcCMOltk7JxZJRLC38TrnB4VmMTX/oA82kHv4oyTG9/Q1sjRlQX4heV4gWeMnqyuNrk7T0G5EouEexvCIhsGCtqqcDm811wOQpMc11NUSorr01LK8DPnLWkCgDVc=,iv:fs/9GrKWKlWitCJrobljX5xy8R6J7zXCqO3a2sAja9g=,tag:dOq022asgdZyK4T1VeayKw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
