---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny
  namespace: kyverno
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: admission-controller
  namespace: kyverno
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/component: admission-controller
      app.kubernetes.io/instance: kyverno-kyverno
      app.kubernetes.io/part-of: kyverno
  egress:
    - toEntities:
      - kube-apiserver
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: cleanup-controller
  namespace: kyverno
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/component: cleanup-controller
      app.kubernetes.io/instance: kyverno-kyverno
      app.kubernetes.io/part-of: kyverno
  egress:
    - toEntities:
      - kube-apiserver
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: scale-to-zero # this is a job that scales all deployments down to 0, used when removing kyverno
  namespace: kyverno
spec:
  endpointSelector:
    matchLabels:
      job-name: kyverno-scale-to-zero
  egress:
    - toEntities:
      - kube-apiserver
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: mutatingwebhookconfig # this is a job that removes the webhooks for kyverno, used when removing kyverno
  namespace: kyverno
spec:
  endpointSelector:
    matchLabels:
      job-name: kyverno-rm-mutatingwhconfig
  egress:
    - toEntities:
      - kube-apiserver