apiVersion: v1
kind: Secret
metadata:
    name: jellyseerr-basic-auth
    namespace: media
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:uXduXlkBI4Vtug==,iv:rSrLGRKMy/OzTVFBz4MPXln5MRE/fOpsGK1RvFGm5hg=,tag:Gm2wK0chq/SXoDpFTEFGmQ==,type:str]
    password: ENC[AES256_GCM,data:t+OZu6fQ8z7EL3SqQElodJb/z9jfd3TOSGxHBmUK9qfWRqMZFF3cFmiQdt0ZOPSVvvviTM241Gi/HVBfXKUHcQ==,iv:7tyrfzKvzuCqX6Mwbg3qUyhQz6gAhBDGlkz9P3LmMMc=,tag:5gZ6YLsTvVnsWyeh9LC62A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqRzdYU0FGR01wWHZ4TGlY
            emkzbzZmVVJIbHZUcFFGbzJPVW1jalpUQlY0CkxTcUR2YjR6Zjhya3hnZ0dlV3E0
            YlgrdHh0Y2pibnorY2RFNzBiakx2NjAKLS0tIGFUVmZabUxkM1lDTHlDckl1cjhs
            aDQ4UVhYRXBSSmZlV09mQTB3eUxqdGsKySQ0tc05sjpy3Z/xtVcFyPr6FHzPOhGH
            c3CdaQXni32x9ma/hj0X8Krcg/I96Pzpz/om7VB0bcGvoqP+5yB6AQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T01:16:36Z"
    mac: ENC[AES256_GCM,data:Kq7kFiBIvDSJE0Tw7mkixDjlqZwuRabVwnJwlLCTFCE7XEFzcOnbPCUi1Dl2i6Mfd6LPYXVRF59vvR3YhUXs6geGdTsPaPx8nWiWN0KWwevpuAKpJL8U1qYK35FW/Zixki3TZMHNKENt/Bz0lPqsoK8i4/kLn4yugy0HqwkGn7w=,iv:potZbl2BOjPFPwKbF3HSFPFy8aB0UI/GL6m+H5omNpM=,tag:YAonkGeHtbmaqNxwlXwI6g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: jellyseerr-postgres-v17
    namespace: media
type: Opaque
stringData:
    s3-access-key: ENC[AES256_GCM,data:V+F1ea1BmjcpyqmT432kd+RVxHg=,iv:yPFq/GunRps6b8uwUJOKNCy6bPF6UAuT+wLG0hEIHj0=,tag:aeMEvrSa5ztY8mN+akOPeg==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:VdrB8wl4DQ6vAaeJdRJ1UoMvO9U8X+AhAaIdCqU+l+u+Bz9bViLypQ==,iv:1JEwfFKwgnOh3EsLxPRaa2dhe57tw3exTZMqwlpMd6g=,tag:9Lmb/lLqv/EZy3VxEZeKcw==,type:str]
    password: ENC[AES256_GCM,data:kwidYFGPtO1bt0zeBLegbLHx69u8m6ogFn5u48qcpD2nOS1/b1v6P8d1/Fp+mi2rElsyI/NTl9JHRd9lVqu7og==,iv:MO8rHYvSgYXSHdbMIRSr6dsFFLHzXBW2+fm+bjKfncA=,tag:eSUWEVYPb86NWKK0LNcgJA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqRzdYU0FGR01wWHZ4TGlY
            emkzbzZmVVJIbHZUcFFGbzJPVW1jalpUQlY0CkxTcUR2YjR6Zjhya3hnZ0dlV3E0
            YlgrdHh0Y2pibnorY2RFNzBiakx2NjAKLS0tIGFUVmZabUxkM1lDTHlDckl1cjhs
            aDQ4UVhYRXBSSmZlV09mQTB3eUxqdGsKySQ0tc05sjpy3Z/xtVcFyPr6FHzPOhGH
            c3CdaQXni32x9ma/hj0X8Krcg/I96Pzpz/om7VB0bcGvoqP+5yB6AQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T01:16:36Z"
    mac: ENC[AES256_GCM,data:Kq7kFiBIvDSJE0Tw7mkixDjlqZwuRabVwnJwlLCTFCE7XEFzcOnbPCUi1Dl2i6Mfd6LPYXVRF59vvR3YhUXs6geGdTsPaPx8nWiWN0KWwevpuAKpJL8U1qYK35FW/Zixki3TZMHNKENt/Bz0lPqsoK8i4/kLn4yugy0HqwkGn7w=,iv:potZbl2BOjPFPwKbF3HSFPFy8aB0UI/GL6m+H5omNpM=,tag:YAonkGeHtbmaqNxwlXwI6g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: jellyseerr-postgres-v18
    namespace: media
type: Opaque
stringData:
    s3-access-key: ENC[AES256_GCM,data:cMWNOcYiXlBGPxbv38CsjzPoWTs=,iv:Ocx6YtphLNN6lreGKmlaNrJd7P87P6h/SVmZY7Fnt3A=,tag:cJezEglmujPSJgSBZAw46A==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:AHOA5ujrL9m7Aw6iJ7Nlc4SjQftwj7m3dvWIhPqbD3l+tVXryvoA3Q==,iv:GD7r4N/q2G3XncbaRxBDDcsT9izO2FMEXcVskmr45Sw=,tag:M1AHbURDKR7oG6aQW/OAjw==,type:str]
    password: ENC[AES256_GCM,data:r1zi21ElSNQcXRwdy3gzJnVqd//1RwgvUlm75uGE4k8U7UYKGJ25OKIzybrF9/8B7I/XOO+BBb+NjQA5AguoBg==,iv:+mBgrkeqnnHvt0RbJyLSYO866y8SgF59gfrlhVsfGWw=,tag:WQCxeCXtDBWMbP0GbuIS8Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqRzdYU0FGR01wWHZ4TGlY
            emkzbzZmVVJIbHZUcFFGbzJPVW1jalpUQlY0CkxTcUR2YjR6Zjhya3hnZ0dlV3E0
            YlgrdHh0Y2pibnorY2RFNzBiakx2NjAKLS0tIGFUVmZabUxkM1lDTHlDckl1cjhs
            aDQ4UVhYRXBSSmZlV09mQTB3eUxqdGsKySQ0tc05sjpy3Z/xtVcFyPr6FHzPOhGH
            c3CdaQXni32x9ma/hj0X8Krcg/I96Pzpz/om7VB0bcGvoqP+5yB6AQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T01:16:36Z"
    mac: ENC[AES256_GCM,data:Kq7kFiBIvDSJE0Tw7mkixDjlqZwuRabVwnJwlLCTFCE7XEFzcOnbPCUi1Dl2i6Mfd6LPYXVRF59vvR3YhUXs6geGdTsPaPx8nWiWN0KWwevpuAKpJL8U1qYK35FW/Zixki3TZMHNKENt/Bz0lPqsoK8i4/kLn4yugy0HqwkGn7w=,iv:potZbl2BOjPFPwKbF3HSFPFy8aB0UI/GL6m+H5omNpM=,tag:YAonkGeHtbmaqNxwlXwI6g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
