apiVersion: v1
kind: Secret
metadata:
    name: jellyseerr-basic-auth
    namespace: media
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:B2AU2Ig+3qdhTA==,iv:sgcWo2ai6/Y7pz69VZd6RunG1qJheRlp6Dz3KgGZ67U=,tag:2kR1CM61pSkTtrUPNy9DjQ==,type:str]
    password: ENC[AES256_GCM,data:5v3b26tTl57/1U8fZJ0zrnvhX7ZBj43v5crurkUv1+L08OPLssfr9a3aZu8H+84ZhlrWVpelUhC7++fhOIaa6A==,iv:I9Zluj8ob9q6+WBvmHh1xqJgK/nqgVlo2l5B+RE4wX8=,tag:sX7L6yaqB453s1BZpEn4WQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSOCtGWGZNUkMrajJMNE5N
            Q1FCQlo5UnYvMktBK1hoTmZRSmF6anRBVEdVCjVUbktYb1pyK3dWaGM2K29GWXBK
            dFVaNDNUS1FpSjZNd0hhSjY5ZjlRK0kKLS0tIEM1Qk5Jem5xNkhVclQvMURIUW4z
            NEtvSFkySDhuVHl6TEZ3RmtyM252Q3cKZW7nJSxaE1YzRusAXhMjLb+PDQ1uCvP1
            IvRU8d3/PrT3H3Go6yhGAG7wsppiRRDMlN/YRHItq774/OyoNV6qug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T01:25:17Z"
    mac: ENC[AES256_GCM,data:yzeqvONLzIvZVMGapYBgM/QruohZ5nlujkE5qCFvu5HeLArhM7o7LEBpUA3f2BpQG/fAzAA5h4JEpCQ6USD7Nej80X+k+kbAwBTic4oQIb/TZFB75ufwdLd4OSareSu0aSbt/Q6SdVJXe/h+JNCvZf3eV6sbSFuA+AHD7AVU2i4=,iv:8Vk8/tgMM4b71C1fAPdAliUe3VgR9r9gBVv3FMFXSJ4=,tag:pREdAuCPgqiIDui29SZfhQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: jellyseerr-postgres-v18
    namespace: media
type: Opaque
stringData:
    s3-access-key: ENC[AES256_GCM,data:LYIq32cLAxY0PZD99AEei6Dxe14=,iv:2iT+Oq7gDUHlnm0tXmsFQKD1y2Uhtj31BUy+u/DBUqY=,tag:C6QuPGixtWEc+Q2/Dqrq4Q==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:iffcthElXZGUCVc/FIglMW/ulF8xUfnQ169A6PgBG4Nmg4YA/61Dww==,iv:0537eteR/f4zEBeJXNj6uT61IrZ8T7E1M2c8Y7pL6wM=,tag:mtIkKyktl1MZbbUZsVmsWA==,type:str]
    password: ENC[AES256_GCM,data:tQpEvIoBft69eqNJJGi03EOAqsj9Wnhqi4LiW2Ah9jLJXBRJtVi5dU2WfwfEXmCCb1Ce0bNuZN3FtdjWKW6sMw==,iv:mEUIak0SqaPqB3EaJ1LcrohKPgDkfRoxNA0Knx5o9Ww=,tag:i0vPyQbDjPN2X7rmaaeBlA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSOCtGWGZNUkMrajJMNE5N
            Q1FCQlo5UnYvMktBK1hoTmZRSmF6anRBVEdVCjVUbktYb1pyK3dWaGM2K29GWXBK
            dFVaNDNUS1FpSjZNd0hhSjY5ZjlRK0kKLS0tIEM1Qk5Jem5xNkhVclQvMURIUW4z
            NEtvSFkySDhuVHl6TEZ3RmtyM252Q3cKZW7nJSxaE1YzRusAXhMjLb+PDQ1uCvP1
            IvRU8d3/PrT3H3Go6yhGAG7wsppiRRDMlN/YRHItq774/OyoNV6qug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T01:25:17Z"
    mac: ENC[AES256_GCM,data:yzeqvONLzIvZVMGapYBgM/QruohZ5nlujkE5qCFvu5HeLArhM7o7LEBpUA3f2BpQG/fAzAA5h4JEpCQ6USD7Nej80X+k+kbAwBTic4oQIb/TZFB75ufwdLd4OSareSu0aSbt/Q6SdVJXe/h+JNCvZf3eV6sbSFuA+AHD7AVU2i4=,iv:8Vk8/tgMM4b71C1fAPdAliUe3VgR9r9gBVv3FMFXSJ4=,tag:pREdAuCPgqiIDui29SZfhQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
