---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - database-secret.yaml
  - helm-release-db-v17.yaml
  - helm-release-valkey.yaml
  #- helm-release.yaml
  - namespace.yaml
  #- probes.yaml
