---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - backup-ssh-key.yaml
  - helm-daily-chown-media.yaml
  - helm-daily-instaloader.yaml
  - helm-daily-streamripper.yaml
  - helm-daily-to-jottacloud.yaml
  - helm-onsite-sync.yaml