---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: forgejo-charts
  namespace: flux-system
spec:
  type: oci
  interval: 2h
  url: oci://code.forgejo.org/forgejo-helm/forgejo
  timeout: 3m
