---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - aquasecurity.yaml
  - authentik.yaml
  - awx.yaml
  - backube.yaml
  - bjw-s.yaml
  - cilium.yaml
  - cloudnative-pg.yaml
  - descheduler.yaml
  - dysnix.yaml
  - emberstack.yaml
  - emqx.yaml
  - flux.yaml
  - fluxcd-community.yaml
  - grafana.yaml
  - haproxytech.yaml
  - immich.yaml
  - intel.yaml
  - itzg.yaml
  - jetstack.yaml
  - jupyterhub.yaml
  - kyverno.yaml
  - metrics-server.yaml
  - piraeus.yaml
  - prometheus.yaml
  - rook-ceph.yaml
  - spegel.yaml
  - stakater.yaml
  - superset.yaml