apiVersion: v1
kind: Secret
metadata:
    name: jellystat-basic-auth
    namespace: media
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:Wr2xBI2OIQ4M,iv:tw/Zu/Ah+QxGyMKQGRYUhhP2MPxqQqJAFsf4LBvAvDE=,tag:LlYTKQ4rCPQpcrkuOjOpew==,type:str]
    password: ENC[AES256_GCM,data:33YseGqIL9Ijc41JvsuK22pdRG4JnK0lmrMOcej7CYk=,iv:SBHbzlSXyClxjTGGL5c1EGc7h6oIR7HLYf++Fd8uRiE=,tag:o8dT6QkSQG75tNAgYEHfDA==,type:str]
sops:
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2OUpyTTNUdDVJS1NONVJR
            MnRCVGZQa3JwRXRCRFI3dXFJRUdtWkJES0FVCkhXb1Z0QnEvWFJKTTl3WWFFRnl6
            RFVEMytzYzZyQ21pYTZyVGRDemRLYWMKLS0tIEVBRU9YMlFMYUJGNUpjVlJDVWNy
            UGRFQnlmbDUwMWk5cm1CbHlaOTQ0cE0KDcF1YCuxAG+qZ9yM6nZXIBJEhS0Xs2a5
            kvJ9KqC0t/QTCFd6pvR9plbfLDijC/7kqUFReN6Om5Ankwn+aAGG0w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-17T21:13:29Z"
    mac: ENC[AES256_GCM,data:YsGeQS/9M0VV4j+xeR2KZzb5PEqd6Eor1cLp9KVbsNzVbnVMiyewIap4F2LMv9V3aUYHBBAqD64xk+xky/ZV5MvzcIPu7tZ0QboaZ/SHruUKyO/ROBovagCU+mCmrIdCRyPOYavX78fRfbF3/fNk9Eop2q0yxff/rvd0Ic7Q7zQ=,iv:emDKE3N/xAFpDY8nt6Y6eUdeucS6tA3LXKDQuWhYPjw=,tag:w8RzpasVDN3Zg3MAxjogIQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: jellystat-postgres-v18
    namespace: media
type: Opaque
stringData:
    s3-access-key: ENC[AES256_GCM,data:dzGCOzRAauSB6J7HBEoSIXurqI6/hLxZKqQ=,iv:x/z/QMg3kpSLXGFj+v//qGgMoocsPRDCmj2XIHB2YCQ=,tag:t6LB4KipBGbMc6T1hBpLNw==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:QH/WIok3kRT7vZP+7gS89pt1KG6S7Vh3iaHbY9SPV9HftEATThX4vCsFmjqcEjZ1gJx+0QDTNtIGOrpkpiEdjQ==,iv:huNI1/HtfmsaJHId59ukJa5GkLq/T2M2Mbo+8K/J81g=,tag:1pLfM8c69dSMhEzhPqH8wQ==,type:str]
    region: ENC[AES256_GCM,data:5zZ4RZZF,iv:MIx4X7BByy2RXcYx7q+rGodA+9jUrA98rGmr/A++O1U=,tag:nQssskx1CNzcgU7S6v/Kuw==,type:str]
    password: ENC[AES256_GCM,data:I9CKGWGXl1xGgWBwlslrOFYqEGT1zF89q+iYuiGfgKmO2Wf11m9ZCkn+ipIRqvaNlR4uyoyvHTc6olWxTtVzGg==,iv:dOWOeeNeeXW4pnEUChl7DDpIJKn8yvDq4dRXnzuAJAA=,tag:t9S9xj96mnhKXXqR7/EoeA==,type:str]
sops:
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2OUpyTTNUdDVJS1NONVJR
            MnRCVGZQa3JwRXRCRFI3dXFJRUdtWkJES0FVCkhXb1Z0QnEvWFJKTTl3WWFFRnl6
            RFVEMytzYzZyQ21pYTZyVGRDemRLYWMKLS0tIEVBRU9YMlFMYUJGNUpjVlJDVWNy
            UGRFQnlmbDUwMWk5cm1CbHlaOTQ0cE0KDcF1YCuxAG+qZ9yM6nZXIBJEhS0Xs2a5
            kvJ9KqC0t/QTCFd6pvR9plbfLDijC/7kqUFReN6Om5Ankwn+aAGG0w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-17T21:13:29Z"
    mac: ENC[AES256_GCM,data:YsGeQS/9M0VV4j+xeR2KZzb5PEqd6Eor1cLp9KVbsNzVbnVMiyewIap4F2LMv9V3aUYHBBAqD64xk+xky/ZV5MvzcIPu7tZ0QboaZ/SHruUKyO/ROBovagCU+mCmrIdCRyPOYavX78fRfbF3/fNk9Eop2q0yxff/rvd0Ic7Q7zQ=,iv:emDKE3N/xAFpDY8nt6Y6eUdeucS6tA3LXKDQuWhYPjw=,tag:w8RzpasVDN3Zg3MAxjogIQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
