apiVersion: v1
kind: Secret
metadata:
    name: jellystat-basic-auth
    namespace: media
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:qXZ5EFSATELh,iv:JqwZXqA30beqnVBB/XKE389IJcXs7JHlT+kvuFBuicA=,tag:mTx7cbpnk85btRFB0RyGCw==,type:str]
    password: ENC[AES256_GCM,data:C8ZedE8mTydei4AEvMFDYM3vko+aH33QQeI8LiEid/s=,iv:TTUQX7okTxzsjdrZjOOsrdLTySP4JPOnmmjmS/mQdYQ=,tag:mdNLKxm/7R1ypA9SND5RnQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5NE8yTlY3K0JCRmEveGo2
            ZDVMM1YrMHdWOUtUMlVUMzdGTC9UbzZGZEQwCkl4UkxsNmZkNzF0TXROa1RKYXo4
            c0YxeXg5bERoUVVCaWJNNGVoQU9lNXcKLS0tIDE2QmhXbHdvY1BBOFI3V3RZOHpU
            em5tV0ZQZG1ZcXhha0c0djdBRXhYWnMKRTYnt+koLreeijVY1o3s2IaxJw/hSaEB
            g+QVjlYw/e4TtflBS2elRFnepKIir3bfuYMqKrXxGCwpCW8Y7QNZZw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T12:58:23Z"
    mac: ENC[AES256_GCM,data:z7O3NfjOTsq/RGX5X2mYJ/4s5S3UV7zCCt1lbTV9OcdFwfTPkFXD+xO4PbWtGkp2qwYYJuERxR23KCLDc8DMU71dplqks/DGqkm08PZedxvWTPGSDH/Ms7xRNtZjZqbx5bkx5iUUhDUC4MI7yFbGDAhkNSry6cV8CJVobWqbto8=,iv:qMH8a/harAamRI2nOramhif8PWKHlDZlDxPTFyXtUjs=,tag:K+YaMoiNEsyQf/y7wyu2mA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: jellystat-postgres-v18
    namespace: media
type: Opaque
stringData:
    s3-access-key: ENC[AES256_GCM,data:vixoFI3ahC6drQ5UG65SyD8kgsE=,iv:uuS1FjrPayyyjdIxNC7mjEnbM4oztScwnz4M7qVLtkA=,tag:AgmCaKQcA2mlNOZs+8c3bQ==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:5yWUS2wTjiphfG46opBeM8R8gyMt11srIpVg6PDciX8FGkKSFEvsRQ==,iv:NY0GpkJuwStNCwieZbrK5IlAPCjCN/gQYNzsbTfngBE=,tag:I6HY3kHeIGoC7KsCw6A/WQ==,type:str]
    password: ENC[AES256_GCM,data:Pn0mFhzNTW+2tUitZa/Otaj+fn1qXzmna2u8XIbg/l/yb0scjalO+BBSUcgxZFqrac72+W8WklwSz9WVrv6iKg==,iv:Q2ruXKaBLBWBc4uxT+SrsF+/EsM5UMbAJfCzFSl4zC4=,tag:EXVP1cVXd3qHAeGnjNk/Ww==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5NE8yTlY3K0JCRmEveGo2
            ZDVMM1YrMHdWOUtUMlVUMzdGTC9UbzZGZEQwCkl4UkxsNmZkNzF0TXROa1RKYXo4
            c0YxeXg5bERoUVVCaWJNNGVoQU9lNXcKLS0tIDE2QmhXbHdvY1BBOFI3V3RZOHpU
            em5tV0ZQZG1ZcXhha0c0djdBRXhYWnMKRTYnt+koLreeijVY1o3s2IaxJw/hSaEB
            g+QVjlYw/e4TtflBS2elRFnepKIir3bfuYMqKrXxGCwpCW8Y7QNZZw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T12:58:23Z"
    mac: ENC[AES256_GCM,data:z7O3NfjOTsq/RGX5X2mYJ/4s5S3UV7zCCt1lbTV9OcdFwfTPkFXD+xO4PbWtGkp2qwYYJuERxR23KCLDc8DMU71dplqks/DGqkm08PZedxvWTPGSDH/Ms7xRNtZjZqbx5bkx5iUUhDUC4MI7yFbGDAhkNSry6cV8CJVobWqbto8=,iv:qMH8a/harAamRI2nOramhif8PWKHlDZlDxPTFyXtUjs=,tag:K+YaMoiNEsyQf/y7wyu2mA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
