apiVersion: v1
kind: Secret
metadata:
    name: jellystat-basic-auth
    namespace: media
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:IyESieKI4Nxv,iv:oedah/PdNPm7odu8yo+OCSH0CvWa+4Dr7Niah9PFpLQ=,tag:7ErqnQ+VoM6N64CIN9zKrg==,type:str]
    password: ENC[AES256_GCM,data:BYjkuvGR+CesZBgeM523AcvZnOA3D/v6h4+d4xRG/50=,iv:TEGd2IQR1lzYHGrBqbP2PRzBBBhy0/zumBjnIQ5Pd8c=,tag:AeJ/vuhn3WL5fkvSeOmPfw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoSytjNzlnNitlcGx4RHI1
            MnQxeVhaeERkNWNDdEN6bVQvT1ZTZmFoY0N3Ck1iY2REYUdNVU1qWk03QUhJNVM2
            Q0M0cW93WWxUekxEM0wybkR4Z3ZWdFEKLS0tIGZnNkMwNWRjeEEyY1g5R29jeTJw
            OU5kRmIwMUFFZHhNT3FodWN1dDFkejAKpRl/3K1RspapX02yYatwzzqNxkLbTa20
            2asgVmwli2RCdFHZKax/LUItecNbd0DpAkL2xmcRAsUDB4iVIWaHJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T11:39:27Z"
    mac: ENC[AES256_GCM,data:2yQL1d8sRXrCYU80FjqnosoHMBHpJ8UzL4cpmcpgsGwP6mMZLCKVErvfpntGr4NO07Qpr8kuj6FewSZ67WexIS/V7M8gcrTsLt30H0UIfkQ17s00XhNffb00AwKUvokbtQtzi/uq8vcUVtj16iykQKmCuNSh2+vFKo/uFt70g4k=,iv:gPlOlfPeJCy6nqOLTBA7cQpb/Y18KH5B+RGUII+vxf0=,tag:oJriq97p2a4Y4qWsUyr2Nw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: prowlarr-basic-auth
    namespace: media
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:KF+oRFjLDPI=,iv:xnEGlGkaoCi9n5NQANBXVap1t1HQEGwUaqnTnT1jftk=,tag:uZhYU+aQZqCogq1wtomcmQ==,type:str]
    password: ENC[AES256_GCM,data:E8vSZvWrTuUYR2O4agQSELB1HtH3ygYKrdM0zOQIn4BUZAHsZSrVljPBpCLMdYr5eLnxrIsI1aMkTjXDxX8QXg==,iv:B8EubLb5Xm4vMRrZhw9ZmKvWeS89dZBYbvrt/KkdbVQ=,tag:pn8Za+sm4H/RL8OJd1UVjQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoSytjNzlnNitlcGx4RHI1
            MnQxeVhaeERkNWNDdEN6bVQvT1ZTZmFoY0N3Ck1iY2REYUdNVU1qWk03QUhJNVM2
            Q0M0cW93WWxUekxEM0wybkR4Z3ZWdFEKLS0tIGZnNkMwNWRjeEEyY1g5R29jeTJw
            OU5kRmIwMUFFZHhNT3FodWN1dDFkejAKpRl/3K1RspapX02yYatwzzqNxkLbTa20
            2asgVmwli2RCdFHZKax/LUItecNbd0DpAkL2xmcRAsUDB4iVIWaHJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T11:39:27Z"
    mac: ENC[AES256_GCM,data:2yQL1d8sRXrCYU80FjqnosoHMBHpJ8UzL4cpmcpgsGwP6mMZLCKVErvfpntGr4NO07Qpr8kuj6FewSZ67WexIS/V7M8gcrTsLt30H0UIfkQ17s00XhNffb00AwKUvokbtQtzi/uq8vcUVtj16iykQKmCuNSh2+vFKo/uFt70g4k=,iv:gPlOlfPeJCy6nqOLTBA7cQpb/Y18KH5B+RGUII+vxf0=,tag:oJriq97p2a4Y4qWsUyr2Nw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: sonarr-basic-auth
    namespace: media
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:IMlIHmx5,iv:K5TIfdiyRH8hx8z2sqAAhM99ps6QkfKyRTx8khJcYgE=,tag:EzxMK7sKseyNR2ElHnb5QQ==,type:str]
    password: ENC[AES256_GCM,data:WIQigZMu6Qjmf++8jqyrLfrnGqVe5p7dU7mBYrJnAkGvEQ5E6dj83cgAGgKoCH4p6j91+mU9RoaT3SWMm2LHHA==,iv:gw6JVkWknIxjNEjsdP66flxLOUbWLmV6tRu6hKeOcrc=,tag:MHPC0aodXnIW3iEvFlJQAw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoSytjNzlnNitlcGx4RHI1
            MnQxeVhaeERkNWNDdEN6bVQvT1ZTZmFoY0N3Ck1iY2REYUdNVU1qWk03QUhJNVM2
            Q0M0cW93WWxUekxEM0wybkR4Z3ZWdFEKLS0tIGZnNkMwNWRjeEEyY1g5R29jeTJw
            OU5kRmIwMUFFZHhNT3FodWN1dDFkejAKpRl/3K1RspapX02yYatwzzqNxkLbTa20
            2asgVmwli2RCdFHZKax/LUItecNbd0DpAkL2xmcRAsUDB4iVIWaHJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T11:39:27Z"
    mac: ENC[AES256_GCM,data:2yQL1d8sRXrCYU80FjqnosoHMBHpJ8UzL4cpmcpgsGwP6mMZLCKVErvfpntGr4NO07Qpr8kuj6FewSZ67WexIS/V7M8gcrTsLt30H0UIfkQ17s00XhNffb00AwKUvokbtQtzi/uq8vcUVtj16iykQKmCuNSh2+vFKo/uFt70g4k=,iv:gPlOlfPeJCy6nqOLTBA7cQpb/Y18KH5B+RGUII+vxf0=,tag:oJriq97p2a4Y4qWsUyr2Nw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: radarr-basic-auth
    namespace: media
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:fMX6vO0p,iv:t612xBTSm0orw68MrWK2RQdR4/tCcrqavVgPbDZHcNI=,tag:eDbIaEcJaNkJI+HRl07rSw==,type:str]
    password: ENC[AES256_GCM,data:y0iSbUmEJ8hEvm4ik5lUX+Eu2+UG1SKwrZ5Xo3IIJWt01E0IiJ4+1zRHRUxkiFiBwTM581STpAX8OW5v4H1DSg==,iv:NyHsUp/QQTMdLpPXLZU58q5hhcKmS1cHLmDjPAS22FM=,tag:CTtzbmmurPYXzARnK65/8A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoSytjNzlnNitlcGx4RHI1
            MnQxeVhaeERkNWNDdEN6bVQvT1ZTZmFoY0N3Ck1iY2REYUdNVU1qWk03QUhJNVM2
            Q0M0cW93WWxUekxEM0wybkR4Z3ZWdFEKLS0tIGZnNkMwNWRjeEEyY1g5R29jeTJw
            OU5kRmIwMUFFZHhNT3FodWN1dDFkejAKpRl/3K1RspapX02yYatwzzqNxkLbTa20
            2asgVmwli2RCdFHZKax/LUItecNbd0DpAkL2xmcRAsUDB4iVIWaHJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T11:39:27Z"
    mac: ENC[AES256_GCM,data:2yQL1d8sRXrCYU80FjqnosoHMBHpJ8UzL4cpmcpgsGwP6mMZLCKVErvfpntGr4NO07Qpr8kuj6FewSZ67WexIS/V7M8gcrTsLt30H0UIfkQ17s00XhNffb00AwKUvokbtQtzi/uq8vcUVtj16iykQKmCuNSh2+vFKo/uFt70g4k=,iv:gPlOlfPeJCy6nqOLTBA7cQpb/Y18KH5B+RGUII+vxf0=,tag:oJriq97p2a4Y4qWsUyr2Nw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: media-postgres-v17
    namespace: media
type: Opaque
stringData:
    s3-access-key: ENC[AES256_GCM,data:U+XgbCpE2Obl9AxcDc5njBTctQ4=,iv:OwF5O/YbL4kBU8Wy8pQHF1uJgE07JnWXM8H79I5/X2I=,tag:rS9BCTCnHn0NTee2vSc9lg==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:ry7xGpyEOG4Nqr8p8KckDgkHKZTnQO4LPS9kiG+Rs0ww23idNhiQ2w==,iv:lGQedW2lBzWG+iNr5qMoYoncdpwaNYPZ2S4B/MRI9RE=,tag:n7C3b9YKXI9hbvCuwIuGJg==,type:str]
    password: ENC[AES256_GCM,data:Kn0aEvVlXGeFqQWhEWAbwhR3CBnccbO1Qf0Abht7Tbjpa2teFJqyzMSE/wKCBXhLlnV8VK/oPXe5Zo5NkLwWww==,iv:gwgq5Uz1FXPKtGyy3W+KTXKxCfMlwN3fMGCPsINUUGo=,tag:W88xgrD18sj29faqkdhthg==,type:str]
    old_password: ENC[AES256_GCM,data:9e7s49n3O7i90jbOnkloIP8nZi9Uy7PbHXPEzzqKA1o=,iv:Tlucd9axs10DURHjvDJ7+6OBPV2TE5OMUHhx2Y22ndw=,tag:I8cU+RZsfGNROY1/JzUVEQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoSytjNzlnNitlcGx4RHI1
            MnQxeVhaeERkNWNDdEN6bVQvT1ZTZmFoY0N3Ck1iY2REYUdNVU1qWk03QUhJNVM2
            Q0M0cW93WWxUekxEM0wybkR4Z3ZWdFEKLS0tIGZnNkMwNWRjeEEyY1g5R29jeTJw
            OU5kRmIwMUFFZHhNT3FodWN1dDFkejAKpRl/3K1RspapX02yYatwzzqNxkLbTa20
            2asgVmwli2RCdFHZKax/LUItecNbd0DpAkL2xmcRAsUDB4iVIWaHJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T11:39:27Z"
    mac: ENC[AES256_GCM,data:2yQL1d8sRXrCYU80FjqnosoHMBHpJ8UzL4cpmcpgsGwP6mMZLCKVErvfpntGr4NO07Qpr8kuj6FewSZ67WexIS/V7M8gcrTsLt30H0UIfkQ17s00XhNffb00AwKUvokbtQtzi/uq8vcUVtj16iykQKmCuNSh2+vFKo/uFt70g4k=,iv:gPlOlfPeJCy6nqOLTBA7cQpb/Y18KH5B+RGUII+vxf0=,tag:oJriq97p2a4Y4qWsUyr2Nw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
