apiVersion: v1
kind: Secret
metadata:
    name: jellystat-basic-auth
    namespace: media
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:EIVSVJn0fj9+,iv:Qy/WF8W0cVcNha3kZpIQVrXZGp0QRlO1jtVRoja+6tQ=,tag:l1za5rqNX1Tav1/O1zvJ6w==,type:str]
    password: ENC[AES256_GCM,data:dOdFuLqH80CWK2NWKBSBK7ewgl+Jcg/pgHBKBYBIZuQ=,iv:ZdUTdIIqBZ+g0n/CWltHo+Unn92bOkm65Y2OMylMsAM=,tag:Sm9osa5/iFp32+nSZlMAbQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZVTFrNko4Qys1K01CVHhr
            eUxWd1VmWmorUEZObk1QYW5mUDNFUVFyNmxvCkNlRmlhSDRwWnl4WU5pbUdmM3I2
            RnllTm5DYml6U0VuTmFPR3o1MTJoc0UKLS0tIG43SzdEMnBHY1pZVGFicDMwYmFP
            M0hwNTlkdEU3SDhSN0d0SUMrcHV5STAKyA8DluUkZxm2HrEMFGO14I3t9V1sh0P4
            YS7D6iE3tt685gSqz9S1YnBH2d1EKC6qnw/xJq1oW4Diap5n/s/R6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T12:15:27Z"
    mac: ENC[AES256_GCM,data:JR650p0WATmVxwntDKEUSPxGh8qjXhVDv5jjIAJw5GMZr6pWjRdRkm47cLcRHmj4oy3OwgmkmjlETB2oReYXihuZ8SlyL1V0Uus27FUvJkCkw0K3od+Zpdo10YtgLzJ2QWWjYdFbPgYVxp+As78IayD2K4OUbwaR9vLKc3M8jKA=,iv:IipZHDO4ZLwStAxm+d15mzMiKLXmMAwoGQKK4LCoyD8=,tag:2vaMXfy9Wq6+nm+L3dOfsQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: prowlarr-basic-auth
    namespace: media
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:P1iVb5D2Gf4=,iv:qi1q58yt8H/UQXN0SuhabWpbnHNjri6l4KsDGN0r2XM=,tag:LOI5RHfN12CoApIakJba9A==,type:str]
    password: ENC[AES256_GCM,data:8JfOoQz5sHoeBRECwoZRXR5igLoSoRNPMUWL0GOEMU71EWIkCmLLVV6HK0qMP8V4lP4a6mtODHdbaTh3WrIbOQ==,iv:+x3z8vChbqPUfnGGXFl6k56JpJTQt1DLMkRezT8F14o=,tag:Zwh0pn0YsSFc2MF7EZI8lw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZVTFrNko4Qys1K01CVHhr
            eUxWd1VmWmorUEZObk1QYW5mUDNFUVFyNmxvCkNlRmlhSDRwWnl4WU5pbUdmM3I2
            RnllTm5DYml6U0VuTmFPR3o1MTJoc0UKLS0tIG43SzdEMnBHY1pZVGFicDMwYmFP
            M0hwNTlkdEU3SDhSN0d0SUMrcHV5STAKyA8DluUkZxm2HrEMFGO14I3t9V1sh0P4
            YS7D6iE3tt685gSqz9S1YnBH2d1EKC6qnw/xJq1oW4Diap5n/s/R6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T12:15:27Z"
    mac: ENC[AES256_GCM,data:JR650p0WATmVxwntDKEUSPxGh8qjXhVDv5jjIAJw5GMZr6pWjRdRkm47cLcRHmj4oy3OwgmkmjlETB2oReYXihuZ8SlyL1V0Uus27FUvJkCkw0K3od+Zpdo10YtgLzJ2QWWjYdFbPgYVxp+As78IayD2K4OUbwaR9vLKc3M8jKA=,iv:IipZHDO4ZLwStAxm+d15mzMiKLXmMAwoGQKK4LCoyD8=,tag:2vaMXfy9Wq6+nm+L3dOfsQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: sonarr-basic-auth
    namespace: media
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:H2WjTqnU,iv:L9Bp8pzWdaEjXh/AZdGUd+9EFocRCBKTTEt/9EJe6Mg=,tag:yy22h/yzJjXa5zc/H3cOhg==,type:str]
    password: ENC[AES256_GCM,data:/X1GIiLBxdrT1C5iPZJxUHDqsEvDNzKOs4DyBfwd3TzcqbVFJhRPTynttqp4mj/vr+95GzqaD4+P/Hem0P+7Qw==,iv:R3PFefEVuaivtOUnupXAvM/ZXbiUF6BZUQv5ULWWvA8=,tag:XR+l7MSJyJFeqxbPzLjd7A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZVTFrNko4Qys1K01CVHhr
            eUxWd1VmWmorUEZObk1QYW5mUDNFUVFyNmxvCkNlRmlhSDRwWnl4WU5pbUdmM3I2
            RnllTm5DYml6U0VuTmFPR3o1MTJoc0UKLS0tIG43SzdEMnBHY1pZVGFicDMwYmFP
            M0hwNTlkdEU3SDhSN0d0SUMrcHV5STAKyA8DluUkZxm2HrEMFGO14I3t9V1sh0P4
            YS7D6iE3tt685gSqz9S1YnBH2d1EKC6qnw/xJq1oW4Diap5n/s/R6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T12:15:27Z"
    mac: ENC[AES256_GCM,data:JR650p0WATmVxwntDKEUSPxGh8qjXhVDv5jjIAJw5GMZr6pWjRdRkm47cLcRHmj4oy3OwgmkmjlETB2oReYXihuZ8SlyL1V0Uus27FUvJkCkw0K3od+Zpdo10YtgLzJ2QWWjYdFbPgYVxp+As78IayD2K4OUbwaR9vLKc3M8jKA=,iv:IipZHDO4ZLwStAxm+d15mzMiKLXmMAwoGQKK4LCoyD8=,tag:2vaMXfy9Wq6+nm+L3dOfsQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: media-postgres-v17
    namespace: media
type: Opaque
stringData:
    s3-access-key: ENC[AES256_GCM,data:4qEbA71OrqiG1x7dW/FKLmI58qA=,iv:g27qO8W5WRe4L9ARz1iHVDrvKbOxpls31V0KOkwNQE0=,tag:u0ac53gZVRt4GoUhiGcFtw==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:/UzLD5T2F/N3y1JpZ7weSJK/fom258FKTg29gAebXTjB2ifPPIPf8g==,iv:Loutsr0eBPDWLyS6n7kd+h0zCo6OmS6EaWORfhme7to=,tag:xJJLJd3sCpAi0CKZ5OwJYA==,type:str]
    password: ENC[AES256_GCM,data:M4ZUtKGooxEcVm47TpUatBm69yIpda4pTPbc+KVuPfM/Z0AJ/uQuxA/9Pw4MDHNCPMMgdojCfkiEJeMYk8axNw==,iv:ofe3925EbFL6OTXCUk3RSzFmA3RSSCtK7rW7jum1Zd8=,tag:RmgBmnF5jp2CS+vJAEPjIA==,type:str]
    old_password: ENC[AES256_GCM,data:0bv4Uv/2UC0dMTrQerZuivfAduJvqnLgq6cDlbpnXT0=,iv:xn7TuAqk2VAkBMfpAVYk1QYXxkwfAzs8HOD62LBKGKw=,tag:GFeSF8E+Tke+QjYZwTz6xA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZVTFrNko4Qys1K01CVHhr
            eUxWd1VmWmorUEZObk1QYW5mUDNFUVFyNmxvCkNlRmlhSDRwWnl4WU5pbUdmM3I2
            RnllTm5DYml6U0VuTmFPR3o1MTJoc0UKLS0tIG43SzdEMnBHY1pZVGFicDMwYmFP
            M0hwNTlkdEU3SDhSN0d0SUMrcHV5STAKyA8DluUkZxm2HrEMFGO14I3t9V1sh0P4
            YS7D6iE3tt685gSqz9S1YnBH2d1EKC6qnw/xJq1oW4Diap5n/s/R6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T12:15:27Z"
    mac: ENC[AES256_GCM,data:JR650p0WATmVxwntDKEUSPxGh8qjXhVDv5jjIAJw5GMZr6pWjRdRkm47cLcRHmj4oy3OwgmkmjlETB2oReYXihuZ8SlyL1V0Uus27FUvJkCkw0K3od+Zpdo10YtgLzJ2QWWjYdFbPgYVxp+As78IayD2K4OUbwaR9vLKc3M8jKA=,iv:IipZHDO4ZLwStAxm+d15mzMiKLXmMAwoGQKK4LCoyD8=,tag:2vaMXfy9Wq6+nm+L3dOfsQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
