apiVersion: v1
kind: Secret
metadata:
    name: jellystat-basic-auth
    namespace: media
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:q9nHFoN1k/3Y,iv:9bi8AgzenlBtofP2fclWUQCc/ngGzyvxHUOkL8x9uRU=,tag:WGzZ5NhsvdugIsb1tp/AMw==,type:str]
    password: ENC[AES256_GCM,data:sm2qFwXi2f9PzUFwo0C/5Jmg55ZbSra/QMpBJuPMHGs=,iv:T08I80d+5KvVB8Y5PFOj2ZWXjPZ+Ef462foYjHGJZtQ=,tag:TGnUROmDTiBZOGKWTr2UYA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2NG5KcHdKT3loU2lPSWRW
            Z2FpVUNEUlZENGVnL3JibUhjNHRGRGVMQUF3CmlUS2E3NE02RnlnWUxTRzJFaDBV
            M2llMTJ3eFI0aVRSczZITks2VGlwbXcKLS0tIC9CMlJwTGUxYVhScGJuaW5OVHMv
            d2lsWVY4L1lLWDdlUldlRmxFdmM1UW8KP9ZxfbynJ6L7SfDwk9wdWIrbVoYojUCo
            vNGS6f59uwoT75LHvRDwBSTtO92hEP+V78ZFhniG4sWxGW3yDsQCKw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T12:51:24Z"
    mac: ENC[AES256_GCM,data:d22Eo64bJO49Ptr6yGueC6vNRQLLUxnT4gWW1yqYcXtpXprD4CAMUOY2ciGOXTT6Ui3AnEx2E2Dwy0d1gww7bnH5g5ihpmrS9bZDmZJ4kzUxahQPESZBAnPKML6JdIdtqRq2djyVZBZvbbzSDf3uFDynq7QYWYbUa+6gVRm8Vd8=,iv:ppK3r03didRpXkTqvKBpjiorIAtOkFmAbkrSuhU9Q/Q=,tag:G3WViMpQagec5DzXZ+nCnA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: media-postgres-v17
    namespace: media
type: Opaque
stringData:
    s3-access-key: ENC[AES256_GCM,data:Sp7ewcPhFOe+IoCNwrCr9IzQ2dg=,iv:n4XA7lxLlHdwKI/MiWwrbMjkc4I3LJyzxslCCGTx5+I=,tag:+oNgGjmt54A/nxg79jC4Sg==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:pZ3VCd6uByDFdrNLDHwSiMHX/HDb6zQQ+kZCxLCr0fQYucauTF+Fbg==,iv:OS/mCsMgnMwt4l9FI/7qZndLsX+Bema4UoqZcuT4k1M=,tag:4c0sZxh6WppOXoHkzFQiug==,type:str]
    password: ENC[AES256_GCM,data:EacPLaZermZKn2aexitm0HD1rSxBKCpG66kuKgl2Hlsz0FynG/Y9Q29EvVSGHrQuJB8baOHmRC82oi/vjBNC0Q==,iv:kyeS1iguJaVfzJQbvl0K1ObSmmAfHGQAn7bf9nM0ov4=,tag:ilEJmnP0Aahs3EyqOi2eKQ==,type:str]
    old_password: ENC[AES256_GCM,data:nTjKzbAiKKmTZm9CHOYN67cLpv8p/9A7irreldXLW34=,iv:pycd514i/9Ba5BUXvwOgNPFnAbElXIi/ubElZCePIMQ=,tag:w6NBD5WYlkDwFK7esHr6YA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2NG5KcHdKT3loU2lPSWRW
            Z2FpVUNEUlZENGVnL3JibUhjNHRGRGVMQUF3CmlUS2E3NE02RnlnWUxTRzJFaDBV
            M2llMTJ3eFI0aVRSczZITks2VGlwbXcKLS0tIC9CMlJwTGUxYVhScGJuaW5OVHMv
            d2lsWVY4L1lLWDdlUldlRmxFdmM1UW8KP9ZxfbynJ6L7SfDwk9wdWIrbVoYojUCo
            vNGS6f59uwoT75LHvRDwBSTtO92hEP+V78ZFhniG4sWxGW3yDsQCKw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T12:51:24Z"
    mac: ENC[AES256_GCM,data:d22Eo64bJO49Ptr6yGueC6vNRQLLUxnT4gWW1yqYcXtpXprD4CAMUOY2ciGOXTT6Ui3AnEx2E2Dwy0d1gww7bnH5g5ihpmrS9bZDmZJ4kzUxahQPESZBAnPKML6JdIdtqRq2djyVZBZvbbzSDf3uFDynq7QYWYbUa+6gVRm8Vd8=,iv:ppK3r03didRpXkTqvKBpjiorIAtOkFmAbkrSuhU9Q/Q=,tag:G3WViMpQagec5DzXZ+nCnA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
