apiVersion: v1
kind: Secret
metadata:
    name: jellystat-basic-auth
    namespace: media
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:Dpfqvn3ptjDD,iv:YD6E0/p2TXU0TZbEMefxHckjzP8gP77O9gfbDPqVdA0=,tag:V/ZmvWpRJcMgqeM6Qa12ew==,type:str]
    password: ENC[AES256_GCM,data:XW5FnhAWnhaCi5zEwk3inJZzgX2u0lde3v0dZoo8yb4=,iv:DUIE+rrIgc2DLTWUjIWteop6eSkxBPBR/qmZxjmS9Nw=,tag:RioK+LlX3AscBTfG8r/2Kg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJUW1EaXVSaGEwckw0NlZH
            QW9lY2R0RGlxbjdnYmRQSC9OWnZ5eUtWS0I0CllkVy9LOE9VYm8waTE3eC9vMUky
            UG9HT1RNMXN2K1pVbjZ0V0x0UlNyeTgKLS0tIENxUEFGSVB3VWdzZDZOVi8rbTJP
            eVk4bW55TG9Delgvd0lyby8ycTBKSlkKaJqyEI8h2uH8HUeAJ5ds8SdsJjrwF4pR
            9ZYbgdTt1pjlgTdX2x4ea2tBoDnUqM1tvXUxuhiTXcQo6ZE9CM5ntQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T12:30:13Z"
    mac: ENC[AES256_GCM,data:WObZTIAkkYw6mmAR1td9lORZaw5ksArB4LQqk6zXdtjnwjpOUnPpSiOumo+sj+/L9eDGzR+HH4XKg84Ua/oqMPiAgGrI8H6I9b7fYLcxbK0bXKOT5+ur73UJIXo9kL5QhF5MIpLyCglEKXA7XwwA4ctdDJkdMq3zfGB6n498qDc=,iv:nbueKgtSC7OVArHiFQfZwgN1TQ9S3BT26MmSkWR3pEk=,tag:PuPEey3SRLmVXJ5C5yhpYA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: prowlarr-basic-auth
    namespace: media
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:2HPjv9dh/nk=,iv:kWTrKbQyY/UTnxvxLmphq7FRGYGGFDQzamks3JeGS0g=,tag:Yc9g5b2bhj17iKamFyumyg==,type:str]
    password: ENC[AES256_GCM,data:R0S8DOpMmB7CoFuelAen9/MUW0X4c/ibczwAwyXP+6S1XICKqfddosZWp5vj2BQ+Bu0cHO9yt6ef8Y31x8eTYA==,iv:ww+U0oQk8IWtmSaAXsgadC48xn7HEwtIV6vATKTLeh0=,tag:MW3EJVZiBXeZAYEfaPd/RA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJUW1EaXVSaGEwckw0NlZH
            QW9lY2R0RGlxbjdnYmRQSC9OWnZ5eUtWS0I0CllkVy9LOE9VYm8waTE3eC9vMUky
            UG9HT1RNMXN2K1pVbjZ0V0x0UlNyeTgKLS0tIENxUEFGSVB3VWdzZDZOVi8rbTJP
            eVk4bW55TG9Delgvd0lyby8ycTBKSlkKaJqyEI8h2uH8HUeAJ5ds8SdsJjrwF4pR
            9ZYbgdTt1pjlgTdX2x4ea2tBoDnUqM1tvXUxuhiTXcQo6ZE9CM5ntQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T12:30:13Z"
    mac: ENC[AES256_GCM,data:WObZTIAkkYw6mmAR1td9lORZaw5ksArB4LQqk6zXdtjnwjpOUnPpSiOumo+sj+/L9eDGzR+HH4XKg84Ua/oqMPiAgGrI8H6I9b7fYLcxbK0bXKOT5+ur73UJIXo9kL5QhF5MIpLyCglEKXA7XwwA4ctdDJkdMq3zfGB6n498qDc=,iv:nbueKgtSC7OVArHiFQfZwgN1TQ9S3BT26MmSkWR3pEk=,tag:PuPEey3SRLmVXJ5C5yhpYA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: media-postgres-v17
    namespace: media
type: Opaque
stringData:
    s3-access-key: ENC[AES256_GCM,data:tlfNLme/aHbISTvKw4lu1wm9uu0=,iv:k65CjAxqJdPs97uq/Rh5JyjBUMju41SQlfDWKmMTeps=,tag:tm6cC7OobeHPem345n2OPA==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:IdeFO/SG2v/nBbvrYfVYos3xDqA1baWnYhczGmPtpH74UD2sxP4BGg==,iv:SkB3qUl6msaQ+zTVRu5HQBAX2Z+Wsf0W8KCfPpx0WO8=,tag:DEPxBhUUFyWyJlIxX3zJoA==,type:str]
    password: ENC[AES256_GCM,data:LpKVwcYU1XwdlCocEkr2EfWolpAgijMpGEjWbYu/J+HSFvx6PgqEgu1GeohHOmXKevxEmSl+gbwJYuWFUP+QTA==,iv:nHGv8FLB/yPEEsR3wBlUSsArB117AeVO3/ozJ0r9A/4=,tag:8Kkw4wl3avSKxOs82nuZ6g==,type:str]
    old_password: ENC[AES256_GCM,data:oCu2gxJYAlJODejP6Dsjy9WGK2WzoscgxLIu+Bgf4K8=,iv:qw3BE8EyXWoj1NgjLtjZqrhnEYGJfTHKecPkzS535xw=,tag:1NibUfVqqIkA3OzfVw4JQg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJUW1EaXVSaGEwckw0NlZH
            QW9lY2R0RGlxbjdnYmRQSC9OWnZ5eUtWS0I0CllkVy9LOE9VYm8waTE3eC9vMUky
            UG9HT1RNMXN2K1pVbjZ0V0x0UlNyeTgKLS0tIENxUEFGSVB3VWdzZDZOVi8rbTJP
            eVk4bW55TG9Delgvd0lyby8ycTBKSlkKaJqyEI8h2uH8HUeAJ5ds8SdsJjrwF4pR
            9ZYbgdTt1pjlgTdX2x4ea2tBoDnUqM1tvXUxuhiTXcQo6ZE9CM5ntQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T12:30:13Z"
    mac: ENC[AES256_GCM,data:WObZTIAkkYw6mmAR1td9lORZaw5ksArB4LQqk6zXdtjnwjpOUnPpSiOumo+sj+/L9eDGzR+HH4XKg84Ua/oqMPiAgGrI8H6I9b7fYLcxbK0bXKOT5+ur73UJIXo9kL5QhF5MIpLyCglEKXA7XwwA4ctdDJkdMq3zfGB6n498qDc=,iv:nbueKgtSC7OVArHiFQfZwgN1TQ9S3BT26MmSkWR3pEk=,tag:PuPEey3SRLmVXJ5C5yhpYA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
