apiVersion: v1
kind: Secret
metadata:
    name: media-postgres-v17
    namespace: media
type: Opaque
stringData:
    s3-access-key: ENC[AES256_GCM,data:tXZkWNWzYVIQaI1gaFwlCB/GZiA=,iv:YcIs4JLty9YX6Nvq5xiQNpry1NpL9FAUx7fTy7oRPco=,tag:Xa1JqFds1V6rxmQQZKU7QA==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:2w/sbLBb6EL04Tb983/f4ZFX9tROunQmsh52yZ+KuEEJo80EMCqzJQ==,iv:Ll1JSvfIIxKr9QGpmGqMV3Dmjh4X3ysSORHioIGdnh0=,tag:vqXuF82OcCNNQrTU+J9UAA==,type:str]
    password: ENC[AES256_GCM,data:mIXccGizdzhSj/9AEBOhm+Vt3Yz+fh/mkHtiv+7JIY6axYfooRorZ+9NtOlA0x2MZqW8nJ5aDsRnXW5VVgV0dA==,iv:XDNVBwvOVSkc0Xy6aKR7cimiWkPcE/H17XbSEbkU7p4=,tag:IrNVRLgCYCn5afxNlzsEJA==,type:str]
    old_password: ENC[AES256_GCM,data:f6EcxY+unBz6UV0IqD0fwED+5TGPlqNn69/2Kr6rYx4=,iv:e6Z3burBOoBGYUKHhGXKQn+fS4fXvOa3KzobSn5ueIQ=,tag:lphJ9kMsILvY1XxquwWfbw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArWDdxNWY5SjRTdERwc2d1
            RzhVM3B4QncvY2laa1pzeVA3dk83S0xxa0I0CkRqZUdpT2ZCdXlobjFYL2pteEhV
            WmJTWHRnR0Q4dXZuMS9DWmRjSTdtOWcKLS0tIFpVZERpNzJKNHNXVlFnUHFINnpw
            d3VlTEl0R0xjTzN4VlFpWjh6NGt2eTQK7ccQeLAofzpU3ZHvBaiU807NlDM2/xOC
            VY7PnoDDsGvIpYCc4QrVN4UyJ8hoZJoQKRqmyCLQaFjeMZxsn67eUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T13:00:44Z"
    mac: ENC[AES256_GCM,data:ARgjC4sbcbKrwGasTQ1XW9U7eiSWkzWvTZNw7H0beGFo8Gykdp/Anp9vjsaE70Rvt83E0hY4124KWsQnh+xj99t9BFU9xA9qUM8AdxObB0OUlOpuyw4EAXECx8LEJFbfAvkeVmh9WjP79dgkhzBS/yCQsv22tVFXpqdsyUKPjK0=,iv:HW57zGngsEf+Nr2CXYKI14VxhIMj7PMKUhd7y9u5QcI=,tag:cypFGevXBXGPVKGCGwlq9w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
