apiVersion: v1
kind: Secret
metadata:
    name: romm-basic-auth
    namespace: romm
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:+p9LyQ==,iv:6wTmafCzs74PTqAQEVhA0XYh1rIZkkRvjljYmraoFrs=,tag:zdGXZ3F3MZtqwsXQ4Ni56g==,type:str]
    password: ENC[AES256_GCM,data:Gw6nc6Xx600xL23FirZmbr9f9kzlqbKNqWA9uHCjPg5yCfvCp9t6IrRoMSMM+05O/urGfNECg7w69qXYkj/y9w==,iv:sX5H2382KN1EF0XQw29G3VjPorCfOhgQfGg2Mksxn2c=,tag:Aq/Z08fqHJBzvEP9psIeUA==,type:str]
sops:
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqSis5N0JCTy81N3ZRc2lN
            OXBTUVdKdUFjS3hHazlvYjA3SkJsdVgwWEQwCmdoSWphcG1LOXhmSkYxUU5iSDhj
            aGVZYVVXM01wSGxWaDNUamNkeWxpNzAKLS0tIFh5UGpUR1p6Q2RjZzYvc3JvZjZz
            dWJxWXlRZ0RxOVEwbHA2TVNRYVE1N2sKmDPWDp2PRLKs0hws4QUMF1AEg35T2NXE
            6KBpLKUjIX/ATCNBB1kYB+0QREo1a1geVYK2DUWa7/WG32nhsbDwQw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-17T21:12:36Z"
    mac: ENC[AES256_GCM,data:fx9RpMx3ljwZX01tVn/AvwoemQLqes7LTKw6moreZN4wdDgBzhl5CvgyMi9pkZZl9HNEUVu7KzvgQHhn0M/qTu627OHrTUoYsyOCyEZr5SHGjwgEuMfq89A4z/5wTZo9Ni/W6XLEF4geQkOM+qFoXItrqsc179yx8E1TSCklaok=,iv:lv4IxLgoKKhtZz6Rj+cFn9GKQiye58G/b6cwEiDAeuM=,tag:JVME93bEOXCqeHfUbm50mQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: romm-postgres-v18
    namespace: romm
type: Opaque
stringData:
    s3-access-key: ENC[AES256_GCM,data:oE0CrIVV3ORIX2A7qhmfItAmvd/P5ZTWCeg=,iv:r7Ev9+4QnWoThA9yuPj705JQHmUwmwUAilldpinOlq8=,tag:vZJKOi6U44WldU713jsxrA==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:Pvh3U+pxiPrhDi3Zaf1pX3t+yXws+IszKLVCMRd8I4eZ7uHl67/SmwdgF4Umv1E0Dq0+an7OI7Gx1JqK2bZFzA==,iv:1ASOqC3jzBvw8g3rt0jlcyeyI5MK+Sqp9ViABd2M5iM=,tag:61tHlfYkelqQCPiEcKJcbQ==,type:str]
    region: ENC[AES256_GCM,data:FFM2Jyu5,iv:xUvNwQHuKYNCNcjw5EQUCxhhZwWVmdrpWsbtS4JDSr8=,tag:/3MOz6uiS1Fc0voi200dCA==,type:str]
    password: ENC[AES256_GCM,data:95kNvrXDMVWo/pYso+96cNyV+Bc1kRBCnwvkeKiEKZJfBqVup5ImUUEomqEtFym4cteoCk7gP1sgONfYe7XDdA==,iv:Na3fTnMl3IoRVt7ZY4+PqQFmufriyvITaosoQ4e26X8=,tag:+y0WbEUd1kFK6bhNXh2kgg==,type:str]
sops:
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqSis5N0JCTy81N3ZRc2lN
            OXBTUVdKdUFjS3hHazlvYjA3SkJsdVgwWEQwCmdoSWphcG1LOXhmSkYxUU5iSDhj
            aGVZYVVXM01wSGxWaDNUamNkeWxpNzAKLS0tIFh5UGpUR1p6Q2RjZzYvc3JvZjZz
            dWJxWXlRZ0RxOVEwbHA2TVNRYVE1N2sKmDPWDp2PRLKs0hws4QUMF1AEg35T2NXE
            6KBpLKUjIX/ATCNBB1kYB+0QREo1a1geVYK2DUWa7/WG32nhsbDwQw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-17T21:12:36Z"
    mac: ENC[AES256_GCM,data:fx9RpMx3ljwZX01tVn/AvwoemQLqes7LTKw6moreZN4wdDgBzhl5CvgyMi9pkZZl9HNEUVu7KzvgQHhn0M/qTu627OHrTUoYsyOCyEZr5SHGjwgEuMfq89A4z/5wTZo9Ni/W6XLEF4geQkOM+qFoXItrqsc179yx8E1TSCklaok=,iv:lv4IxLgoKKhtZz6Rj+cFn9GKQiye58G/b6cwEiDAeuM=,tag:JVME93bEOXCqeHfUbm50mQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
