apiVersion: v1
kind: Secret
metadata:
    name: romm-basic-auth
    namespace: romm
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:7Qfq7g==,iv:bWGj+gHDxx37YdLhFSCh4nRXNU+ITexX5sWLweGq5jg=,tag:NtHilihPVR5k4hXJLeVC0w==,type:str]
    password: ENC[AES256_GCM,data:kO9Rmh4/V6M5QcaKCRmL9UUZR6NxNol1XDLkNgZ4y12/DqG6jEkc49rl0PZYaJCUks6yR21EX+laIuzrE15Bzg==,iv:LC2L1Mr+KGcyjXEzCRsDVtDZkdGZdcWsswmL3nfPSxc=,tag:cp5z2BshGQwLIir+71Lj5A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYVzdPT1Rob2ZscUlFcTdG
            S0lwTW5HbEdyMm9NRFZCQjJLbHgrRjd5cHdnCm5ia1Z0Y1B5NWdYM1JYaEVEMnpW
            MG5HOEtHMUJYYlNjV0I1d01TckExNFEKLS0tIENoL1JjamhIY2FxS2J6WUJQMDZa
            R1RQOTFDYy9rZFJmL3JwSlVOSEJNSEEKRWGs5S56uEDdR2F9Pu3IDbbSmhRGU20B
            25mUrzHway9i2Yrw08QOf9XUoB2HsfO/xzNOYWDpLyyrnaVJQiqyag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T00:00:36Z"
    mac: ENC[AES256_GCM,data:sHWq+4heZ/kNI8M34BXI/XbPWUOA9tv6fO7QbKGiC8uG6KBaAOxfCo71KkyQ3dYtgqXCNAh6CW8Gd+SspETRhi6seOWIX4pKAaVtdck6xhREKeDaQvEUzXlcTvAipgbqt66al2gM1uju/LN/pnFfGbLUkAJHeDwBwYXz6qSvgsA=,iv:mvgPziFSdo1mLUBaGMgHx4cvP4StfskPjE8tapbOdKA=,tag:uHthgoHzN12gmh93W/uFIw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: romm-postgres-v17
    namespace: romm
type: Opaque
stringData:
    s3-access-key: ENC[AES256_GCM,data:n05IHqdkhBKRxBsmuHEaVOu4rJ0=,iv:4S2LNeZvabC6qfa8CLfFxav3eiGs2BDNh1JNNbQNMDg=,tag:IOsaCi2yH918g62Ps72UKA==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:Sv+cEenz60Ljnp2ScjdBUsd/sTNql9JkZr4QcIxc7qfi60pv4A7p5A==,iv:Wm9Ns2dmiz0C+VLDqig0sahqa6/oXy21qw4vXdm/mBE=,tag:sTBeGD442EL9wBeGE3uFjw==,type:str]
    password: ENC[AES256_GCM,data:LG19uPVgR9nf2wKBcMKBbPDCL4hGQnT2vqtQ0BJk15k+XpXLnO/LSkSJIWIE+6w0/frmjTIJmWjISzxoSf/5oA==,iv:4qeATuLhrNRrET4G/y7IJzWpEzj78yhMEVpxL9Pl3gQ=,tag:tKy73J9nW2kFXqxiyb+U7w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYVzdPT1Rob2ZscUlFcTdG
            S0lwTW5HbEdyMm9NRFZCQjJLbHgrRjd5cHdnCm5ia1Z0Y1B5NWdYM1JYaEVEMnpW
            MG5HOEtHMUJYYlNjV0I1d01TckExNFEKLS0tIENoL1JjamhIY2FxS2J6WUJQMDZa
            R1RQOTFDYy9rZFJmL3JwSlVOSEJNSEEKRWGs5S56uEDdR2F9Pu3IDbbSmhRGU20B
            25mUrzHway9i2Yrw08QOf9XUoB2HsfO/xzNOYWDpLyyrnaVJQiqyag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T00:00:36Z"
    mac: ENC[AES256_GCM,data:sHWq+4heZ/kNI8M34BXI/XbPWUOA9tv6fO7QbKGiC8uG6KBaAOxfCo71KkyQ3dYtgqXCNAh6CW8Gd+SspETRhi6seOWIX4pKAaVtdck6xhREKeDaQvEUzXlcTvAipgbqt66al2gM1uju/LN/pnFfGbLUkAJHeDwBwYXz6qSvgsA=,iv:mvgPziFSdo1mLUBaGMgHx4cvP4StfskPjE8tapbOdKA=,tag:uHthgoHzN12gmh93W/uFIw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: romm-postgres-v18
    namespace: romm
type: Opaque
stringData:
    s3-access-key: ENC[AES256_GCM,data:/ipUbcrrbaMssg8LO8WGXeY7r+c=,iv:FEKm7hxNaD9xTvdOPrGW9b+o3BHidGVusCulqLhraGw=,tag:Ar/FpzldfglkzpULV2faqQ==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:DwDf4Z7PyeKJF0w747+R4K/EKzn4bCkrm2J3J2GnpbR0vKK2JpbKcw==,iv:D09JweXzeOboMlww7FHgBJQNCjwDkgePUip0jukM9q4=,tag:DXCh9EnCK97VqR+borMSTg==,type:str]
    password: ENC[AES256_GCM,data:mc2Bbi2oi2cw7AeEhVnjEg8fjwQMBQtVR/ARYBA6DmdX8wqREzYNaVbESFK6iGs9B/A8mflHb+ku6SeyWgT6Sw==,iv:WrD2Tgun9Y6fU0L8x1HLUPFIXLU9LeGhyELtfVozAiE=,tag:B+3qPDgUxbZVWcFzrRqjeA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYVzdPT1Rob2ZscUlFcTdG
            S0lwTW5HbEdyMm9NRFZCQjJLbHgrRjd5cHdnCm5ia1Z0Y1B5NWdYM1JYaEVEMnpW
            MG5HOEtHMUJYYlNjV0I1d01TckExNFEKLS0tIENoL1JjamhIY2FxS2J6WUJQMDZa
            R1RQOTFDYy9rZFJmL3JwSlVOSEJNSEEKRWGs5S56uEDdR2F9Pu3IDbbSmhRGU20B
            25mUrzHway9i2Yrw08QOf9XUoB2HsfO/xzNOYWDpLyyrnaVJQiqyag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T00:00:36Z"
    mac: ENC[AES256_GCM,data:sHWq+4heZ/kNI8M34BXI/XbPWUOA9tv6fO7QbKGiC8uG6KBaAOxfCo71KkyQ3dYtgqXCNAh6CW8Gd+SspETRhi6seOWIX4pKAaVtdck6xhREKeDaQvEUzXlcTvAipgbqt66al2gM1uju/LN/pnFfGbLUkAJHeDwBwYXz6qSvgsA=,iv:mvgPziFSdo1mLUBaGMgHx4cvP4StfskPjE8tapbOdKA=,tag:uHthgoHzN12gmh93W/uFIw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
