apiVersion: v1
kind: Secret
metadata:
    name: romm-basic-auth
    namespace: romm
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:PohnRg==,iv:pNVTtFphA0Ql7TALuzRdEy0bZkkCKBb4DvfFv4peZjI=,tag:rKNzdv+1N/1avh0ajuPFLw==,type:str]
    password: ENC[AES256_GCM,data:B7yBziewyHeHwAmHojlHztKQ37c/JUgFRkZiE//jToracBdZXKZznw+ZaGVDsooMo/vtDTuZ0DyGy6cUAvJ8qQ==,iv:/y6oHEXqaukRJql1lRKS4TER8vAbRhytXuPwLyeSTKY=,tag:7IuaFSSb4kbRMqx/WyNS+Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5TldSSC84Q2hhekVjamEz
            WFlsSngrdDM4elZtRFA0c0plT0hOcUY4ekZvCkJtTEVNL2NPdHhOQ01UYW1qS3Jw
            YnJtMWdSTDRRb1JYRm9XWE5lOUJVTlEKLS0tIGYyWmcwbTJXVEhZV0lBL3JDbTE2
            VzhrZVdib0tHMlpiME9ic1hDMWhDeFUK+CAwYs+xHxwgwDHWoDn/8+i9uVyipUuv
            3rS59Oqq/8Wu80wW8/Vs6wJhaO+z7iNUORMsWqUk2dKKp3Hq+8mliw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T00:42:53Z"
    mac: ENC[AES256_GCM,data:PmkKpiZcq1cmT2hSGv64SMUYzWINZUcNmpXU/I8Uq55axOroA4wezwAlu6fvEYRWm6WS++MRj9s53FqXBivCgxrhGmVQzPjBPD5N88bOZ4Q7A+CeozFtnGXxiZrh0PgTblG7w5FcEwNwk86PafYxk9hsnMGSP4o7ACJ11lWaQTM=,iv:lO8VTg65n1/gslvsPojlDwarSaT2Qw0GM54lEx7p1h4=,tag:xkGRK1wRih5rkWy3HgZ3eQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: romm-postgres-v18
    namespace: romm
type: Opaque
stringData:
    s3-access-key: ENC[AES256_GCM,data:7LPLorMZfyGRr1ABh3KFrm1Ggjs=,iv:7zKdd/7ZcCf+WaZAg+axqqhn1ckB2JlSTd0ZSxrRAg0=,tag:eT4ITD+FnS5QkFGX401TmQ==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:Yw0RtCnd19VdAxTrzp2AjQvvAY9gD8RBtE/iaWdZCuvIzfs/KrGNmQ==,iv:JkE7Aa0Sqo9CkBtLPfND6YSgrWsoQU3/44HmIarBduE=,tag:jCtna5yX5swozCre5WIs1Q==,type:str]
    password: ENC[AES256_GCM,data:vcWbN4b3KrlK/CVJolJ4FOv/POCudLOZIUbE/K5wXmkcxiW97Pnl7Wpc5QBclQkjfxxm/kpdf9LWfNot37Bs2w==,iv:mTFLcogwueXMt/oXfJlWG3rFwudqCEW7Lhf7Zu6D/1g=,tag:l2QIMKBBymaI9oG9GJe9SA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5TldSSC84Q2hhekVjamEz
            WFlsSngrdDM4elZtRFA0c0plT0hOcUY4ekZvCkJtTEVNL2NPdHhOQ01UYW1qS3Jw
            YnJtMWdSTDRRb1JYRm9XWE5lOUJVTlEKLS0tIGYyWmcwbTJXVEhZV0lBL3JDbTE2
            VzhrZVdib0tHMlpiME9ic1hDMWhDeFUK+CAwYs+xHxwgwDHWoDn/8+i9uVyipUuv
            3rS59Oqq/8Wu80wW8/Vs6wJhaO+z7iNUORMsWqUk2dKKp3Hq+8mliw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T00:42:53Z"
    mac: ENC[AES256_GCM,data:PmkKpiZcq1cmT2hSGv64SMUYzWINZUcNmpXU/I8Uq55axOroA4wezwAlu6fvEYRWm6WS++MRj9s53FqXBivCgxrhGmVQzPjBPD5N88bOZ4Q7A+CeozFtnGXxiZrh0PgTblG7w5FcEwNwk86PafYxk9hsnMGSP4o7ACJ11lWaQTM=,iv:lO8VTg65n1/gslvsPojlDwarSaT2Qw0GM54lEx7p1h4=,tag:xkGRK1wRih5rkWy3HgZ3eQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
