apiVersion: v1
kind: Secret
metadata:
    name: invidious-basic-auth
    namespace: invidious
type: kubernetes.io/basic-auth
stringData:
    username: kemal
    password: fb34aa18cf7a21bd7919e61bfac9bb06
---
apiVersion: v1
kind: Secret
metadata:
    name: invidious-postgres-v18
    namespace: invidious
type: Opaque
stringData:
    s3-access-key: lpI9GiIYVnSKUDHNPHSN
    s3-secret-key: U5KMvWadvrEIXN0A9PI07kfWvH19Vv488L3zVF48
    password: f01a33b4630be988af8f5a627b747552
