---
adsb_compose_path: "/opt/adsb"
adsb_compose_config_path: "{{ adsb_compose_path }}/config"
adsb_compose_ip_binding_ultrafeeder_web: "80"
adsb_compose_ip_binding_ultrafeeder_rtlport: "30005"
adsb_compose_altitude: "changeme"
adsb_compose_latitude: "changeme"
adsb_compose_lontitude: "changeme"
adsb_compose_beasthost: "adsb-ultrafeeder-1"
adsb_compose_fr24key: "changeme"
adsb_compose_adsbhub_clientkey: "changeme"
adsb_compose_planefinder_sharecode: "changeme"
adsb_compose_opensky_username: "changeme"
adsb_compose_opensky_serial: "changeme"
adsb_compose_piaware_feeder_id: "changeme"
adsb_compose_tz: "Europe/Oslo"
