---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - backup-ssh-key.yaml
  - database-secret.yaml
  #- helm-daily-to-consume.yaml
  #- helm-offsite-sync.yaml
  #- helm-onsite-sync.yaml
  - helm-release-db-v18.yaml
  #- helm-release-exporter.yaml
  - helm-release-valkey.yaml
  - helm-release.yaml
  - namespace.yaml
  - networkpolicy.yaml
  #- probes.yaml
  - pvc.yaml
  - secret.yaml
  - volsync.yaml
