---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: synapse
  namespace: matrix
spec:
  selector:
    matchLabels:
      app: synapse
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        backup.velero.io/backup-volumes: synapse
      labels:
        app: synapse
    spec:
      containers:
        - name: synapse
          image: matrixdotorg/synapse:v1.83.0
          ports:
            - containerPort: 8008
              protocol: TCP
              name: synapse
          resources:
            requests:
              cpu: 400m
              memory: 512Mi
            limits:
              cpu: 600m
              memory: 1024Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 8008
            initialDelaySeconds: 300
            periodSeconds: 30
          volumeMounts:
            - name: synapse-config
              mountPath: /data/signing.key
              subPath: signing.key
              readOnly: true
            - name: synapse-config
              mountPath: /data/log.config
              subPath: log.config
              readOnly: true
            - name: appservice-irc
              mountPath: /data/appservice-irc.yaml
              subPath: appservice-irc.yaml
              readOnly: true
            - name: appservice-signal
              mountPath: /data/appservice-signal.yaml
              subPath: appservice-signal.yaml
              readOnly: true
            - name: appservice-telegram
              mountPath: /data/appservice-telegram.yaml
              subPath: appservice-telegram.yaml
              readOnly: true
            - name: appservice-discord
              mountPath: /data/appservice-discord.yaml
              subPath: appservice-discord.yaml
              readOnly: true
            - name: synapse-config
              mountPath: /data/homeserver.yaml
              subPath: homeserver.yaml
              readOnly: true
            - mountPath: /data
              name: synapse
      restartPolicy: Always
      volumes:
        - name: appservice-irc
          secret:
            secretName: appservice-irc
            items:
            - key: appservice-irc
              path: appservice-irc.yaml
        - name: appservice-signal
          secret:
            secretName: appservice-signal
            items:
            - key: appservice-signal
              path: appservice-signal.yaml
        - name: appservice-telegram
          secret:
            secretName: appservice-telegram
            items:
            - key: appservice-telegram
              path: appservice-telegram.yaml
        - name: appservice-discord
          secret:
            secretName: appservice-discord
            items:
            - key: appservice-discord
              path: appservice-discord.yaml
        - name: synapse-config
          secret:
            secretName: synapse-config
            items:
            - key: homeserver-yaml
              path: homeserver.yaml
            - key: log-config
              path: log.config
            - key: signing-key
              path: signing.key
        - name: synapse
          persistentVolumeClaim:
            claimName: synapse
