---
- name: Ensure path to compose-file
  ansible.builtin.file:
    path: "{{ garage_compose_path }}"
    state: directory
  become: true

- name: Ensure path to data-folder
  ansible.builtin.file:
    path: "{{ garage_compose_config_path }}"
    state: directory
  become: true

- name: Copy template-file
  ansible.builtin.template:
    src: docker-compose.yml
    dest: "{{ garage_compose_path }}/docker-compose.yml"
  become: true
  notify:
    - Restart garage
