apiVersion: v1
kind: Secret
metadata:
    name: freshrss-basic-auth
    namespace: freshrss
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:balMMyqcv9E=,iv:a4hVB5K6VyF2skj71aUlTzJp9hu8fon5viaWWkKJYA8=,tag:/NdMlzvMo9Rpld9Cqx7GIA==,type:str]
    password: ENC[AES256_GCM,data:I42ugO/TtbxmJQcWUWMvSmvjgkYrJWK4gm8gVS5Mwto=,iv:S5m8CfSH7cxFCndblVMDMCH8qMXd2ITcgjygtc0JVMM=,tag:Wjmw8W88o1w17XS289cgNw==,type:str]
sops:
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4NERkSzVOcnZkR2phZlFw
            Q0poNUVNS3lNOEcrUTVqK3Z3K1ltU0JwRmhNCldFdFNmTDcrelpwakFZSEplZ0RD
            VTZSZlF4NlhHdzQyRHdsUlhOWDg0VkEKLS0tIFhKUGR5ZytGMUNlRW9jWEpqTmJN
            WlY3dFdUT2JmcXEwYU03cXdrSjNnZG8K/yWnsie1VAXrXZ594/oDGanvJlzBSBK5
            yAjXzbnwpwWjqM2OlEcsXAF83EUMPH50NECUvp8U30+51/ESi86big==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-17T21:12:40Z"
    mac: ENC[AES256_GCM,data:hTE7u/oM2hrzEDgVzgQpMW38/qcMpi96X28baVctqaTUgEUeGkugxz/atfBb0yf/78EQcFUHgnI+YuTJwi9jchEojSXO5fp+ZU2X4dfAn6HhPAhkVV55TmICjuAHygIoZ8IrhkZTMTvrmDwkTmvolOGI6Y4WNpSKCtwPaIs9c28=,iv:zrI4MKdjI2naUYGxI+twzjowG/af9VC/d+anffyixdk=,tag:SBe0MbJIMX5Tepufzi6Jgg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: freshrss-postgres-v18
    namespace: freshrss
type: Opaque
stringData:
    s3-access-key: ENC[AES256_GCM,data:vQMvmCRnzuzo52ARvMzQvDp0j0U3kJiYa/4=,iv:wCaa7DZqtHIVs3e15TFPfd/A2f6pP/XlgjD9Djknah4=,tag:pQGdH2sC1WdrwPUFOj9XMg==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:SiQcxR60PIPpDjptBNIEQQkhnOeD9o/iB73FQZbypw+pggmwRsplxKiYeX7DAdt/N3mbLU5P51T3aQfNQwXPbg==,iv:SHTrMlkOoxmZz7AIDXwywd7CFZXCKZjzaeuLvxijk5Y=,tag:xQvqm9MF6TqRS8lLknxgWA==,type:str]
    region: ENC[AES256_GCM,data:u4jxhbZT,iv:ezvtXKB6FNiIve2p5wnATzv1+TEbtY7JoLOJOtCKo0g=,tag:C1X9sFN8St+Pahz8rdb58Q==,type:str]
    password: ENC[AES256_GCM,data:64pnFf0kUbpTmP6WWOkbaj9+HD1fENqyqrThp4DWWxfwmRPW3DlBPzANcUCPw/bB5zV29xpZYbkkm9MrGVoBQA==,iv:pnOQdEEDtw8Fp8uLa+OZVFBrWPhEidd3S3VRTu2ev78=,tag:09kNPhNdS5O3VO/U4lTLFw==,type:str]
sops:
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4NERkSzVOcnZkR2phZlFw
            Q0poNUVNS3lNOEcrUTVqK3Z3K1ltU0JwRmhNCldFdFNmTDcrelpwakFZSEplZ0RD
            VTZSZlF4NlhHdzQyRHdsUlhOWDg0VkEKLS0tIFhKUGR5ZytGMUNlRW9jWEpqTmJN
            WlY3dFdUT2JmcXEwYU03cXdrSjNnZG8K/yWnsie1VAXrXZ594/oDGanvJlzBSBK5
            yAjXzbnwpwWjqM2OlEcsXAF83EUMPH50NECUvp8U30+51/ESi86big==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-17T21:12:40Z"
    mac: ENC[AES256_GCM,data:hTE7u/oM2hrzEDgVzgQpMW38/qcMpi96X28baVctqaTUgEUeGkugxz/atfBb0yf/78EQcFUHgnI+YuTJwi9jchEojSXO5fp+ZU2X4dfAn6HhPAhkVV55TmICjuAHygIoZ8IrhkZTMTvrmDwkTmvolOGI6Y4WNpSKCtwPaIs9c28=,iv:zrI4MKdjI2naUYGxI+twzjowG/af9VC/d+anffyixdk=,tag:SBe0MbJIMX5Tepufzi6Jgg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
