apiVersion: v1
kind: Secret
metadata:
    name: freshrss-basic-auth
    namespace: freshrss
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:Ex8hfaoBCJk=,iv:SOuj4QYSt7tKTTeoMyec8TKFesFt9e3FRIhJMqxWqSY=,tag:1uuqXGsVsR0R1vNPcPs8fw==,type:str]
    password: ENC[AES256_GCM,data:3THspvTy5iexUrVXMwzX/nyTV3D1fbjoaDOVxq3DaMk=,iv:UqZxbwa1qtPJB0D5AteMo6QlDLt4vPR+04c3ibPxnSc=,tag:9f3U9oGdDSJ3n0FjbVPIPw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0cWhlaWh3ak11THpmWjh0
            RE1kd1RWYnczdE5SUk4zcjAvZUtSNzlwV3gwCkpLRlFUWFBnc1RmVklEV0xzanQy
            bWk1WWJqbkZzNnVCZ1VOUUVJVU1NOUEKLS0tIGgyaWNKaGNpRDZwcEJJTEFia1Nk
            OStJVm4wRy9hcXF6MzRtY3p2QTJGam8KaLM1wEfIc16R/fJ/awAu2Bk3tMXa6udL
            xZurXjyS+rj7x/a5d+XMltbqY0g611I0qD/tOh8ngCKM0IQK0zKWSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T00:51:55Z"
    mac: ENC[AES256_GCM,data:zUB8kl3LCVcKbKTXFYOaWJyf73RnhhHjeZicTeYFppGD5feDoA/vWvXPGRiDiHEuvVUkL4YOQsigQmEIEppNlxBTLHnrH79V302EcI712fAEIQYlq11TSh4G0t/47kLExb9Lmz+bSybV9+QBJUt7JXYl+VbVaRJJUxcH7aje70U=,iv:38wsM4ehqdofd18gwJGbi6QJcq086Vv7bb5TqOcykJc=,tag:VYLmZk6xu5RZ1vqZBx02Gw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: freshrss-postgres-v17
    namespace: freshrss
type: Opaque
stringData:
    s3-access-key: ENC[AES256_GCM,data:yw5CnyQUde9iMymt34rr0R2I51s=,iv:qceFW+m8TYSV16X9lK3Rqn52+9KzrgpbWQ1FEUv0sv4=,tag:/kHO26iOgmzxfCTNTHHR0g==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:fKtb0RCYV1hPCIKXfCVudfzzF2Rgh3fyix5eswcvukFYkswgyqPerA==,iv:ywbcmmKDJSDZ9E/12aaHJFViawGXGeEQVHoQBzE/ISM=,tag:r507giQcPMAq4x7CK5kJqw==,type:str]
    password: ENC[AES256_GCM,data:zoNfqoUYUiCR8PaAtQ47y8BWktb6BZTPETTL4Ho/6J7EbW6XsSLN9JW+JNxc8+0+SKJItv20VW0zinzK2XVprg==,iv:9UW5lDz1C2T7o92Mxp9geGo6r0/2yl8t4apPuRKfYOE=,tag:U1Jj9slrGFP+QgmWi4pSsA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0cWhlaWh3ak11THpmWjh0
            RE1kd1RWYnczdE5SUk4zcjAvZUtSNzlwV3gwCkpLRlFUWFBnc1RmVklEV0xzanQy
            bWk1WWJqbkZzNnVCZ1VOUUVJVU1NOUEKLS0tIGgyaWNKaGNpRDZwcEJJTEFia1Nk
            OStJVm4wRy9hcXF6MzRtY3p2QTJGam8KaLM1wEfIc16R/fJ/awAu2Bk3tMXa6udL
            xZurXjyS+rj7x/a5d+XMltbqY0g611I0qD/tOh8ngCKM0IQK0zKWSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T00:51:55Z"
    mac: ENC[AES256_GCM,data:zUB8kl3LCVcKbKTXFYOaWJyf73RnhhHjeZicTeYFppGD5feDoA/vWvXPGRiDiHEuvVUkL4YOQsigQmEIEppNlxBTLHnrH79V302EcI712fAEIQYlq11TSh4G0t/47kLExb9Lmz+bSybV9+QBJUt7JXYl+VbVaRJJUxcH7aje70U=,iv:38wsM4ehqdofd18gwJGbi6QJcq086Vv7bb5TqOcykJc=,tag:VYLmZk6xu5RZ1vqZBx02Gw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: freshrss-postgres-v18
    namespace: freshrss
type: Opaque
stringData:
    s3-access-key: ENC[AES256_GCM,data:KQpYwSaT5nJSXYALbuB5mtVjxX8=,iv:ZAYCUCZXdmQLEf5FT62wVJGdEQOL7tyOlZA6zZs3tAM=,tag:DavDxqiNbT6Ggwg+WAtpmg==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:hPtRkhiAljrbAY7aacRfAdoTJpfOiw0GxiUYuzrfGObU2yNl/DPiXQ==,iv:c2rPAtXJtrCqnOWuWYwcvj7gACMuvxjynlsuiz150f8=,tag:mjeEt6K1po7SgSJuvDPcMw==,type:str]
    password: ENC[AES256_GCM,data:s0WPGxAqHwwP31uW2vvA0UWGLkqs+cE7ohvys53HWkdzs4imeAyeUPJR+wq7zIKMrgp32dLbwEfIma9zpWWULA==,iv:BvOCKITg37xoKHjUbNwp6ulnF0FUr2bvdzrc9aw1E4Y=,tag:5miBs4nF5jleL3ZHqfLTzA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0cWhlaWh3ak11THpmWjh0
            RE1kd1RWYnczdE5SUk4zcjAvZUtSNzlwV3gwCkpLRlFUWFBnc1RmVklEV0xzanQy
            bWk1WWJqbkZzNnVCZ1VOUUVJVU1NOUEKLS0tIGgyaWNKaGNpRDZwcEJJTEFia1Nk
            OStJVm4wRy9hcXF6MzRtY3p2QTJGam8KaLM1wEfIc16R/fJ/awAu2Bk3tMXa6udL
            xZurXjyS+rj7x/a5d+XMltbqY0g611I0qD/tOh8ngCKM0IQK0zKWSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T00:51:55Z"
    mac: ENC[AES256_GCM,data:zUB8kl3LCVcKbKTXFYOaWJyf73RnhhHjeZicTeYFppGD5feDoA/vWvXPGRiDiHEuvVUkL4YOQsigQmEIEppNlxBTLHnrH79V302EcI712fAEIQYlq11TSh4G0t/47kLExb9Lmz+bSybV9+QBJUt7JXYl+VbVaRJJUxcH7aje70U=,iv:38wsM4ehqdofd18gwJGbi6QJcq086Vv7bb5TqOcykJc=,tag:VYLmZk6xu5RZ1vqZBx02Gw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
