apiVersion: v1
kind: Secret
metadata:
    name: freshrss-basic-auth
    namespace: freshrss
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:OIMCCy6QCpY=,iv:FOXBPWMnJSY+s7lnaL+16cCXYscMCc5FXat9ZXt2tSM=,tag:ye1crd6xkX8e7xqZK2j0oQ==,type:str]
    password: ENC[AES256_GCM,data:jbQPRkKG92/5U/JxY31xNbu7iyQD9iAmOgwJGPXhY1A=,iv:ZK2YMpbmJAJk5aWwwQdMg7OMA55WrWXnISyIGyG8wjI=,tag:phMVf1KAc7yUJR1/5P4Zhw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1MUJqTEk5NEh1UE05WGJJ
            cGIrSkpVTG9YdzVtUkxVdk51YWdtUjV0Mlh3CkJNamNJaDE4ZC9pNmJJNGFVbWxn
            Wk9ZYmNmMzB5MGtxb0NKRzFaSXpQSE0KLS0tIDgwL3pWUURZd1lOMjVrNENiRW5N
            ODRZcWdrcUh3TXcrbkNsVE5IRW9Na00KDJc7tXDH8FlcaVO8r4Dq2wUdcMpGvk5Z
            TXBW+Ixel4eDuNJdHt0Mfs9LbfvLU+FpCREug/WdxgUBNMKM5Fkw5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T01:09:04Z"
    mac: ENC[AES256_GCM,data:y17A+bWGM+hbVpNellK19kiY+KXS9YKqiWkg9IF/4PzvmAVlPpeTdWlAKN72uWDtgf7mPr+1Qd7o2fP77EuvUH7LJrIYU5F/zkUomTgI/fvPNSASZeS56uxLQPpVIsiCs/our/ikyRInHF3ropzgwP5KfJmJX9emElcyWz/5v5U=,iv:VIS8A4H2E/avwnLAx0wT3PGot4qCkBD3tJ3Q3wSFLXM=,tag:Vk0G/mCSOdAXLo6oUa49yg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: freshrss-postgres-v18
    namespace: freshrss
type: Opaque
stringData:
    s3-access-key: ENC[AES256_GCM,data:ywUCd3VieSB/yl1Jz/fdJZEdH3o=,iv:8Vn8LiUDEdNTvgmxO8oFB8Do6q/6AyP0AEJdADhv5DY=,tag:oMJbBKoesJXzRSY4aLOTWA==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:gFBsA9fn5BpYEm2A0miGkHCE9eW+e9tlajAXWtACN9MsqItvUt7+xw==,iv:n/vm76P63IPex4xQ3WVqQJuB1q9gLwB/ALs2F6ZeJuY=,tag:2JZXJ4EchMblfKvHCaa/mg==,type:str]
    password: ENC[AES256_GCM,data:83FOQzs4mhhp5ckwrtG6ve5MYZqugpvVvshmUdLASFugopVvhyqZrCzhGaIE6z01VfuQjZUNihpf04dEK7FZXA==,iv:UhVdDY/IgfuL2a+wzyZI+LGiJodKrUrLsgFuLhXZTA0=,tag:mHRD3Koy9mmNOI+uhAR65w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1MUJqTEk5NEh1UE05WGJJ
            cGIrSkpVTG9YdzVtUkxVdk51YWdtUjV0Mlh3CkJNamNJaDE4ZC9pNmJJNGFVbWxn
            Wk9ZYmNmMzB5MGtxb0NKRzFaSXpQSE0KLS0tIDgwL3pWUURZd1lOMjVrNENiRW5N
            ODRZcWdrcUh3TXcrbkNsVE5IRW9Na00KDJc7tXDH8FlcaVO8r4Dq2wUdcMpGvk5Z
            TXBW+Ixel4eDuNJdHt0Mfs9LbfvLU+FpCREug/WdxgUBNMKM5Fkw5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T01:09:04Z"
    mac: ENC[AES256_GCM,data:y17A+bWGM+hbVpNellK19kiY+KXS9YKqiWkg9IF/4PzvmAVlPpeTdWlAKN72uWDtgf7mPr+1Qd7o2fP77EuvUH7LJrIYU5F/zkUomTgI/fvPNSASZeS56uxLQPpVIsiCs/our/ikyRInHF3ropzgwP5KfJmJX9emElcyWz/5v5U=,iv:VIS8A4H2E/avwnLAx0wT3PGot4qCkBD3tJ3Q3wSFLXM=,tag:Vk0G/mCSOdAXLo6oUa49yg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
