---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-backup.yaml
  - helm-daily-imap-backup.yaml
  - helm-daily-sitebackup-from.yaml
  - helm-onsite-sync.yaml
  - mbsync.yaml
  - namespace.yaml
  - pvc.yaml
  - sshkey.yaml
  - volsync.yaml