---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sshd
  namespace: media
  labels:
    app: sshd
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: sshd
  template:
    metadata:
      labels:
        app: sshd
    spec:
      containers:
        - image: lscr.io/linuxserver/openssh-server:8.6_p1-r3-ls71
          name: sshd
          livenessProbe:
            tcpSocket:
              port: 2222
            initialDelaySeconds: 120
            periodSeconds: 30
          ports:
            - containerPort: 2222
              protocol: TCP
              name: sshd
          env:
            - name: PUBLIC_KEY
              value: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDK16+6/jzCvp3Sthg0S0JY2syS3ypa8kxkLr34mJghisvIr4o3G3o0PAaB9rZHd/M2cmZYP7/bkXt/QpWWjaOlztQvYd3oZ9sAl5Omt0kKcmzdsiz5om+0sBfpHVBgkC+nBFgF3+/e2hMh8Z7xqPfbFhpZjBDozh2HflN09xwt5K1fREflxLZfQl9VYLbwRhRtlpmPOXmMWO+6jF90tggvLs926zIV1oe+cQbxrdhPyq09fCAvZKPOfurrJBjB+EZ2IJIwhL/GpkANOBp3TmoES/FVkvzkYrdHq9DVqq4rm1L5FK85ssQK6Fk0VVh7fWknIoMzLRnPRFoMBcb+7dU2TrwY0IIaepulrWtGSSmSjzQXkEP9KnCoFtHxSj5qSgYX1PjSiXoVAEULhQdCQzp2DEwDbiwDKbaZ1VBCwH4TDII9zWYJ355CguD03hWrdrpSXbWE3JFHZtT/ZYK2J23yZEiWY6wMW5YvGSY6kRZzpg6bnCmxi1PlRuLmlWDR/dUTSp+WMmAv/wnbHyLJD5WGJnmSXlI+xYsdbl+VjUpOylBEOR+wWKNww9UTS6U+aYZJ8bh5tDSvgxrg6qJoij/UlG3yQUX3hRi/iWctETJ3PSTRyFY5QNZjhnaglR+NKDn0vvZ6GF759wQ9gkOoYEuXmHFHKaymvowE+qIGXhgSnw=="
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: SUDO_ACCESS
              value: "true"
            - name: TZ
              value: "${TIMEZONE}"
            - name: USER_NAME
              value: "user"
          resources:
            requests:
              cpu: 100m
              memory: 10Mi
            limits:
              cpu: 200m
              memory: 50Mi
          volumeMounts:
            - mountPath: /data
              name: media
            - mountPath: /config/ssh_host_keys
              name: sshkeys
      restartPolicy: Always
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: media
        - name: sshkeys
          persistentVolumeClaim:
            claimName: sshkeys
