apiVersion: v1
kind: Secret
metadata:
    name: seerr-basic-auth
    namespace: media
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:rN84ycQ=,iv:g8t+1ij0rRm1Nyia/s7XvC4hsgat2SoyrePWv1pQ3rk=,tag:SmIkZ7rnvfjX5Lmw1wtKbw==,type:str]
    password: ENC[AES256_GCM,data:htI4HTGzZmCMa9oQOVUfKmXty/VMwPWiNX6zqeDqMeMMcnstdq7PT9o5PZsxojruBI4HhNs7MWsqeD0hsifbvA==,iv:Gpdw7pFSNe+uRB73+vjIkFJr1kM4NbVE8oOa2j4ocCc=,tag:anjmJgeR0xh5JwQii8IpZg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaUHFXZ0lJTkdzNkdrNnBq
            Uzd0U0wwWFFoTTdmUXUxTllHYk9DUzZqbnc4CktOSmx4U0RQU2FweWdvSFZHOFNx
            L1R4Q0plTVh1YWJCQ05SS3pEYTdGa3cKLS0tIE1JeGFVMncrdWVMNVdCVysvVVgz
            ZXp1RS81b3ZhRG9qRG1UL0dsUktZUUkKOm3sodKiIa4Ac5MF3TKwnyizs87Q7hkI
            FEJIgEWPItt2nJE9UNPUbz65uG4Vs1idpcXliW1oVB2PktEyWBzVtA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-17T19:07:20Z"
    mac: ENC[AES256_GCM,data:EQdhdSeWTGFVPn3roTh0m3kvikyx/f5e/z1x7R1AZliqb6kPenCSax5YqeMkKW4fE/uTZ2J5euuU3fFjBDl6OV6VwtjXTfuGe4+BBPSDrPKYZYOQKAHG9/UPaUslXIn9loBUAYtoKOawF1Pq27nGkSqAp7xbCvLGFVxjkApoiUU=,iv:g+iko/cOSEwijSK+Da0AXZu5pFYViS8ZHA0RQOKriqA=,tag:u7qFsbTaJ2UD095W8NDhhg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: seerr-postgres-v18
    namespace: media
type: Opaque
stringData:
    s3-access-key: ENC[AES256_GCM,data:axAXsC7iCuJ4qWYpZmaOKAOuyNDkbIheMN4=,iv:eecUJ5exOlA30PUYLosjHurOrd3fw+4BhqoQzQv4I+g=,tag:0jhRhzuI8pBDphnx7G9Z4w==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:EpaZadrteiF7XrHR+nrU3iMNK60u/qLNmYnRwZVvDXSfLHl/Ts9vBCV7fH2lCEoK+jcluS7JBaneVF5TYN1soA==,iv:MdWQmNzwFuzsIYCHjCcD3uvUeMti8Op4uarGd1mVSrY=,tag:fSl/P3X2KUBuW1PmAfua/w==,type:str]
    password: ENC[AES256_GCM,data:T5faxJzfsfZTXQGZAcdBHn2ZsO4FdVfMbmEhCBZ28y1+QnzJJMsNtA3+7HFIZrrcMCeHFvZrKCU+xKYpTFYCdQ==,iv:LSnqki7i83803ROxWFiBPffipcoEoK+7wHl46VoJGYg=,tag:MF/FlvjyHjC2q5SNy/tvBQ==,type:str]
    region: ENC[AES256_GCM,data:4T4rTQCl,iv:wl/k79dV4hFRvIhLD92Yqowzmpr6CO2NyDM7d3YibFU=,tag:tXPGHIeQfbTAGo81acBnxg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaUHFXZ0lJTkdzNkdrNnBq
            Uzd0U0wwWFFoTTdmUXUxTllHYk9DUzZqbnc4CktOSmx4U0RQU2FweWdvSFZHOFNx
            L1R4Q0plTVh1YWJCQ05SS3pEYTdGa3cKLS0tIE1JeGFVMncrdWVMNVdCVysvVVgz
            ZXp1RS81b3ZhRG9qRG1UL0dsUktZUUkKOm3sodKiIa4Ac5MF3TKwnyizs87Q7hkI
            FEJIgEWPItt2nJE9UNPUbz65uG4Vs1idpcXliW1oVB2PktEyWBzVtA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-17T19:07:20Z"
    mac: ENC[AES256_GCM,data:EQdhdSeWTGFVPn3roTh0m3kvikyx/f5e/z1x7R1AZliqb6kPenCSax5YqeMkKW4fE/uTZ2J5euuU3fFjBDl6OV6VwtjXTfuGe4+BBPSDrPKYZYOQKAHG9/UPaUslXIn9loBUAYtoKOawF1Pq27nGkSqAp7xbCvLGFVxjkApoiUU=,iv:g+iko/cOSEwijSK+Da0AXZu5pFYViS8ZHA0RQOKriqA=,tag:u7qFsbTaJ2UD095W8NDhhg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
