---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../adguard
  - ../archivebox
  - ../authentik
  - ../awx
  - ../blackbox-exporter
  - ../changedetection
  - ../cloudnative-pg
  - ../comics
  - ../cyberchef
  - ../dawarich
  - ../descheduler
  - ../endurain
  - ../cloudflareddns
  - ../epicgames-freegames
  - ../firefox
  - ../forgejo
  - ../freshrss
  - ../gotify
  - ../icloudpd
  - ../intel-device-plugin
  - ../invidious
  - ../it-tools
  - ../joplin
  - ../jupyterhub
  - ../karakeep
  - ../kuma
  - ../kyverno
  - ../librespeed
  - ../mailbackup
  - ../mailrelay
  - ../mailrise
  - ../mealie
  - ../media
  - ../meshtastic
  - ../minecraft
  - ../nextcloud
  - ../node-feature-discovery
  - ../node-problem-detector
  - ../ollama
  - ../openclaw
  - ../openwebui
  - ../owntracks
  - ../paperless-ngx
  - ../papra
  - ../reloader
  - ../remotebackup
  - ../romm
  - ../rssbridge
  - ../searxng
  - ../speedtest-exporter
  - ../spegel
  - ../superset
  - ../syncthing
  - ../system-upgrade-controller
  - ../unifi
  - ../volsync
  - ../wallos
  - ../warrior
