---
apt_packages:
  - btop
  - ca-certificates
  - git
  - hx
  - lsof
  - ncurses-term
  - nmap
  - python3-debian
  - silversearcher-ag
  - systemd-timesyncd
  - terminfo
  - tmux
  - unzip
  - vim
