---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bedrock
  - bedrock-creative
  - bedrock-survival
  - creative
  - mc-router
  - oldworld
  - survival
  - backup-ssh-key.yaml
  - helm-borgmatic.yaml
  - namespace.yaml
  - networkpolicy.yaml
  - secret.yaml
