---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: rclone-config
  namespace: minecraft
stringData:
  rclone.conf: |-
    [minecraft-garage]
    type = s3
    provider = Other
    env_auth = false
    access_key_id = ${SECRET_S3_MINECRAFT_ACCESS_KEYS}
    secret_access_key = ${SECRET_S3_MINECRAFT_SECRET_KEYS}
    region = garage
    endpoint = ${SECRET_S3_MINECRAFT_URL}
    force_path_style = true
    acl = private
    bucket_acl = private