apiVersion: v1
kind: Secret
metadata:
    name: epicgames-free-login
    namespace: flux-system
type: Opaque
stringData:
    EMAIL: ENC[AES256_GCM,data:IidA2CL2eshI53ANiNiQ8pjEKw==,iv:/WT01recRT2lBBwYmEPpmpH5p2nsaVOpcB7uWR3evlw=,tag:haqgYIjYY067V7+PlNWXnQ==,type:str]
    PASSWORD: ENC[AES256_GCM,data:FJnYmiap57h5MjjqVM+SgqNro5Ntk+9akvu1bQOHjjI+budnVqhFk3S1MkVSyp/K5/+GCIgOWFLb5THSMUj9pTf7zqi0GF7hqIUIC6EzCdSEKljDX9w+ToDrXZrB4VAWsFXmHSLHpV5IOmBdoD4MyLmddaXdzWALRxbTdH9hXII=,iv:jodVfIyc3AWGQu6HFKIie6I35n8dcfgU1IqLdgQGz9E=,tag:k/NAI1wAil4FJybkvU+HVA==,type:str]
    TOTP: ENC[AES256_GCM,data:cSGgzyF4V9zvtB2hX89JJVfhYih5s8VDR4vgCq8ehqT7YWt2eWq/iz55puqr2vQDtiH7/A==,iv:CwjdQ6I4/bPXzLyudiSp7gZHcgl3wGqMdjIn0J6QVWU=,tag:LKOAxTwZ30dENxQbcPBy2A==,type:str]
    GOTIFY_TOKEN: ENC[AES256_GCM,data:cZ3VdTvf1VnxRd99eCaB,iv:JBiF0AD5VKcQ9REFYzVY7mNkkEX0gAj6OKVtA5siUhM=,tag:HegKm6NWU1Q8gm2z072krg==,type:str]
sops:
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCT0NkVzBnOTdQQ0pET2xv
            em1RWVNzZFRjUUhROGV0aWR1WWpEeFNjaWdFCnRVam1UeHVIZHFmNjFwR2EyNWdR
            NysyVEZ0UmJjdFcvVm53MWtSYVhmd0EKLS0tIGxoWml5Qlk3dTliSktQak5oSXpW
            cmNuaHZpeGVZVVNaZkwzV2oyRlNtUHcKVRYVOuaIV9OhOBG3ku7uqUgvFl3D9geU
            LuBaelkdn0K465Hh9IfaIWbCPjgQt4EYtPJ/f4E7IcaKQcd8YyhQSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-15T18:24:33Z"
    mac: ENC[AES256_GCM,data:d/4hQ3rRvQsgA2ck2rv8qtVXc1y29rQp03xnd6/MaNh2i0dlvI4yaMRIywI2GFRH9gCx5EP9y+MFnJ7DPnCo/9GG17ruZnQXvQnXmiSjP3MltWvOP91x938+uwxNwkxgbrpS6ko0xGw5Vc0o0//1PXrZNFhBpSUmTHsFu24/GyY=,iv:K+wzpYoXZOnmuk/DCjTrawa0gfDjGhjHiziTsPtV3eI=,tag:cQI28qOv50zA2q7Nbha9EA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
