apiVersion: v1
kind: Secret
metadata:
    name: prowlarr-basic-auth
    namespace: media
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:T7yoeyF1XtA=,iv:T/Gk2m+z6i2p1JDS7CFo5GAXT9p57T54Re6QLbVNsJs=,tag:pKl3XX18YLToIVEpZYrmiQ==,type:str]
    password: ENC[AES256_GCM,data:AoxGdPNTd693cBanXNr81s9dHaxfxkE3qvjUfjS2rDLtIiBo06kAUtGK7J1kydZGiabnjGPRVBBcDi+cFU4sDg==,iv:QOR3TJHaH+4qPlPy4HcuQqKCnE7x9c1TBspk5qB3HuA=,tag:5lI8E3F1qW9G5FHuxlB89Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGNnNGVWhBb0pZc2ZVeHlv
            SGd3OEtTZnRHOGg1ZkdTQmtCNERnL21RS0dnCnZWNFdWZXhpK0Izd01hWkVGalJG
            Skw2WTRBVnZlT1lqdFBCNW1vV0xnbkkKLS0tIGthanVLVHkxRWZ4ZTBVRXZuWFhO
            cXZGVUtCalJheC83djF4dzEyak00WUUKsRfZI3JgUa8pA8vXMZWFhV1I9XplDHbm
            OjvdSU3apWnJ1DvrwLAGwM3yVV1DjNCNrEGlaEEWIaEQ9bZKrrqlmA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T12:49:57Z"
    mac: ENC[AES256_GCM,data:L/dEKPnbCLhJVsVLuP854t6H+mihYb407a5a9nBDJGOJ55Z8pgsd+lwn/4c45vwZVBV2MMGfMuQy5y/hiP8Jet6IIfw1eOhh5AZuonGfeS1KFmic4WWYyDSSM7LElrlPA8Gyj1RJSSWuoN3UMagGZcf76yfix0qG3Ps5/6rOpi4=,iv:iMY2Yf5zdcF+cEVtJ/pjMmoQLAvM40oPlY8KEx9Y8Yg=,tag:CSE3e+BuEiP004vFmx7YZw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: prowlarr-postgres-v18
    namespace: media
type: Opaque
stringData:
    s3-access-key: ENC[AES256_GCM,data:cSazFQ7gsPrpQsDlFiqKQll1X24=,iv:7vnaCPc7VSwuzdlQzkgAh3C1bDqzJeXzKNDJbjYRca8=,tag:AiLAupyuHbAX/QK7boJneg==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:bs3bG/WDQetEVqcHVASfJxWHlaQdpF1/movswnBgfsoFxqPClfB8YA==,iv:RGkv9EvOUbH0Vouv711tJf+5q/brYQWwUjB6Mz9fq80=,tag:ObPqyMYq9F6IBLnhedANjw==,type:str]
    password: ENC[AES256_GCM,data:EU91zs8DOMigrfibyfBQEmPGpBZftCZWiozsQ7TEF81uznzgXXsbckDNSB7It3Z0J8bVRKSUJ4uXUop4MkjnRA==,iv:PU8BRrSMz3EJmTBsHNa0Z8SA0xxipG98iYUaDb07G3E=,tag:JcEHQB/9haf3eNZyph5HbQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGNnNGVWhBb0pZc2ZVeHlv
            SGd3OEtTZnRHOGg1ZkdTQmtCNERnL21RS0dnCnZWNFdWZXhpK0Izd01hWkVGalJG
            Skw2WTRBVnZlT1lqdFBCNW1vV0xnbkkKLS0tIGthanVLVHkxRWZ4ZTBVRXZuWFhO
            cXZGVUtCalJheC83djF4dzEyak00WUUKsRfZI3JgUa8pA8vXMZWFhV1I9XplDHbm
            OjvdSU3apWnJ1DvrwLAGwM3yVV1DjNCNrEGlaEEWIaEQ9bZKrrqlmA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T12:49:57Z"
    mac: ENC[AES256_GCM,data:L/dEKPnbCLhJVsVLuP854t6H+mihYb407a5a9nBDJGOJ55Z8pgsd+lwn/4c45vwZVBV2MMGfMuQy5y/hiP8Jet6IIfw1eOhh5AZuonGfeS1KFmic4WWYyDSSM7LElrlPA8Gyj1RJSSWuoN3UMagGZcf76yfix0qG3Ps5/6rOpi4=,iv:iMY2Yf5zdcF+cEVtJ/pjMmoQLAvM40oPlY8KEx9Y8Yg=,tag:CSE3e+BuEiP004vFmx7YZw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
