apiVersion: v1
kind: Secret
metadata:
    name: prowlarr-basic-auth
    namespace: media
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:LJd7OdZmypo=,iv:NgMo22i0x5tIYGSbn0OJj7XV5XbIfC2GjSyFiPq3ay0=,tag:m7JVjJOKqSNd9/300VwlIA==,type:str]
    password: ENC[AES256_GCM,data:8btKia4PlVi6YVNn3Q43X/eQG1D4DmO8hyAwZtnen1s6eOoSKPMKwMS0OkhiFTPKu61C/QqIOpl5HM0ZFQ6WMw==,iv:Zctpw2+62SM5wAGDCJ4tYngk0jkJL+ZTgxS37mV2L7E=,tag:o65ztN+C22jfayp1/Ycphw==,type:str]
sops:
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIUEZXUDRVRkM1Yy9BdEVo
            N0gyS3dGSVFEU0JBZTBsb0hGRTdEZi9DWFJRCndSNTFGZmhhT05NWDdkODcrdUZs
            VzczbHhZSUxhUkNrRlFPWjErSjZaTkEKLS0tIFVmY2UvZUd5ditPMWR0TE9SYmFW
            aEV0Z0dYcHBBeUc0enBhK0NScnd2NjAKihO71G9wQOC2wI9Kzk4iA34GiWeBKtJK
            4zsuMmvCRbpMBPAoOG/ai9XAn2TG+NwTbi1BvybdACEQ8w5TjspmPA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-17T21:13:14Z"
    mac: ENC[AES256_GCM,data:LrCF0m2+fK4+t/Bdzzg+dZnJPPtqcQARYiDM+uoHljK45RBY4CgZQ/l0Le1pKFOQmPwxuDhgc8Ohx5NnGBQhbdhNHx7oM9xLlT8FjM3E8zo18hFXGyoJw8B9Q1KTOANuGXgK9hhx+W/DPKdoi6+NhmcZW0KJc52gJbrJzZm1RK0=,iv:8yizB8rrEzMCsh6WKlQY/t94AW3vU+zLzhyvW0z72Go=,tag:65y7LgaHC0XdLQiT/hrWZw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: prowlarr-postgres-v18
    namespace: media
type: Opaque
stringData:
    s3-access-key: ENC[AES256_GCM,data:3QamclyeginJodSVFtJqmJiozYqudKUvTa0=,iv:JAOaqwnwDLiTL8nXjO30ijox7w7Vdiips1k2PZaYAJw=,tag:Ad5gwavbJxDKhg/VDEbdHw==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:Z55HUumQTM2f/5uPJtbDGUewyPsUygaO0YH8QFXfsVEWpBrtadt9BU/mjqXeP3FppVIbghloOLCvUp7Tu5TDbA==,iv:rwMr7T80UAkN9g8pnzJeSwywqW7Of+sVYLUvxEAWWz4=,tag:8X6CV3IVW85JNwA4sNxYaw==,type:str]
    region: ENC[AES256_GCM,data:ZMxzBwpX,iv:FyZJxeSYHuBseBAXGOwHdxyjR5nxhYaxngmJM2f+j50=,tag:YgUlUura8sd3Ci/tBKVUYg==,type:str]
    password: ENC[AES256_GCM,data:Z3IO7kbe2iHeiozftsLCwL/Hq+1ZtAKslz0ovMLLiCfZZ1JHAQuacJCZIoG3s82MOqqrs3VsZJ/u8lBr+KIudA==,iv:dpN/y7oRA9fz+aIb8+gc7kfdydq/XrmrVqDPjD0Z6Xs=,tag:b00+EdTzovVdRN/jlCVw5A==,type:str]
sops:
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIUEZXUDRVRkM1Yy9BdEVo
            N0gyS3dGSVFEU0JBZTBsb0hGRTdEZi9DWFJRCndSNTFGZmhhT05NWDdkODcrdUZs
            VzczbHhZSUxhUkNrRlFPWjErSjZaTkEKLS0tIFVmY2UvZUd5ditPMWR0TE9SYmFW
            aEV0Z0dYcHBBeUc0enBhK0NScnd2NjAKihO71G9wQOC2wI9Kzk4iA34GiWeBKtJK
            4zsuMmvCRbpMBPAoOG/ai9XAn2TG+NwTbi1BvybdACEQ8w5TjspmPA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-17T21:13:14Z"
    mac: ENC[AES256_GCM,data:LrCF0m2+fK4+t/Bdzzg+dZnJPPtqcQARYiDM+uoHljK45RBY4CgZQ/l0Le1pKFOQmPwxuDhgc8Ohx5NnGBQhbdhNHx7oM9xLlT8FjM3E8zo18hFXGyoJw8B9Q1KTOANuGXgK9hhx+W/DPKdoi6+NhmcZW0KJc52gJbrJzZm1RK0=,iv:8yizB8rrEzMCsh6WKlQY/t94AW3vU+zLzhyvW0z72Go=,tag:65y7LgaHC0XdLQiT/hrWZw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
