apiVersion: v1
kind: Secret
metadata:
    name: openwebui-basic-auth
    namespace: openwebui
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:FPDcRVLq6ie1,iv:FU0oS/dMKuxxutEBdFeMRFKKQ6CsC7MsbVgcWOo6QKM=,tag:O0wqKT7NQL55LCrOy0H2hw==,type:str]
    password: ENC[AES256_GCM,data:w2KPUfmPICli9hJNJFW0wC1ce42BsF3W8QHkCsD8mTI=,iv:koYj8p0QHbIMpomfzfO6CPDw4F/3t7vhtIfQwCOHc7Y=,tag:b952AoIOcITDmlCNUe3lSQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTY2xKWWNZdUllbGhTa1Z0
            TkJ0Zy96OERsL08rZXBXNUFkVjZqaVZrZzJFCmpKZjhBdjlRSk0rckZISCtLSUFm
            ZURCdGt6R3JlS3NjdVArMkVtQUdQWjgKLS0tIDVqQkxmckptb0YyTElGNU9Lc2xG
            OTd2Nnova2xYOUE5Vnc0RytIS1R5L2sKGiqxxeLP/aL4FkDEcRpf60eUXHg8DajQ
            vzht7koheZyVWwlG8Jie+sTb5O/FlN0D2QAvD7X387Ib08Ex/eUa5w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T22:38:03Z"
    mac: ENC[AES256_GCM,data:i+gNIqsmlUYiwlgqrDTsoFD0HrNX7Wdt4FzKUV52gZS1TKDngQrqVt4oAcqFauu8wXB/xHt0ydOEQHlAcikXzZNfrbeF+jKrSMnAwqe5EyY5gnKP8nndPdxfvwWf/ARmNPh2yFYcW1dFqTmpn/uO8NI5AgIpKFQGFEtGIH/XGJw=,iv:59m3QQ4E/PFOA18gpvfSNueoP6cbUNLKv9frXArezEU=,tag:tCrNwd1nB4ggVBRLWmpbpg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: openwebui-postgres-v17
    namespace: openwebui
type: Opaque
stringData:
    s3-access-key: ENC[AES256_GCM,data:8LvJBlS6CxgG4ENCjnJM3GqaCjc=,iv:WH5LqGHBch5MQPbdg2sRkqmZVFT2eXTnEUZtsulIy98=,tag:RGn6B5pCVLa9moo2JG93fw==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:3vijJuSSzScim9eWgruL7cPj4Qof59djdyHk/jyKIexp6bJyUuhL4w==,iv:3o/brtTQ9hpIG7O0Y9qIK01fv+FjEE0h0Vg4q64eDXI=,tag:NrIY4VOjuT1VadaiaSWM8g==,type:str]
    password: ENC[AES256_GCM,data:HJGYJnhqgPxJPegqzK7MdiB5M8CGiL7i3PyjE++5LLU=,iv:dcaE7rLR5YbrxD1vUD+JYBDFrgNcgKTfn97tS/vW9tE=,tag:mVsXpDU9VylaWUElm90GSg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTY2xKWWNZdUllbGhTa1Z0
            TkJ0Zy96OERsL08rZXBXNUFkVjZqaVZrZzJFCmpKZjhBdjlRSk0rckZISCtLSUFm
            ZURCdGt6R3JlS3NjdVArMkVtQUdQWjgKLS0tIDVqQkxmckptb0YyTElGNU9Lc2xG
            OTd2Nnova2xYOUE5Vnc0RytIS1R5L2sKGiqxxeLP/aL4FkDEcRpf60eUXHg8DajQ
            vzht7koheZyVWwlG8Jie+sTb5O/FlN0D2QAvD7X387Ib08Ex/eUa5w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T22:38:03Z"
    mac: ENC[AES256_GCM,data:i+gNIqsmlUYiwlgqrDTsoFD0HrNX7Wdt4FzKUV52gZS1TKDngQrqVt4oAcqFauu8wXB/xHt0ydOEQHlAcikXzZNfrbeF+jKrSMnAwqe5EyY5gnKP8nndPdxfvwWf/ARmNPh2yFYcW1dFqTmpn/uO8NI5AgIpKFQGFEtGIH/XGJw=,iv:59m3QQ4E/PFOA18gpvfSNueoP6cbUNLKv9frXArezEU=,tag:tCrNwd1nB4ggVBRLWmpbpg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: openwebui-postgres-v18
    namespace: openwebui
type: Opaque
stringData:
    s3-access-key: ENC[AES256_GCM,data:l4niwgUWsuxXbhRV24/Dek53lJ8=,iv:uampwSoXoEKBKjiUsQEu/OLMxm/MqS/pqK3Yjq1MLUo=,tag:g49GdKsT38XG1+LmcRBArw==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:2q6hoifqaGpZxGIYtvDUdl6qORDPUqg5PyCpWnwm+0tvvfCVn/riLg==,iv:lAvUsj0vnyeeMmdUEBav/zO3Pkn+uLWQgs5yKo79ZF0=,tag:m7kaI9Z6QkGRhttEFXrRaQ==,type:str]
    password: ENC[AES256_GCM,data:caOxeU8SxlkeSADkOGqvwsUMbdzhJllo9IPzG3OUAkc=,iv:0NPo9N00NRpO+hPu6LMBRCmD36zVmiXCbhPwWq4G1Cs=,tag:c6bDtIbvbbg3ZM+mPi+WEA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTY2xKWWNZdUllbGhTa1Z0
            TkJ0Zy96OERsL08rZXBXNUFkVjZqaVZrZzJFCmpKZjhBdjlRSk0rckZISCtLSUFm
            ZURCdGt6R3JlS3NjdVArMkVtQUdQWjgKLS0tIDVqQkxmckptb0YyTElGNU9Lc2xG
            OTd2Nnova2xYOUE5Vnc0RytIS1R5L2sKGiqxxeLP/aL4FkDEcRpf60eUXHg8DajQ
            vzht7koheZyVWwlG8Jie+sTb5O/FlN0D2QAvD7X387Ib08Ex/eUa5w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T22:38:03Z"
    mac: ENC[AES256_GCM,data:i+gNIqsmlUYiwlgqrDTsoFD0HrNX7Wdt4FzKUV52gZS1TKDngQrqVt4oAcqFauu8wXB/xHt0ydOEQHlAcikXzZNfrbeF+jKrSMnAwqe5EyY5gnKP8nndPdxfvwWf/ARmNPh2yFYcW1dFqTmpn/uO8NI5AgIpKFQGFEtGIH/XGJw=,iv:59m3QQ4E/PFOA18gpvfSNueoP6cbUNLKv9frXArezEU=,tag:tCrNwd1nB4ggVBRLWmpbpg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
