apiVersion: v1
kind: Secret
metadata:
    name: openwebui-basic-auth
    namespace: openwebui
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:E6MEsvaKRkjR,iv:Qudx9nVqCHF0GQT8XgJ0k16CqtYATwmvkTwtwhlMp6k=,tag:lc/3fA8FOzscq9OHOmi3uA==,type:str]
    password: ENC[AES256_GCM,data:SkhsouOggpMaSK8mrfLnucTT380ulV60nt9uwwqoIKg=,iv:AmkJDRsRLr7/BrWT1CTam3h8MtB5WMtVOBvGowM7sEI=,tag:l7FqL8HCnY9AqaQouCIBvA==,type:str]
sops:
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVcDB5N0Ztczd0dFJGaFJO
            dUMrUzQwTTN1UEdSQVA5c3pIMHdIdHQvV1ZZCjh5NG9NYmdiWXFOd1U3WDlrQTdr
            cDl5QzljaGpiRm9JcWljaEdPUHk2SEkKLS0tIGcyUzhCckZxVDNuMTRwTDNGTHF0
            NFJnTjZ2SEE3ZDdHUE9HNXd5clRMMnMK/PynjxsQM2+zOwe48BP9vXDSiSKu7blc
            LzFzbes/4+8yzWLFr30R1HFI7cNdH/iDf4X1coArZ7W7XRWeuZ9Szg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-17T21:12:47Z"
    mac: ENC[AES256_GCM,data:wJTYFeuLZabt5g9QReiZpt25T0/num9gnp0DwD3u7OyUYarztgHYMO2ln4NwUT7RGSbMfTqk71EZYiXqAtwvm39/EOgYn3JplWLDnghfIjEmqULPqEbENJXe+QJCRzHexu58MYKO+9uN0rWK8WCHfkef6QFL/uxCY8GOtfDgnvc=,iv:WS/YR/3jAlzaRxQZ392vyUjOyBxL2uAI9mmMQtTz9sQ=,tag:vAtku65WTEKxMTqNaiBnqw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: openwebui-postgres-v18
    namespace: openwebui
type: Opaque
stringData:
    s3-access-key: ENC[AES256_GCM,data:FILgm4/5Nt71LlnAXK9Yh8t+K8CEwDg8O0E=,iv:n+Lhm9FbEW8pao28Z6cydJ7B8W4pYMeue5mcWsQ1uKc=,tag:2juhhrWfvAI/VTXleTTGrA==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:12wZd2eb1dZOFohc5KCrVlgo8LRHcr3SxwTdqShwwuD41DrbZ5l7JpeAv2N2kV9O7Ud1RoCiX7YePy/0j9ZFNw==,iv:CaE+tssqbPMo2jVi7wqj1GiaxLEyTAHH3AHeOEKxsPo=,tag:utOWVPSC64JV/Sl0cvyE8w==,type:str]
    region: ENC[AES256_GCM,data:awH6Akuy,iv:EHHR5BkeD5flmAmyVLyEdbBG9iQsyEYAI3OdLZj5Swc=,tag:aULu4eolpoM3VL6vwqUKZQ==,type:str]
    password: ENC[AES256_GCM,data:4syM4nKSqGTOknXjml/NCo7ttt3WlVui7SGwajCpIbY=,iv:KL2tYPwKhYELo40zRhTn3X+Th19Ra9W19yquc+mcZFk=,tag:qQJ4uAk9m/+7qUgk52t+ug==,type:str]
sops:
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVcDB5N0Ztczd0dFJGaFJO
            dUMrUzQwTTN1UEdSQVA5c3pIMHdIdHQvV1ZZCjh5NG9NYmdiWXFOd1U3WDlrQTdr
            cDl5QzljaGpiRm9JcWljaEdPUHk2SEkKLS0tIGcyUzhCckZxVDNuMTRwTDNGTHF0
            NFJnTjZ2SEE3ZDdHUE9HNXd5clRMMnMK/PynjxsQM2+zOwe48BP9vXDSiSKu7blc
            LzFzbes/4+8yzWLFr30R1HFI7cNdH/iDf4X1coArZ7W7XRWeuZ9Szg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-17T21:12:47Z"
    mac: ENC[AES256_GCM,data:wJTYFeuLZabt5g9QReiZpt25T0/num9gnp0DwD3u7OyUYarztgHYMO2ln4NwUT7RGSbMfTqk71EZYiXqAtwvm39/EOgYn3JplWLDnghfIjEmqULPqEbENJXe+QJCRzHexu58MYKO+9uN0rWK8WCHfkef6QFL/uxCY8GOtfDgnvc=,iv:WS/YR/3jAlzaRxQZ392vyUjOyBxL2uAI9mmMQtTz9sQ=,tag:vAtku65WTEKxMTqNaiBnqw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
