apiVersion: v1
kind: Secret
metadata:
    name: openwebui-secrets
    namespace: flux-system
stringData:
    WEBUI_SECRET_KEY: ENC[AES256_GCM,data:y7TTLUQOqWsLkJJCFk/QZ1jph+p/IzFVBgFe4yHngl0=,iv:W1ke3v8maCm70aHSATf+ScyhtgWsGgeS0paYB9crpf8=,tag:RtPO7W7fU1+avTSYgen4cg==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:FY3VKOT1SnBvFg63FoNevSyezHUVRlCVV+FWO6PH1A3e9ED2i1v/uNgsjDGZKvF7n6x557huXmNQ+hcXgF8UzXQDs2rJvvsgBlmCR+MjMVMzrvn9WaKYjWiZpvNrCQ==,iv:KnaY9vEuefUKbzTisSxEHq+8iUVc42mDUxilYSqw9PE=,tag:c2eOcgD8W62UA1WnG/srlA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzNTFzdmVyM3k3R1hvNkFn
            bEkwM0F6MC9mUWxpWFBidTZwR05ybzd3UEZjCkZ3bkxpOUM4SVd0QXUwNHVrTWYv
            MWZWVG91bjl4TTlOYVRSWnRxM2RWWlEKLS0tIGhxeEZ0aHZud3J4aGIwYXNELzJn
            RGtIelRlYldINFNBcXVBbGhscktlOTgK21ADpaWfkxein4vARvnqOyC6OuJ6Vz3B
            EpZo7z826da4+KABdIGM7/hW6JAoNweOvjZ0iR66JDBWUHkMq71UuQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T22:47:14Z"
    mac: ENC[AES256_GCM,data:sfZYSSuOQOovaJ0iUN35wmo0OIdRPEbbyX2sVLy+9sAIVhhsLXJDf2QwjZTNBSY+R8tZRBLGq+4+p1ecmXjFv+2ARbXdH+R7cGOqm5ayb0N4Ic9e64hjfRERl4NJRy3vF/+t2W2kATriAxYEdFQVEC6/eWGslIht8KzcQwbNBZ0=,iv:xE+ktAQqKsTUZHjTlE7nEYPB9tjGf8hOfHwH337H+Jc=,tag:9pIiCkrhEyAbInDDEotDpg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
