---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: probe
  namespace: adguard
spec:
  interval: 30m
  chart:
    spec:
      chart: raw
      version: v0.3.2
      sourceRef:
        kind: HelmRepository
        name: dysnix-charts
        namespace: flux-system
      interval: 30m
  targetNamespace: adguard
  driftDetection:
    mode: enabled
  install:
    createNamespace: true
    remediation:
      retries: 10
  upgrade:
    remediation:
      retries: 10
  dependsOn:
    - name: kube-prometheus-stack-crds
      namespace: flux-system
    - name: blackbox-exporter
      namespace: flux-system
  values:
    resources:
      - apiVersion: monitoring.coreos.com/v1
        kind: Probe
        metadata:
          name: urlmonitoring
          namespace: adguard
        spec:
          module: http_2xx
          prober:
            url: "${BLACKBOX_EXPORTER_URL}"
          targets:
            staticConfig:
              static:
                - "https://adguard.${SECRET_DEFAULT_DOMAIN}"
      - apiVersion: monitoring.coreos.com/v1
        kind: Probe
        metadata:
          name: dnsmonitoring
          namespace: adguard
        spec:
          module: dns
          prober:
            url: "${BLACKBOX_EXPORTER_URL}"
          targets:
            staticConfig:
              static:
                - "adguard.${SECRET_DEFAULT_DOMAIN}"
