apiVersion: v1
kind: Secret
metadata:
    name: radarr-basic-auth
    namespace: media
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:UKrkBEUk,iv:1flud7fm5ShYziS1Jo01fKAOBjos/wqnxBYK3stT460=,tag:Y3oSURoC+DbOeKczlI4TWQ==,type:str]
    password: ENC[AES256_GCM,data:oVwepfOD9QdzRlgwDcOgk3kUAvHK1H00VG4Y6lalVu8CJQd5wMeU1Anh/MyJjBmgE1zvgus/UxqvlqxpTCj88g==,iv:/mmmI31x7tx03mcJkVHFddSee9F47ATF+F2Seg12xqI=,tag:N6aHeXYVrKWkypPqF7FQ9w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZeEFmOWlRd2ZXdWFvSGVV
            OHc1MzJqT2YwSFJLck9sOTV0dkRBZVhvY1VjCm9DbE51NG9rY3RaeTZDeml4MW1J
            VVZWZDZqLzhnYW1IcnJUaFJmYTNWVEEKLS0tIGowaVFwVFZnaTRTR1dYYTI0NGFn
            dDV5RU1TUEVmYW9FUkxoOEp0RTRXazgKaJzMavTICmI+AIUalOT+uvuVnTJ+H/8e
            85jNFAgmkjbC7dFRto4NTuiEcKfNpnHi4qEXvPa0X8xiTIDo0hOBtw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T12:15:30Z"
    mac: ENC[AES256_GCM,data:FsFr8RSAsti+zU8lzxKbuoWTjVi3ud8ajP298pdZ9HsSD/2BQa+IrLYoKdea+yXuQPmMYvRIO9GInpS6WOI7wD7uREeSG8n/lSUE9xaZJnxQ8mH52VefVRAtRnO7vT5wC6ALkZxBLNCFxvBOwDDTWtwIo2gUd6MbLV7OGaB1/fA=,iv:8tAy9Uwea6NH+O51weSQQGAcIDDKZVTW1Mpo678QzdQ=,tag:6ffim5L+LbbkVy13usCt4A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: radarr-postgres-v18
    namespace: media
type: Opaque
stringData:
    s3-access-key: ENC[AES256_GCM,data:dXtyYr7pHaT497YNZnpt7Z1ehmg=,iv:G/8TsM4j9NlZYhbMyaQ99Qi44EnB99JJBoD00ORVrUw=,tag:GNwmh3s8+bU2siwRp1rbwQ==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:Wl/JhmaSX3lG0JJT4EnPGTdHDF+3oPNbx1DWR3iWdr6xBJ7JYyNhPQ==,iv:w9jIlWAZLfK0285vFgKXlOaewU0uP3F5KR5ETZVQXOE=,tag:cgHRSsaBSs1aCgHZJeLjcA==,type:str]
    password: ENC[AES256_GCM,data:6bY8owwge+9qrX6jUwqucMWDahiKmMfaIOsTORXCY6m5zNx8JmYn5gY9tR+O31d6FB4KNOMIPDozV9pjBXC29A==,iv:kmUMko1z+f/SfhctJ19axXL7tTCqqzzQE/GlpaDymAs=,tag:MmGWqoKlUElaqaVFGpP7mQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZeEFmOWlRd2ZXdWFvSGVV
            OHc1MzJqT2YwSFJLck9sOTV0dkRBZVhvY1VjCm9DbE51NG9rY3RaeTZDeml4MW1J
            VVZWZDZqLzhnYW1IcnJUaFJmYTNWVEEKLS0tIGowaVFwVFZnaTRTR1dYYTI0NGFn
            dDV5RU1TUEVmYW9FUkxoOEp0RTRXazgKaJzMavTICmI+AIUalOT+uvuVnTJ+H/8e
            85jNFAgmkjbC7dFRto4NTuiEcKfNpnHi4qEXvPa0X8xiTIDo0hOBtw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T12:15:30Z"
    mac: ENC[AES256_GCM,data:FsFr8RSAsti+zU8lzxKbuoWTjVi3ud8ajP298pdZ9HsSD/2BQa+IrLYoKdea+yXuQPmMYvRIO9GInpS6WOI7wD7uREeSG8n/lSUE9xaZJnxQ8mH52VefVRAtRnO7vT5wC6ALkZxBLNCFxvBOwDDTWtwIo2gUd6MbLV7OGaB1/fA=,iv:8tAy9Uwea6NH+O51weSQQGAcIDDKZVTW1Mpo678QzdQ=,tag:6ffim5L+LbbkVy13usCt4A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
