apiVersion: v1
kind: Secret
metadata:
    name: radarr-basic-auth
    namespace: media
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:b4HmNC17,iv:sKM6He2Y8cdHdVpElnzPW0j4bsOynzhRa4wWzKKa9vI=,tag:IFesXQaNM62ULd7fUQGL+g==,type:str]
    password: ENC[AES256_GCM,data:LVfglOJQPjfPb1czKPMC6k19Mand/5flyZwjXF+K7M+wQkoliB1eSKlDR5aQ1QEpU6Hi8tPshI7wEZRFwiBd2A==,iv:G9PiuqPEjLQoJsMchd18PkgOBwaKzv90BuKXO4Xpsm8=,tag:Rsq4wfI/oEhAYOvUUIafGw==,type:str]
sops:
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOdE1MdmxLMzVtSVJJam4y
            QUQ1OSs4aHlOWGxHTWVaU2lWZXhjWUNZYW1nCkFyWWpMNXZQL2hNdGRGVEV3ZU9H
            bitmMW82dkFZSm15VXczOStoMjc5OHMKLS0tIG9uM2diRWVjbU02aFhma2FuaXF5
            UmxEQ1diV29ER2hHVHFsMTgxdXhmdEUKgA0EF6/o466ouLS5A2rukKretDbgPrb6
            Izh81eksuHAKCvOQdLJl6Yy2jS7kkLUUNbd9MVznTWG0EuRrZlG/Fg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-17T21:13:32Z"
    mac: ENC[AES256_GCM,data:91eNZR+tm5f+q2wwpxPmqUYpcxRuIUj/ONBT95h+abMPpwre5pbIvSsn2uR7HQykbR8rL+ZiMXKyUvr88mkWXSLngDyXSfyprQcNlgyLYVRexbUT99k57kl0umWdR3QLzZKPhFiiJrHaGSbgKNagBTtyfkFulOi8+HmnT5t6kBU=,iv:D0W24gsoSoc4ltKsB8e6D+dETuPId2ESfoAiMr8ZCHU=,tag:rCtHnY3ZzcvblfK5x3t1og==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: radarr-postgres-v18
    namespace: media
type: Opaque
stringData:
    s3-access-key: ENC[AES256_GCM,data:YTN/T1O6IyV8o9uAPokmqA8mG9KLkKaTBeM=,iv:SEi+VI/ykWXwuMSQk1c+GM/rBbvVebMcxgpcAxSWjEM=,tag:jmxDdJ+5AFRf2IygnI2q6A==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:YIyZf05/ULSCHt8440wI+dXiErnZEKvkgV2D5MF/HaU+BLI6+gzn8K6G3efS5M0q0n/IKTug18QNn9PoW/ZhGw==,iv:9YoLisBP/2BrUOMOtDTVh0iPzhv6vjz6r4eQDbvTY6g=,tag:h/dRlK37c0wdxQcXuR6Tlg==,type:str]
    region: ENC[AES256_GCM,data:x1fSszKh,iv:7/TSvPq6uVlq7278IrBdFzbNZ1kRimVE4rX6tdbCmLs=,tag:D8PKvtnbcgkUVR37x6mXmw==,type:str]
    password: ENC[AES256_GCM,data:UON1+m7AAHc+eQPWa+OOUrt9I+uYH3J/G3vX5bmd63QAflrqAJ+fVWDzecDtbyk58R0UBme5lsniwkLKwmNnsg==,iv:Tqj/8FZHyCLTiwbM89JfEtKgx6Hug6QDUQ/iHhZ764Y=,tag:fCMJXWbSouoeNHelx6T1Rw==,type:str]
sops:
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOdE1MdmxLMzVtSVJJam4y
            QUQ1OSs4aHlOWGxHTWVaU2lWZXhjWUNZYW1nCkFyWWpMNXZQL2hNdGRGVEV3ZU9H
            bitmMW82dkFZSm15VXczOStoMjc5OHMKLS0tIG9uM2diRWVjbU02aFhma2FuaXF5
            UmxEQ1diV29ER2hHVHFsMTgxdXhmdEUKgA0EF6/o466ouLS5A2rukKretDbgPrb6
            Izh81eksuHAKCvOQdLJl6Yy2jS7kkLUUNbd9MVznTWG0EuRrZlG/Fg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-17T21:13:32Z"
    mac: ENC[AES256_GCM,data:91eNZR+tm5f+q2wwpxPmqUYpcxRuIUj/ONBT95h+abMPpwre5pbIvSsn2uR7HQykbR8rL+ZiMXKyUvr88mkWXSLngDyXSfyprQcNlgyLYVRexbUT99k57kl0umWdR3QLzZKPhFiiJrHaGSbgKNagBTtyfkFulOi8+HmnT5t6kBU=,iv:D0W24gsoSoc4ltKsB8e6D+dETuPId2ESfoAiMr8ZCHU=,tag:rCtHnY3ZzcvblfK5x3t1og==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
