---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - backup-ssh-key.yaml
  - helm-daily-audio-ripper.yaml
  - helm-daily-instaloader.yaml
  - helm-daily-to-jottacloud.yaml
  - helm-daily-video-ripper.yaml
  - helm-onsite-sync.yaml
