apiVersion: v1
kind: Secret
metadata:
    name: forgejo-basic-auth
    namespace: forgejo
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:o+qCFXi52A==,iv:60VHCuiVmjQq7rDlC7/uTG4d006NEWwWtBS/EtqFM9M=,tag:esF/jfmsQHvjZyhnohUxIg==,type:str]
    password: ENC[AES256_GCM,data:gUh3gr392g0PIWNv/+Xb+YlA9QCAPy5A3F6g4IjR040lru87FaXLi/FaSZqx+YhGhYFaDpp+duqRifQd+KVqCg==,iv:Rq0JWh3gwlV/K+TRaKIL/oH8JV4zql102ClVYgb1pPA=,tag:TYiMjPT52BmyF2D28y4oKA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzaWFic1M0UUlrem9mWTJW
            akhvNU4wNGxHUFZnd25QbS9ENFloMWZ5K253Cno3UFhnKytObXZpSEd6ekhBQmUv
            VVlJUEtpVGZLcy9hVGU2WW51MjluUk0KLS0tIExVUVNUQVpCK3UvUUpxcHZXVXd6
            dWgzYXFmSUtvb1RnMFg1TitMVkhGb3cKwAE2MiXBIf2k8Ae9lSYoR7WZLbLqKYvJ
            hlriPIH31K1KlKVZ2dcu7LaSPFQf+0UCrER/jJi05BKq5MqBgTZkrw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-22T22:40:29Z"
    mac: ENC[AES256_GCM,data:maZxVxz7DjcY9+dzqQYG/KzajauaDKVDZEto2vHUxzGOYRpGSb9JF74A05inIgJEN8TlZBdoZINXcjztlcORPINUSd9fdDaHkxbM8WiTqKlBl5D5QHhGt7jISmJGpWy+f4h3E+z/SwgrwNPbwijshQ9KL89STbthovywnLSif1g=,iv:ykQgp5JZ9i/6mm+Jne7bUERVrg+8TtzlcmuZJfEdYEo=,tag:mt1LDxyBgD2M2wyqLyIK1Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: forgejo-postgres-v18
    namespace: forgejo
type: Opaque
stringData:
    s3-access-key: ENC[AES256_GCM,data:ape5xF6u3GQEimol6rNH/LU5g3E=,iv:NEYtuL5JJd8e/6aA7o6VXTzE8hDTD6qlQr4B7ZnhT1M=,tag:GvgXKfgpOtlgV/ufMehsJw==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:1381twkXKGpZrKu+1MXbFeZIgI6jjWM6JWvdP7yaCtwbapkhBoQG5A==,iv:zCYrlL/Weo/e4VLRI+D+YR/yu+lDQvXnK2dUw+3ctvI=,tag:p1HO09dgE5YAdZXHl5/LIA==,type:str]
    password: ENC[AES256_GCM,data:RJNNyORKZSImBa4Riz2eoWNRenfxGA3Rbsb9DGapK1QE0d0B1i1MPWgWSUkIg2eXRsa+FXxtYPGKQMl2cCcIOQ==,iv:VagGD+oe+zWWFd7HI+KAAUsrBK896goKRQcWwhMkgjs=,tag:Zow7zFDHYRDNuyvZ0nCy6w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzaWFic1M0UUlrem9mWTJW
            akhvNU4wNGxHUFZnd25QbS9ENFloMWZ5K253Cno3UFhnKytObXZpSEd6ekhBQmUv
            VVlJUEtpVGZLcy9hVGU2WW51MjluUk0KLS0tIExVUVNUQVpCK3UvUUpxcHZXVXd6
            dWgzYXFmSUtvb1RnMFg1TitMVkhGb3cKwAE2MiXBIf2k8Ae9lSYoR7WZLbLqKYvJ
            hlriPIH31K1KlKVZ2dcu7LaSPFQf+0UCrER/jJi05BKq5MqBgTZkrw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-22T22:40:29Z"
    mac: ENC[AES256_GCM,data:maZxVxz7DjcY9+dzqQYG/KzajauaDKVDZEto2vHUxzGOYRpGSb9JF74A05inIgJEN8TlZBdoZINXcjztlcORPINUSd9fdDaHkxbM8WiTqKlBl5D5QHhGt7jISmJGpWy+f4h3E+z/SwgrwNPbwijshQ9KL89STbthovywnLSif1g=,iv:ykQgp5JZ9i/6mm+Jne7bUERVrg+8TtzlcmuZJfEdYEo=,tag:mt1LDxyBgD2M2wyqLyIK1Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
