---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name forgejo
  namespace: flux-system
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: forgejo
  targetNamespace: *name
  install:
    createNamespace: true
    remediation:
      retries: 10
  upgrade:
    remediation:
      retries: 10
  values:
    #containerSecurityContext:
    #  allowPrivilegeEscalation: false
    #  readOnlyRootFilesystem: true
    #  capabilities:
    #    drop:
    #      - ALL
    gitea:
      admin:
        existingSecret: forgejo-config
        passwordMode: initialOnlyNoReset
      config:
        APP_NAME: "Forgejo"
        cache:
          ENABLED: true
          ADAPTER: redis
          HOST: redis://forgejo-valkey.forgejo.svc.cluster.local:6379
        i18n:
          LANGS: en-US
          NAMES: English
        indexer:
          REPO_INDEXER_ENABLED: true
        server:
          OFFLINE_MODE: true
          LANDING_PAGE: explore
          DOMAIN: &host "forgejo.${SECRET_DEFAULT_DOMAIN}"
          DISABLE_SSH: false
          SSH_DOMAIN: "ssh-forgejo.${SECRET_DEFAULT_DOMAIN}"
          SSH_PORT: 22
          SSH_LISTEN_PORT: 22
        service:
          DISABLE_REGISTRATION: true
          DEFAULT_ORG_VISIBILITY: limited
          DEFAULT_USER_VISIBILITY: limited
        repository:
          DEFAULT_PRIVATE: private
        ui:
          DEFAULT_THEME: forgejo-dark
          SHOW_USER_EMAIL: false
        queue:
          TYPE: redis
          CONN_STR: redis://forgejo-valkey.forgejo.svc.cluster.local:6379
      metrics:
        enabled: "${MONITORING_PROMETHEUS}"
        serviceMonitor:
          enabled: "${MONITORING_PROMETHEUS}"
    image:
      rootless: false #true # just to test ssh-loadbalancer
    ingress:
      enabled: true
      annotations:
        haproxy.org/allow-list: "${HAPROXY_WHITELIST}"
        haproxy.org/ssl-redirect-port: "443"
        haproxy.org/response-set-header: |
          Strict-Transport-Security "max-age=31536000"
          X-Frame-Options "DENY"
          X-Content-Type-Options "nosniff"
          Referrer-Policy "strict-origin-when-cross-origin"
      hosts:
        - host: *host
          paths:
            - path: /
              pathType: Prefix
              port: http
      tls:
        - secretName: "${SECRET_DEFAULT_DOMAIN_CERT}"
          hosts:
            - *host
    persistence:
      enabled: true
      create: false
      claimName: forgejo
    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
      fsGroupChangePolicy: "OnRootMismatch"
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
    service:
      ssh:
        type: LoadBalancer
        port: 22
        loadBalancerIP: 10.0.1.44
        externalTrafficPolicy: Local
    strategy:
      type: Recreate