---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: forgejo
  namespace: forgejo
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: forgejo
  policyTypes:
    - Ingress
    #- Egress
  ingress:
    - from:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - port: 22
    - from:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - port: 2222
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: haproxy-controller
          podSelector:
            matchLabels:
              app.kubernetes.io/name: kubernetes-ingress
      ports:
        - port: 3000
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
          podSelector:
            matchLabels:
              app.kubernetes.io/name: prometheus
      ports:
        - port: 3000
  #egress:
  #  - to:
  #      - podSelector:
  #          matchLabels:
  #            cnpg.io/cluster: forgejo-postgres-v18
  #    ports:
  #      - port: 5432
  #  - to:
  #      - namespaceSelector:
  #          matchLabels:
  #            name: kube-system
  #        podSelector:
  #          matchLabels:
  #            k8s-app: kube-dns
  #    ports:
  #      - port: 53
  #        protocol: UDP