apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: forgejo-config
    namespace: forgejo
stringData:
    email: ENC[AES256_GCM,data:KEh5YIZ6DLLDjzKK3UnoUFI=,iv:Z33ODaLWpzTZvBY4PYagiYSmU345P4b6wNwO8gpzHLo=,tag:y4mOHgMp9bwZsFy8ydad3Q==,type:str]
    username: ENC[AES256_GCM,data:t6mxzg==,iv:N3R8DRC7H+KGrj/wU5T1MbbToN/jnAwUJulDSSWJTC0=,tag:9qIIskj/jCXF1D+8DXVCtg==,type:str]
    password: ENC[AES256_GCM,data:zc+YwLsaC35B+0MF9cg+UvUXHDLkR/S9THMTFLCw5UgWrNotvitc5DgChLJ11PQ8aesF9CpbU6eW2414j4wRJVNUxgTHu8lunYpMJm9tGquJ2RJ5r7UEGA==,iv:N8v9HUb8BVwsTnnnbHd2wIRalczVNeKdmevdATwpnxA=,tag:gvas8jzFui6L72Z8mgKNZw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArdkpmVU5TZm1NeGt6YU5L
            bUQreTVLWjhZZVJ5cTJNclVqdVJ0WnU0UUhzCldpYnFRVVlQTnU2M1Fhcnlramhr
            TlpmZUkyTU9lY0p5NEl3MFRBbWFDdEkKLS0tIFVOaWNkeWpXYW4wRWRVbDFNUlFo
            TTFETFluejZiSWxtWUxxK0p2V0daYmsKK8X5HylCLZi2H1Sp7567UmSD2CAA1e/B
            Zz958wZR0LhT8TD2yl0PnL02fgvVgtWWJYh223kijY1weQ/rRLctgQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-30T03:22:17Z"
    mac: ENC[AES256_GCM,data:iP4BTjSZIE5WKfRb60VC+TPt36nm79hWaXx+r0m8+CTkorNTUxF2iLvOpxruWr3/fr950NUg88APeqzWZgyR1NViYAysSu6sHbeeUGl4sjT8tI+jg5iFuTm2Pc0aDxWbZZvg71Pm4/rL4ZMK+i5GxaWThXrKNYnVDLl0y7EZrCs=,iv:cQu1SY/rnIcOE4R7xXtm3OE1pZQDvfEhDbSb9ZkoItM=,tag:tyRKQV0U2H0PZcYK4RKyjg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
