apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: forgejo-config
    namespace: flux-system
stringData:
    email: ENC[AES256_GCM,data:auc0QxOonOa9BlPSlw1fDD0=,iv:F/uRCNZe2mkuKK3VDwnpBm3gTRgkG8b2VdAfU3H7XAE=,tag:x6zjzujs/722ysPFB18iWw==,type:str]
    username: ENC[AES256_GCM,data:vaD8sQ==,iv:+aQhLv0YJKnQaK0nxUoO3UIcWvws9PwaUR+c/6+bTUQ=,tag:ypQdGve6ao4TE3Z8UyvDgA==,type:str]
    password: ENC[AES256_GCM,data:7oBnQox2XWI+A5fLdKYFubrIrPUrg5IqiL8OyQrvql6rwKq/CcMCD4+7tBHd2ViT3DDpBFBRtcuFR2s5ZI//drh/1sCj+ibwGAkKeShZSYmRwKBgq38xTw==,iv:hi5JuIK8QtaHvamAcSGVeiRHxZlMmdNohqnKNeryDJ8=,tag:rdrm8cZ+/6qcbTLQu/FVyg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzZnJRQVFQeDZXSEtzZnU5
            MHdoT1dGUmc0UlFhMi9mMHFwZGVGS1BuL0JVCmJodEdGVFVycjQ1RTNEUDJzTHpJ
            RW9vS00ybEI0cm5idTlENEFWQTluREkKLS0tICtha2V3SDdtb3hrM0NRNTJNZ21l
            TVBFcmc3VndQdUIxUUJuZWJDV1hES28KxSP+Oxx7OJkjGzCvFQoc8nCwZJFt+D/C
            +uUUepJI1+NQqUOxHd/S0i36fy3IzV4EALXbZzickR+CQbMZAIbI3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-30T03:09:15Z"
    mac: ENC[AES256_GCM,data:0MDML6YkPvudXo6qrV26rVPZdY+3ZZGJ05FWuUoep0bY0hEH5FRR9CxoHCika3UK0ReoDmcFJlONfYxIIfhyvBX8qVCA6xV7OPle7HLgayScTsVSvI0/O5R2Sb4GrbX/EnG+LCs1N5GpvEq7Ao8JW4/fukw1pW668e7prOE6SLA=,iv:LWge737Gj/LidUNHSwZ+PtVBkEQDAGsl8jk9wCNkEiY=,tag:ZgNy4Lh0I8WEVWAZiMp/aA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
