apiVersion: v1
kind: Secret
metadata:
    name: immich-basic-auth
    namespace: nextcloud
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:6DYTw2nC,iv:xMajOsKUeDOmIl23FjrN6oVbMEUzMlRbK7f21wN/E3E=,tag:50iwRUzlsqgHrwzTH20zaw==,type:str]
    password: ENC[AES256_GCM,data:0JqD6vHYAnw91c5G59bgWrKAK51oxdg1jdyRnSEdfRFd7gvfOmK8IDT5fFSFkt17oIoNoyh4K3uw2DosTZrr9A==,iv:LoY1ykhPkdpei/xrBu5b1g7UVdQlZE73+TcQXNF0J5w=,tag:+SIIzJn/Fsqal3zw3uoFEA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByTUo5MTRJZEVMNUN4VGxN
            Z1NmK3RZV1ZpclVyckIwQUdtVWE5TzFoNFRrCis4Um1OTldHUFFJMUlMT3F2SlhZ
            SG40b0R0UFRQcEFEaEVaRHdvRjRjaGsKLS0tIFEyNVg3aFl4ejRzS3BnY0tIRTlx
            WlFNQnJXU0c4Y2Y0RFU2K0VROWNTVUUKeUqCBu2VB3HdB2CJW/aVFmEcvdHKAs+F
            rWFcITdgjD5LHJiAxT4DPx7A9HOoE3Dom70hiaNpkZSSOuYDEh5aKA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-29T00:26:14Z"
    mac: ENC[AES256_GCM,data:lbz6HGg8Kdtphsh4eXBWjhmcZhg6lDsy/A8132PbE6FDZEDpzMJ3T54XoZLZkLnsVcAqLPT8GbtobQgZ+veOQ7Na6XqzwGAudP8h8pmMJ64J1832r6VoIu8L47RsiSZxEIEMDZEbpddYC0TOq31lTfcHVdz4xGcG2ZgG1AOcWbo=,iv:HBzJFiIhjWo6cgumw9PUtFEqjzhouvZ5jwgHFLchLoU=,tag:NEUrom9eoPHpsM1bq/kaIQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: immich-postgres-v16
    namespace: nextcloud
type: Opaque
stringData:
    s3-access-key: ENC[AES256_GCM,data:x0xmFHsTBu6NfO8+YskpTNEPp0I=,iv:EVCnWtr1XbIF88HubY7LT2Essoel/sj9jWHYKJuJY6k=,tag:PzFcV7Ys2T9/rxdghmakrw==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:Bjj/GOVQ1WVfu6/og8w+vLGfQl4dbjqrVyvTHLr5AQySDZ2WGvuIMg==,iv:cUUnO2Uhu68QbJ/6RkHolV/jgRlpcY2Ceoz1lrTN1vg=,tag:osWjrbQh+jznTYaBCUlpQA==,type:str]
    username: ENC[AES256_GCM,data:d1AjeWO40dI=,iv:WYopV+PhliLVDKXn2/bhAXOihEGcgncXQ0nzi4EIYag=,tag:TYUJrn98rQqzhKNEi8myjQ==,type:str]
    password: ENC[AES256_GCM,data:AGzwbIPpbZoVDCm8Q8Ra+Efit3KZFrQoQj93zOAWmsNeQ/fNt4HeWS1VtE9BhXdl+k1aWE5wQB7fbpiDNOKgPg==,iv:zFEPbkWuY862Oojm3oOeOx0phg6gbsL8aXiFdYTL63k=,tag:SWaqmIYq50x6SovWN/TdIA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByTUo5MTRJZEVMNUN4VGxN
            Z1NmK3RZV1ZpclVyckIwQUdtVWE5TzFoNFRrCis4Um1OTldHUFFJMUlMT3F2SlhZ
            SG40b0R0UFRQcEFEaEVaRHdvRjRjaGsKLS0tIFEyNVg3aFl4ejRzS3BnY0tIRTlx
            WlFNQnJXU0c4Y2Y0RFU2K0VROWNTVUUKeUqCBu2VB3HdB2CJW/aVFmEcvdHKAs+F
            rWFcITdgjD5LHJiAxT4DPx7A9HOoE3Dom70hiaNpkZSSOuYDEh5aKA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-29T00:26:14Z"
    mac: ENC[AES256_GCM,data:lbz6HGg8Kdtphsh4eXBWjhmcZhg6lDsy/A8132PbE6FDZEDpzMJ3T54XoZLZkLnsVcAqLPT8GbtobQgZ+veOQ7Na6XqzwGAudP8h8pmMJ64J1832r6VoIu8L47RsiSZxEIEMDZEbpddYC0TOq31lTfcHVdz4xGcG2ZgG1AOcWbo=,iv:HBzJFiIhjWo6cgumw9PUtFEqjzhouvZ5jwgHFLchLoU=,tag:NEUrom9eoPHpsM1bq/kaIQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: immich-postgres-v18
    namespace: nextcloud
type: Opaque
stringData:
    s3-access-key: ENC[AES256_GCM,data:JEXPw4UTM7mGN0uE5dyG0lNL3ps=,iv:bi58m6tmyAODpoQVJdal1/WzFB9ODH14kE8VcQ11MUo=,tag:siIgsGejwx0Jo2t6VSKh8w==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:fsAiZYTqTUf9N7AdMU7Uq/ldwAZOkYzZwSe1bKo4sImcXA1461oYvQ==,iv:DfRXmRfPTD6fHUK1ki38wdleaOCId0rtP6bxcJyAbpM=,tag:G1VbMHroqJRYGStSf4IHow==,type:str]
    username: ENC[AES256_GCM,data:FhGwcXKpBOY=,iv:PrWtvIsbRR3x/SzdBuj6w9a8yXesHoh7AQ0ojIQv5kM=,tag:kmouTMgBPqJD94kKTS+VBQ==,type:str]
    password: ENC[AES256_GCM,data:FQT0G8LcDiZtbpvKh6UVW4HwbaNe6dDKW8qHo0XtIJT4rxZS/MZ9DyFU/AVDViAp77gsCvdgqwZkRKz4rjERHA==,iv:68N9D2DDY+qnGUI0iBuOrfqpgpp4Hokuj8zbc2yaED8=,tag:NqKVtylC7/tQ9YjHnSth9w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByTUo5MTRJZEVMNUN4VGxN
            Z1NmK3RZV1ZpclVyckIwQUdtVWE5TzFoNFRrCis4Um1OTldHUFFJMUlMT3F2SlhZ
            SG40b0R0UFRQcEFEaEVaRHdvRjRjaGsKLS0tIFEyNVg3aFl4ejRzS3BnY0tIRTlx
            WlFNQnJXU0c4Y2Y0RFU2K0VROWNTVUUKeUqCBu2VB3HdB2CJW/aVFmEcvdHKAs+F
            rWFcITdgjD5LHJiAxT4DPx7A9HOoE3Dom70hiaNpkZSSOuYDEh5aKA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-29T00:26:14Z"
    mac: ENC[AES256_GCM,data:lbz6HGg8Kdtphsh4eXBWjhmcZhg6lDsy/A8132PbE6FDZEDpzMJ3T54XoZLZkLnsVcAqLPT8GbtobQgZ+veOQ7Na6XqzwGAudP8h8pmMJ64J1832r6VoIu8L47RsiSZxEIEMDZEbpddYC0TOq31lTfcHVdz4xGcG2ZgG1AOcWbo=,iv:HBzJFiIhjWo6cgumw9PUtFEqjzhouvZ5jwgHFLchLoU=,tag:NEUrom9eoPHpsM1bq/kaIQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
