apiVersion: v1
kind: Secret
metadata:
    name: immich-basic-auth
    namespace: nextcloud
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:AO60gWUh,iv:PHSVFey0I+9mh9PUlS/ZSmfvvxBrzF72HY3arO7sdBg=,tag:dd8+Ipgr6mUd99559jjNeQ==,type:str]
    password: ENC[AES256_GCM,data:SK6ZV0kPipfeMNkuiMHhaGXj5iOhCcfoFjdcHG9x8JrKdq6qVfE3YdSSut1wXBe5YkYx8adGxZG/aeMkan0a0g==,iv:2zfTb9c0kpXU/pc+mZIFhY6DeHWw8un3hRi4bykyNUE=,tag:VDgnuGAQIYlhisRlIxHtPw==,type:str]
sops:
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvZkljVUpqSzNaNEJoNC9S
            cGNCejhrZHZLaGhLVFRwYTZBdnJwN1lNRkUwClRlMzFmYXRqbTB6QVIrK2ZybEZs
            eFllbnc0NzE0RDlCOFlENnQyQnBiWlUKLS0tIFBtazRuOXJ1eVpQa2x0Zzc1MW5K
            Mzl3QzdWUW5mMFVYVXJQU2tLZHlOam8KXafBiuZUTy4I34EeweJKAxjpUsa91IKo
            VGamY4nWZBSOBu9+KVOebZu9tl6Wjb/GQDfM1UbSOIGJ4U2MxOI94g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-17T21:13:08Z"
    mac: ENC[AES256_GCM,data:P5WwceSQF2VmKWftyc0Ir8mUBMyPz8F2vNKPZIyWgy1X6BaiKXRzyKDIvQJFIFtn2BeHKRmJ2/9wQ/YKS5FopZK7HfRXP9K8efup4SVK5gEPAH1ZHNezrP5Me8qx5q0Vti68pRVvH+g/Oeo/TMNeLD9zs/O9XfBnbKWx/gVHMO8=,iv:7tA17hFRZwTAk7vo19Gs/tqsqAGxa1nQ4M0fr/fnXd8=,tag:AZayeERjgy/iygJ8nVCdcQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: immich-postgres-v18
    namespace: nextcloud
type: Opaque
stringData:
    s3-access-key: ENC[AES256_GCM,data:PTdFkEitrc5hY1ZEqKLxlgAf3xBwel+b7JM=,iv:/dw8HY99RIPtCq859WZo/0bdG8K1rBb02R7SZA7E6wg=,tag:SR5uqVaPwofG8wlMV2/afg==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:uW0wB8z5EexpgLCq9HY9N1pKmFfhY4RElSqdSzxxlDLIrY2j4vYKoOUaKEcRheiJ1MFTvT2wZgAWi9bCNt/oMQ==,iv:SXWjT3E506TuKBQfcW0MdrI14Sy0ivqNNrnVkA0PmwQ=,tag:ht8GaDQdKjPU1Im1DKK10Q==,type:str]
    region: ENC[AES256_GCM,data:2Cw/EuO/,iv:IP6JyW20QOZY+7SCE6e3NRpn48UaF0ln8DjxEjwL9Cg=,tag:RyTLQKLSJFXROW/DhcSf8A==,type:str]
    username: ENC[AES256_GCM,data:8y9AIX6KQ8Q=,iv:g42MFaRjkxeTBTl9Uf+Fqb0Oxoryso6evOZgcrrIzk4=,tag:Um3xoylYlJeXyWKwlm4WvA==,type:str]
    password: ENC[AES256_GCM,data:fJvUcjQcBvqnDunvZL9aQ1mod51968TZNcuClUlrQ3m9y506pEd2E+LXCyVi2DpSKiiVGZadkCzcaIo8T6u85Q==,iv:XMkqN1AjjzypiQYc4QjbxICLD0DjZ8GD7QhTNk0coLg=,tag:Hlmv6JMGFbohGRW80CGu8w==,type:str]
sops:
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvZkljVUpqSzNaNEJoNC9S
            cGNCejhrZHZLaGhLVFRwYTZBdnJwN1lNRkUwClRlMzFmYXRqbTB6QVIrK2ZybEZs
            eFllbnc0NzE0RDlCOFlENnQyQnBiWlUKLS0tIFBtazRuOXJ1eVpQa2x0Zzc1MW5K
            Mzl3QzdWUW5mMFVYVXJQU2tLZHlOam8KXafBiuZUTy4I34EeweJKAxjpUsa91IKo
            VGamY4nWZBSOBu9+KVOebZu9tl6Wjb/GQDfM1UbSOIGJ4U2MxOI94g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-17T21:13:08Z"
    mac: ENC[AES256_GCM,data:P5WwceSQF2VmKWftyc0Ir8mUBMyPz8F2vNKPZIyWgy1X6BaiKXRzyKDIvQJFIFtn2BeHKRmJ2/9wQ/YKS5FopZK7HfRXP9K8efup4SVK5gEPAH1ZHNezrP5Me8qx5q0Vti68pRVvH+g/Oeo/TMNeLD9zs/O9XfBnbKWx/gVHMO8=,iv:7tA17hFRZwTAk7vo19Gs/tqsqAGxa1nQ4M0fr/fnXd8=,tag:AZayeERjgy/iygJ8nVCdcQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
