apiVersion: v1
kind: Secret
metadata:
    name: immich-basic-auth
    namespace: nextcloud
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:d1ZBAYGp,iv:HgUHYmNBp7ONaytys5w+2j6V6lKnQA/3klfiP6Nq9tQ=,tag:3oNk4E8KmSYOGEkCN2fuXQ==,type:str]
    password: ENC[AES256_GCM,data:ARbfmQ1+ynj9xNu6KI7dIuAQIvz7/IJ43B6X8Uc8MnjnCqiAJTBvmoiWtNOUtzXsZeTkqftUtN/FtGt24A4D3g==,iv:vM75PMMfDWsPZzm8HeRUUUPW/QL0+RxInflAhBRIvSY=,tag:9AyxW/tbIAYS0PVjO7ikAw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0RlFNMytUQ280azlRRVBy
            Q0x5RllQYnJNc1RZSkFGNzVpaVJ6TmxSTW5FCldrSVMvNTNOVSt1WlhGaWpGVG5a
            M0Flbm43MEJPRFhSY3NqL1NYWVBYQ0UKLS0tIFJsYWxEcWZsWXhROC83LzZDOE8x
            K0c4WC8zY2lUeXJGWDIrOW1mcXphQVUK79EaBCWUkhGDUgcZhfr9dTYApX2tEhZd
            4CokvDcK2fjVPxRQsgcWnT119GBvnV5i4CDMK/XMm/KfatFSB58lyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-04T14:28:15Z"
    mac: ENC[AES256_GCM,data:xm5dABz5AdjMHUV/6CqDTjD4ffu3KI/o/fugauiCOwfAsZiKJwG7xtuk38VnZv1CqYneRqUMDd0RLTgu+ErFOKj8rqJcOktcQGV83nl5tqCNm30h6EZhX+JB40unoL2Ji5FkBS/0S7zJWrZPRaoUrmdZ1Ww9xAI479Mxaq1q6tE=,iv:fG+7SgJ/Ewf2K6V198ihYfep2ZSTm13Ol+RgcTUqSn0=,tag:uD3pNgHadlbkXHvt91ADoQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: immich-postgres-v18
    namespace: nextcloud
type: Opaque
stringData:
    s3-access-key: ENC[AES256_GCM,data:HIpxztAsAph0EOg3NE0RRUxWnac=,iv:10knfbNBY1lvshOnIXwRaSMQbTkeFQaLXJS6JKUBQ/Q=,tag:dQTZC/UoFXR8PfIVAGmtGg==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:6rcZvM2RG2lWtg97rquZGGsKFk4TXUWttE5sm5YMwNlG4obpDV6LPQ==,iv:Rsq1IliLhlieAabKHw07tIKoOlsbX4vvkd4fSqcz6iI=,tag:QPRz5IQQwM7KEwdm2eLcYQ==,type:str]
    username: ENC[AES256_GCM,data:yQA7xcR6SDY=,iv:tj0Wb3UhbgM3eR6j+Y5JkTIcq4sJ4wg2dZ9Btv0Dtzs=,tag:IM7r4wwN5pGV8JBjpinGpw==,type:str]
    password: ENC[AES256_GCM,data:BiC48ETGT7GIKOmd9ivazdlHpde8UBVH2IxvnEDX8GT0iSy+BBrVjtKGFNUAx6IJO2Jok+eVBno9HfRH/N3Zqg==,iv:7wUyyHhdNrNTI43Xx+Xz4sWJwakDedpKJ10HKikDvBo=,tag:bHcGFkP7GQUp9NG9kryGyQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0RlFNMytUQ280azlRRVBy
            Q0x5RllQYnJNc1RZSkFGNzVpaVJ6TmxSTW5FCldrSVMvNTNOVSt1WlhGaWpGVG5a
            M0Flbm43MEJPRFhSY3NqL1NYWVBYQ0UKLS0tIFJsYWxEcWZsWXhROC83LzZDOE8x
            K0c4WC8zY2lUeXJGWDIrOW1mcXphQVUK79EaBCWUkhGDUgcZhfr9dTYApX2tEhZd
            4CokvDcK2fjVPxRQsgcWnT119GBvnV5i4CDMK/XMm/KfatFSB58lyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-04T14:28:15Z"
    mac: ENC[AES256_GCM,data:xm5dABz5AdjMHUV/6CqDTjD4ffu3KI/o/fugauiCOwfAsZiKJwG7xtuk38VnZv1CqYneRqUMDd0RLTgu+ErFOKj8rqJcOktcQGV83nl5tqCNm30h6EZhX+JB40unoL2Ji5FkBS/0S7zJWrZPRaoUrmdZ1Ww9xAI479Mxaq1q6tE=,iv:fG+7SgJ/Ewf2K6V198ihYfep2ZSTm13Ol+RgcTUqSn0=,tag:uD3pNgHadlbkXHvt91ADoQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
