---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - adsbhub
  - fr24feed
  - namespace.yaml
  - opensky
  - piaware
  - planefinder
  - secrets.yaml
  - radarbox
  - readsb-protobuf
  - ultrafeeder
