apiVersion: v1
kind: Secret
metadata:
    name: global-settings
    namespace: flux-system
stringData:
    SECRET_DEFAULT_DOMAIN: ENC[AES256_GCM,data:ksNEXGYTpghb,iv:hV3Xh0xCywCkfqGjKTN2S935qFdd6keki6NIeZwF3JM=,tag:l7APPab67V1E/cCFg1/lhA==,type:str]
    SECRET_DEFAULT_DOMAIN_CERT: ENC[AES256_GCM,data:+6AVRxT7THf32A5Sv4pKx8Wy1IgUdaY=,iv:w70Papqg5MvdHU7EQCLMjKk9OYHMOLJFEoJX0IEPnN0=,tag:SPMnJSojUrLtNUCTSIKsEQ==,type:str]
    SECRET_INTERNAL_DOMAIN: ENC[AES256_GCM,data:WOTuzzvGD14X,iv:8AZwl3hqwhyCAmF+EN6OBQkfT7urOLdxs+qpKc+Wb2g=,tag:TwLczkAYcR4zY/hoeea3Kw==,type:str]
    SECRET_INTERNAL_DOMAIN_CERT: ENC[AES256_GCM,data:K/ozjypYXiqw74UL8oq6NR19kM5dl+g=,iv:V6c1ayzbVqBZAofDAv50Okwzvzi2PUfESzooFColgzQ=,tag:sNavrqIteCXWmmHjdNldZg==,type:str]
    SECRET_PRIVATE_DOMAIN: ENC[AES256_GCM,data:xqgBGuhy9KRb,iv:CJGRS7FUeEjra2tBP1wAmVGxFgL3l2XE8yu61I4Ldlg=,tag:yPu9WEHmW5vD7RJGEaNBQg==,type:str]
    SECRET_PRIVATE_DOMAIN_CERT: ENC[AES256_GCM,data:kpSQXv52w22sT83Uh18ovREZtGZ1dc8=,iv:vf9V2sigvjAmcgBsx5TBSHWh/byYh5CcL/rKiEobQpg=,tag:O5IbYjsrHSuC+2ldjChKuw==,type:str]
    SECRET_PUBLIC_DOMAIN: ENC[AES256_GCM,data:2+yZMyHpa6Zwu+ItPQ==,iv:f3MLrNioCFTLULrnF6ghMeODJeEDtFkT+w9jMLHtqtc=,tag:lNxbNw++S4YQJT8cXT0cCw==,type:str]
    SECRET_PUBLIC_DOMAIN_CERT: ENC[AES256_GCM,data:YhZOGde45oyPtym0rcRpuqzZUHPDaUYOkter,iv:qGr8I/qzpUfpbl2VQbpOk2VFS4ToHVZCT9rpRhCyaCM=,tag:e/kMqUL+cKog/udShKbT7g==,type:str]
    SECRET_OFFSITE_DOMAIN: ENC[AES256_GCM,data:1Su0lQcf42xGTd6S,iv:mJPx6/8Kv1Tj+VbhneWlbYRAl91hfJNUEcUnekNaNbU=,tag:WDwtt08DYYufnroJxeeffQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:YkMav0pm+kIFlrqPYw0em8BXgH8=,iv:+2NJGODACCgyUW3N/H73k/CoZs4zB5uRdEWjaMEm4Ho=,tag:/pF3xxRgxGDode12gSt4mw==,type:str]
    SECRET_GRAFANA_PASSWORD: ENC[AES256_GCM,data:QBsjOg4l2AM=,iv:dsvTwbdCk2pKuaM5vlau16DPC9tkojP7bKXXCcB4dbc=,tag:m+L8OZrmSCJTBBQjLl3sNA==,type:str]
    SECRET_DISCORD_ALERTMANAGER_URL: ENC[AES256_GCM,data:fTaeZSlh+ZJkqSJ5+rdtU4kVN+Tr5k5KVfgX/QCZYlInJJiKfEMabBmuE5nfogy7NR4jAap2BBOxaFgyyqZxpKJoVSoMvFUCwl4MCm2NsMcx4IRnG0UJdh1fkGO5anJYDVnHGXvrFIpxhHHMXboQD0t0LofSjANPqw==,iv:T1SxIrKRmHBJf+AKJSUORMcSEQe7mZqB8Bt6RcajHzc=,tag:xVZFXhwTZ13lwN30IjzXiw==,type:str]
    SECRET_PLEX_TOKEN: ENC[AES256_GCM,data:EPAgXXzvcKKBVVXwZEvoI7mWjj0=,iv:2AaNOrDs9ivNlzOdjatojXPsUqPFbMSGoCzCaMDwcwg=,tag:UOAhwzHwrKpTJHU4RRY2lQ==,type:str]
    SECRET_JELLYFIN_TOKEN: ENC[AES256_GCM,data:ugh1I80ttBgwy2i3ZingvT76rW6Ryk8YVUL3MT3mNPU=,iv:lHeT008cyBkRID+KcGToWiNdqrtfq7klPY5jjhxpI+E=,tag:dppcx0T5nMroERzFPYlxMQ==,type:str]
    SECRET_PLEX_USER: ENC[AES256_GCM,data:fO3u+Am+aRBBfg==,iv:ayypjrw0OxUacLYd2khcxT764pWZ+Y0JRHRqk/arTY0=,tag:iqphfnHKDyWUkJU2H9epZg==,type:str]
    SECRET_JELLYFIN_USER: ENC[AES256_GCM,data:gmQBEA==,iv:q0Mmypc2xnxU8cpD0sWRBaYooS/S9s8cPzgBpf/defk=,tag:oe74YUQIP4xALUJLQLQtBA==,type:str]
    SECRET_TMDB_APIKEY: ENC[AES256_GCM,data:C4XK15M8pJhW4Vd/fThQlvkeurkklPZwnfikop75XY0=,iv:kMTA4kFKR7pEdQg17ppj7ThS8Vwm/CMYLC1pFFNDuRU=,tag:2mIqeSZ35NBQx0aDaXPPJQ==,type:str]
    SECRET_ALERTMANAGER_HEALTHCHECKS_IO: ENC[AES256_GCM,data:N5r3QKZhVHodYCF5nODQDmdtyxcNfKOOQHbtrNuSoZL3whHi+hB145QeERL5NuqRp2Cu6YF9a4o=,iv:qg1YLeYxbQ8X53DGCiC1olUpDDBsXVVoOVvWToIbIBw=,tag:futqFbCaENKIBu31UEJYUQ==,type:str]
    SECRET_SONARR_API_KEY: ENC[AES256_GCM,data:Ak2EpBuOrbekv253n6KddTkEZN4JjxCGI+72067DUE8=,iv:Rs0cMb+IhZHpjEBFZsDpZrMJa+Z2AKEmRvb5MBcrb2U=,tag:ts54CkieQjKUu/pRu2qk9w==,type:str]
    SECRET_BAZARR_API_KEY: ENC[AES256_GCM,data:Tj3fbx92VEFgiSYrFlxO5+EEMkDcqFF5+hOZkTsfoks=,iv:RVOUkc6LwcqB4TUJcQQmT2TgZ4VDnHOlDmCU/XZE87Y=,tag:4F5ndxhPsCxUfpTaKFOStQ==,type:str]
    SECRET_RADARR_API_KEY: ENC[AES256_GCM,data:uYtM49TTiwqihcm9//dWtTkBo8WsymJNbe0dOsGuqkM=,iv:eVNxdcXY6n3znzVvOqgF45EOKCn/7EduStmUbwIJyK0=,tag:OuvRPa6/M8F65pbGVyb+HQ==,type:str]
    SECRET_READARR_API_KEY: ENC[AES256_GCM,data:CnGjqsZjYt3xa8b2zaIw0NeDU4iEc4qWBCco/yu+56I=,iv:TXdy2bstiJC9LQLohuE8YMvqEVmmSBTgCNvLpbVRWSU=,tag:aNTw8SwMauR9ZuhilnV/ZQ==,type:str]
    SECRET_SPEAKARR_API_KEY: ENC[AES256_GCM,data:c0vYNxLmiTI8n+XPrGSq19BxPeeTo4tacHu9oOHTyFI=,iv:MSUtvEJ6551+9MVz3ykwgCs91sltjyB4Ld4qEU9Ue3M=,tag:jh5Edv2aF2ic7+nPHnRGhQ==,type:str]
    SECRET_LIDARR_API_KEY: ENC[AES256_GCM,data:Dh/EstWjyXK+Av620JdFuP9zZGr90U+UfnVqxvEH8hc=,iv:ST9RC+NBqIaWj9Nq90EzLKnUUzWUanZB1f34f3WMCwc=,tag:k6WHMx5EvH/v9pGWIm4ufA==,type:str]
    SECRET_JELLYSEERR_API_KEY: ENC[AES256_GCM,data:HwTPiIxf8sRbbBjWkikxsbM7ZmwMhrD2qYZvrS/Pu9SL9JybpLuLM4CYo/eWxEBK2UfcJExMxtaTTnt1THRys0ZQ7SE=,iv:6JZovb6ab5CqVwHyhFOVAPklyuloXyChzyjuk02iTgo=,tag:e1I+lemmjRpXjTVs2aEv9g==,type:str]
    SECRET_PROWLARR_API_KEY: ENC[AES256_GCM,data:SRNuf7Sf7lpc0hNfcCIzVTGujvbQS8vOw6Svt9KQW3E=,iv:Cr1YKhQ/xZZRbABFQYTbESs9Cvt7rrcHtt2Ze81PK4M=,tag:OFT23uSWaoaD15iJ6IYaEQ==,type:str]
    SECRET_S3_CNPG_ACCESS_KEYS: ENC[AES256_GCM,data:gJMOTZh8nKOvnhfrcMSWz0EpS7R3SWPSfo8=,iv:7lRV0Krtn0zufOW4lpwwsvEKg0N5tiRlC6r02OdVW+A=,tag:zDoZKdSRugbHPNZ60ih58w==,type:str]
    SECRET_S3_CNPG_SECRET_KEYS: ENC[AES256_GCM,data:cldeoM2UUFUqgdjqhalpQDjssWOod54Z2KfDVvinbgQqHA02jC32x2f357nFOjeAKXS4Vltj9igcoo1rdymT6A==,iv:BDPmESDOTeqrUFrr5Ekbzt6WVBeHMj2/tKf9DVUCfWw=,tag:yp1wpvSfgd137PrD+eMaJQ==,type:str]
    SECRET_S3_CNPG_URL: ENC[AES256_GCM,data:GeZFg2047VA7sbDQ9Fokkrn5EgBmMijxpA==,iv:pAiQfgnPq5Ef1IlSxxKcxRx0jyZQuETjAXahyyngJGg=,tag:ZZckYCq9fEjJayAKj5WiCA==,type:str]
    SECRET_VOLSYNC_ACCESS_KEYS: ENC[AES256_GCM,data:YdiNGPOYYcol1Gv4UFgTwkifT8I=,iv:pSX7KIaTSPHoadcovA9Ad3x3riiJIAs5ME45iuRh+m4=,tag:AqaRT/rb9/9Eg4aM2Pvucw==,type:str]
    SECRET_VOLSYNC_SECRET_KEYS: ENC[AES256_GCM,data:K6AXyCCnKHmj+OFQ2c3rrc0lud9wTqUDydNXWBf79/oB5GL5X4OyOg==,iv:jdYTHQRxEbpJaXN4qOrQDHTZkELPwkIt5VuJIZ3zCGs=,tag:tHZx8V8GDeC4Pg/QrTXGGA==,type:str]
    SECRET_MAILRISE_GOTIFY: ENC[AES256_GCM,data:/06NmFfXmnmELkfnID8/Xmz0OGDdS3aSCfYNauQ35lvB0XoeorNGgIzPVpFfQcPErAEAcA6MrWk=,iv:QZsH+yOSeNjfWh5iHWRZlxuCnqWfmU5FVzfyCQ/KxQE=,tag:KX32DUPO0DFRzwzXprkq8A==,type:str]
    SECRET_ALERTMANAGER_GOTIFY: ENC[AES256_GCM,data:iAePODdX5xJVlL1Z+oFN,iv:DNmOWryx7MkqFn1muWQm6sMg6ELZ8B3BXbt5d71mlz8=,tag:PY81AoR5I3tdSEgVndamWQ==,type:str]
    SECRET_S3_URL: ENC[AES256_GCM,data:SNAqlmwu9rLTYUmohgbzibFEcuq1yIrcN1Ns,iv:bo1Ry3Jdaf5DTuK4MYDjPfFzFc3WWSDw4JBD2z9b/dg=,tag:dNfUJWf6FPwLuez5IKi2/A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpdHFtTGs3eFlzeFZaWDNR
            aUx5aGpkUlVBdjREdll5SVE2eGJkSWZCWkVRCitGY2s1WlpZNlYyK3F5ZStMeDVM
            d09RN3RiWE8xOWkwYjBmeVJTRTMrRW8KLS0tIHdOdWNPWGREYlJOU244Q0thbE5J
            NHo2WS9CVjIzWXRiY2h0VzBvS1dEWHMKNjRLBNS0YWm/fpLM7LxpfiLk7DGPKrg1
            af0LQtPBkUYDyZWpmBbr7la9cma4/6QmgOxrhsPK0IUGzK4zCf/Jmg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-22T23:12:28Z"
    mac: ENC[AES256_GCM,data:hCOWGB5bX5QLTe8RAfuSQ6v3pvRUCI4lAXIUugP7H4yTx0Uut2vD51v91HD9RquVl7lX8oz4qWI6JZ/Qc8Yio8XSYz1eU8BjA8bLzwoj4bOql64N242MPsG2Weq3IuwNLAC/7hwo49YYBT7k9W8gttpiPWFzrmwU6EIHnzcnHwM=,iv:QQPEmVgRIpYPqYTEwW8DXtoapZUGjUd0PSb9eyLG4BI=,tag:/08+vg5V4r4aH2rE8W9d5Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
