---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../botkube
  - ../cert-manager
  - ../dendrite
  - ../docker-registry
  - ../external-dns
  - ../haproxy/haproxy-ingress-daemonset
  - ../kubed
  - ../kuma
  - ../local-path-provisioner
  - ../metrics-server
  - ../reloader
  - ../snowflake
  - ../tailscale
  - ../thelounge
  - ../velero-oracle
