apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: karakeep-secret
    namespace: karakeep
stringData:
    meilisearch_master_key: ENC[AES256_GCM,data:qbEUnMIbQT1MCaEQFur+xArvokS1zS3d3ik/6uBJpHmDMpulLqlXv0lah3QGZyaUfObcJnVhrJuHtuKwwxmL59YhNNs66md7hH7xTg==,iv:a9rKJbK5lA+nb9f7IyKPJ4lXbKe0QS1Gi5AHs5+QRuE=,tag:Gdc3xwLGIhnpTiQHaZmCTg==,type:str]
    encryption_key: ENC[AES256_GCM,data:QNCATQOSeb2tfzGP5IzbSPIYG/09ycsLOHBLlAG9hxaBHsz0UMfnT6ky6sxl0C8nLIPDf5fHKIehcex47m0btbsnOLIJdxrlE3T2bw==,iv:cqj/NevFG4SWcFxwsNFBlDsT1qFFXvuDwJ+3ft1i83E=,tag:RB97QH5/46aCTz289cT3lg==,type:str]
    openrouter_api_key: ENC[AES256_GCM,data:vB3IMOagnhsbS4rVLnFqh2b5vlBPtghS4+nDZuEWvBTrCfO+0zodyUOiT6gOk6ri8wSkyJPAxvM4tkm9HPnJ1F5QE5wGuK3bFw==,iv:YPmb2bHVxIr/FUORos3CeKSMobVpkr+CjU+YnmzZxeM=,tag:zZt8EcGi9kbUZ0UP/+oOWg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrTkprM1kyTUk3K0xCbEFS
            NmE0MWNpdDBBcGlxeEdxbWJsQ1RCR0NHaFFJCjByZ0JQUFFRNXY3N1lRN1hTSU0y
            WmFzY3hFZE5nWjc2TGFySzRpNFpLZTAKLS0tIHZjcUxWZkJKNm1sYVV0OWNrd3Zv
            Ykk5MzZhejNFbGNSTzlwMExyYlRmZTQKMzZ9Pp5nlntnJEvTuocqZLuulSoF4WpU
            SxgcsUU/Uu7YVh5RuPIkE2ScN1WGyMPFCSQiYeTLMvpx+PtJORXJnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T13:48:34Z"
    mac: ENC[AES256_GCM,data:w4mXSLi2dMn7Wsvq4ifWhFtJywhRY8FmmtCE8h3vtAcyDljqkPvluEnxtsZ/axfrlurYJGhMeIsJUoNPe/d+eDNAv400JUy4nSNgahV2kOImGZJ5k0wRVNaMc83zhNOdebZNxWgFIlWlEK61yF+Tog/5ycz8H6ZCx62KvJvhCSM=,iv:gX+Fl5Xnidv6QeRL9tNOiIKTZION2KRfObCAB0cOFd0=,tag:cIWGgIg6e60j8truRF3ruA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
