apiVersion: v1
kind: Secret
metadata:
    name: lidarr-basic-auth
    namespace: media
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:vBaJ11jr,iv:jQCBdFRDgeihkqfyGVSRphKQY4iF4DnLXjEhPTx59ZE=,tag:td8hQoDc1hlqBaWhggOSxw==,type:str]
    password: ENC[AES256_GCM,data:zc6dF2GJzPsitNTmGA3WU+2EZwMulPmG9vLrDURdYQNyQxMxZwalwQ77y/vxxU2+KVCeUPcWsDGiUT97lsJOew==,iv:R5GlFw0Ax4vjkPeJUUOPsQdJWx/BXrKHDLcBLeBYaOY=,tag:KpL/XrkumU/LivaEYlsAJQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBSFBGR09kTlVrMWhKSzFE
            N0g2N2N5VDEyWHcyS29BN1JqMjJIVGZiZGhFCnJDUG5jRlJaVkZyNXpXU1JmQ3ZQ
            RG1Ld3BBOUpZUFlvNTM4cnVvdGxsNTAKLS0tIGo1NmJpNnFKL3BGbjhGQ0hnWkF3
            eEYrRWRxZ0JvU3pMdGgvMXc1WitSejAKjb5wwUrSy79EO969ptIqDefdRpizyRjw
            SSD0/QZniXAAVxs7iU9Ye0QHWQK/4n2i8Fnwcph8Z9vuDuLmftQ+wQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T11:51:19Z"
    mac: ENC[AES256_GCM,data:BsO6edi2EjIZQZPWCynzis6yL7hp+HwlbPkj+Mad+YqFxm3UQioNB8pyLhGjr7iGRw6Sy1ZGWCIdXzDcpB0r6vwT5wZksPmMaLtwvT8ukZRkC7zinOVpqX57fvqi4PmPCLsEsrA8kujwOdpTxnfGzMvWy840mDsTeLxE08QVYYs=,iv:Xw7Lx9GlD9dQEfD96RE79AAflAjfLxCZejDZI0jrIDY=,tag:uaC8aTcCh9lot20YUL+n8Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: lidarr-postgres-v18
    namespace: media
type: Opaque
stringData:
    s3-access-key: ENC[AES256_GCM,data:ZxXQZLx2C2GJnvqRaeHbTqKB0mw=,iv:9fz3bDyJmb97ajYr3PdXshp7j5dbyiE3S4zv3TTTqtA=,tag:yyjQ2ZB/c6om46wGdXdn3g==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:wE2hMpCVcTEG+oG+N2TfxHVoQRRmpWAtAFA/AfIpmVfh5iJ5EMhr6Q==,iv:8hkgIy8q/athw2lcVOrjLPj/1Vu82B9x0ox1Mrm8Wq4=,tag:madRVC2p4uzvMQ9AJnhMIA==,type:str]
    password: ENC[AES256_GCM,data:K8LijPGN5eqp4iQOwnRCFUSTxgP5jZn1sw/Qu3hxFhiw/b32Zfxx0gBZOogHavOE1j12gJqdCmBvQym3+ADd+Q==,iv:XQCN2yygevi7GP7PpfCY1ixYXa24h6QfzmKy8zU8z4Y=,tag:KofPU+cfZpKjhpERjwc7RA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBSFBGR09kTlVrMWhKSzFE
            N0g2N2N5VDEyWHcyS29BN1JqMjJIVGZiZGhFCnJDUG5jRlJaVkZyNXpXU1JmQ3ZQ
            RG1Ld3BBOUpZUFlvNTM4cnVvdGxsNTAKLS0tIGo1NmJpNnFKL3BGbjhGQ0hnWkF3
            eEYrRWRxZ0JvU3pMdGgvMXc1WitSejAKjb5wwUrSy79EO969ptIqDefdRpizyRjw
            SSD0/QZniXAAVxs7iU9Ye0QHWQK/4n2i8Fnwcph8Z9vuDuLmftQ+wQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T11:51:19Z"
    mac: ENC[AES256_GCM,data:BsO6edi2EjIZQZPWCynzis6yL7hp+HwlbPkj+Mad+YqFxm3UQioNB8pyLhGjr7iGRw6Sy1ZGWCIdXzDcpB0r6vwT5wZksPmMaLtwvT8ukZRkC7zinOVpqX57fvqi4PmPCLsEsrA8kujwOdpTxnfGzMvWy840mDsTeLxE08QVYYs=,iv:Xw7Lx9GlD9dQEfD96RE79AAflAjfLxCZejDZI0jrIDY=,tag:uaC8aTcCh9lot20YUL+n8Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
