apiVersion: v1
kind: Secret
metadata:
    name: lidarr-basic-auth
    namespace: media
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:Xp/QhvKk,iv:xUUjLzHR42Zslti5z8wuG/aFnzZ0wuxXlkea2gwZs1Q=,tag:yvGS6AU3ct8Uk5DSxIP8aQ==,type:str]
    password: ENC[AES256_GCM,data:0/svErHXScM8FCkjj9sdLog8FRCyzuIqYaW7zHLw50SwukeFgmuKzPMqof+cdZlnY6eHAfETNgzX5QcH0Iq55g==,iv:B4UFyuSYESWfQA/zlLM9w8uOdMb/BFeKfiGrEKoQPCQ=,tag:D5fOM2iYzfq766Kqyepugg==,type:str]
sops:
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuOUR2cXRVYWFlTGErbllJ
            enhyQkMrNDh1NTZqOEgrWk45Y3dXa2gvSzFJCkZMRzllVUltTTdZRGl6QWg0Tnd1
            ZC9HY2VPbElxUzlnZ1pDQ3FMMTdHMmsKLS0tIER3elJYK2RvazZVT045WWYvSytU
            dHNvNDJGeDJ3OWhNRjI4VVg5Tm54VEkKSQ7VOMJoiHkwA/IK4+ViBehpk3ptWXxY
            yyqU4fcXRdbJeRRkpcKDBVBIh3GClZXadY5kKuOUY0g+YbGWTRHDDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-17T21:13:17Z"
    mac: ENC[AES256_GCM,data:e3eT5SKpc4YvRf4abE2twXAAXY8RAsmu0f43auX8Xd7qxwIfv9jzO2+SopiyFXmKbIX+qvXS+NJUXgfgR3ZA1MgzJI3JEqZi7X/cNVqed0P50LjRKEbPt5LxvEgqqYupJyFEX021yoNKoDwTBRg8LWWFVoKbI4SswGZYXsyUUKk=,iv:nWTpV5iwt52FvvptSlAhWYv65WGX6S03/j28DtgYvTc=,tag:HKV2RXGuu+V80b+2wbEebg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: lidarr-postgres-v18
    namespace: media
type: Opaque
stringData:
    s3-access-key: ENC[AES256_GCM,data:1ddH8ofwyL6nRqcPLQdhVDv+NKJ+gRetKJw=,iv:x3U7blAfEgaVSFdpZFoUYdkcjA0Odq3vzc4Hjg8KsT8=,tag:z13c+GN3ReFo9vFhXGLJLw==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:yWEo5rq8OL9PcIBarTGC2WY4ovlLG7uJZi1ct0yicpXgLsONOzBrAEojF8SnXjT9exDgAk9UuGmv6LrFlEJjGg==,iv:LCT0Zne993nynuvLITrfMpHhSlcgx8g+Y7LDmC4qKRY=,tag:NJwdwZcK/ckpMkI9neQSsw==,type:str]
    region: ENC[AES256_GCM,data:rVAA6NzX,iv:jXgb9y39QiqBwg4t7j6tnBc+vp6kXoazLdNK7Oxc/Pk=,tag:DOV7VPJRC9HE85J0vHURYQ==,type:str]
    password: ENC[AES256_GCM,data:fYVXG6E2dMOwf5Otl7FM2R14XEb+2Kv3WNBk6fcZYKnSC0bnW+w5A3Jqs6SXqsqaU/QMTJ16RLCusmbTnf344Q==,iv:y7s9ofutJrvfmUuHG1hp6ZnqvW/p6xgBiSiT9pROS/s=,tag:iwQn1wv0jmA7TNv+DRu5Gg==,type:str]
sops:
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuOUR2cXRVYWFlTGErbllJ
            enhyQkMrNDh1NTZqOEgrWk45Y3dXa2gvSzFJCkZMRzllVUltTTdZRGl6QWg0Tnd1
            ZC9HY2VPbElxUzlnZ1pDQ3FMMTdHMmsKLS0tIER3elJYK2RvazZVT045WWYvSytU
            dHNvNDJGeDJ3OWhNRjI4VVg5Tm54VEkKSQ7VOMJoiHkwA/IK4+ViBehpk3ptWXxY
            yyqU4fcXRdbJeRRkpcKDBVBIh3GClZXadY5kKuOUY0g+YbGWTRHDDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-17T21:13:17Z"
    mac: ENC[AES256_GCM,data:e3eT5SKpc4YvRf4abE2twXAAXY8RAsmu0f43auX8Xd7qxwIfv9jzO2+SopiyFXmKbIX+qvXS+NJUXgfgR3ZA1MgzJI3JEqZi7X/cNVqed0P50LjRKEbPt5LxvEgqqYupJyFEX021yoNKoDwTBRg8LWWFVoKbI4SswGZYXsyUUKk=,iv:nWTpV5iwt52FvvptSlAhWYv65WGX6S03/j28DtgYvTc=,tag:HKV2RXGuu+V80b+2wbEebg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
