---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../botkube
  - ../cert-manager
  - ../chatbot-ui
  - ../cloudnative-pg
  - ../cloudnative-pg/cluster-16-oracle
  - ../haproxy/haproxy-ingress-daemonset
  - ../invidious
  - ../it-tools
  - ../kuma
  - ../local-path-provisioner
  - ../librespeed
  - ../metrics-server
  - ../reflector
  - ../reloader
  - ../searxng
  - ../snowflake
  - ../thelounge
