apiVersion: v1
kind: Secret
metadata:
    name: sonarr-basic-auth
    namespace: media
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:NEVBslOy,iv:UGnBlMnH54ofj3V10K4Y3zgJNkdEnRCEYCdBtNA4mLw=,tag:iV0EVYMTm6qDdYLmrlJYFA==,type:str]
    password: ENC[AES256_GCM,data:Ztwg8Q+B3Z7cdtfcZCP7Sd5qWyrJoHWeDHduP0zXc4mDgkHQVGj55j2Ql4M6Sw1VW+oSKg9ahdvOkvvzKAxk6w==,iv:F+Ssn0FTGayGEM8q2UyUaxFW3n4OL5INKwUIey8Ccwg=,tag:NunrAzG4KBir5dAJL7T9tA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3QW5MOGdXZEJ2Nit5Ykhy
            MVJHQmVQVmwzcHNZWVI4bHBmSlpaUm9LRnk0CldJc05jQzJLbVZEdEtLZkFhQmxJ
            cUVaNERKemg4cm5vV2xtRUpQOXliUHcKLS0tIEJTS0pUY2FLV2NVOEZnMmY2d3Zk
            M1VqWVQyU0pPc2szbE81MGZtQ0V6SkkKJz8Yy2UXjgZ0cFez51xLkWc99VnNqbcA
            oRsXcJU0CfVZtng5i8At5q9Zjyy9AHaofcUbu0SjBXYXlZNIFvl5Mw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-01T11:02:14Z"
    mac: ENC[AES256_GCM,data:GS0WaIE6Lh91gziwQThK/bAiczM2NjUu56QkI3KWBQwIHIr5tmgclm4oe4i9XDrDQxGRh15MVnkEQLdWT8b+pD4BkCAtWfDs6NqMhz6yFLrOM6guSlsPSWeIiyPRM1yxIXYmKRpJ4e/Kx/bw/s4VflEAU77OQzD8yb2MHU+Ga5E=,iv:xUUrdhrb8cdXNPpXGmzL44aFwr1RCjhTEEe+swUW08Y=,tag:TnoBUzKPeZ5ofwD1PC32zQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: sonarr-postgres-v18
    namespace: media
type: Opaque
stringData:
    s3-access-key: ENC[AES256_GCM,data:nnG9pxU+OJdkn9psmpI7SFW/tKU=,iv:bcj7Uduq8hHfJNeUUFjIJDnA/3cO2VwTbTrf1WPIDT4=,tag:VZ1M12SzjIrJQt4vC/hltw==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:fTt8BtNNg6wb8m7ZdZ711wCa2/e+IGXk6sENy4fGC4YoF8iKfPSDsQ==,iv:F5MYHzboNYHsCx8u8WU/acqxVhSvYNQXInTcS9XvYGM=,tag:zmIxE+6Jskn6f8/Xf5KY8w==,type:str]
    password: ENC[AES256_GCM,data:pGrOC09iStzrT5yz4jkvqxdb9LPxZu0IK4lfb1zdwREpCKnuc2b2gCrmr8aOfpEV7DzNvwdaCRSAIWT/ziwI2Q==,iv:SFszmIvACuaO74+uEPO1flaBS/4KfSAB0h62GqqxTwE=,tag:rFq61RtXUvFP/EMXVW1l9Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3QW5MOGdXZEJ2Nit5Ykhy
            MVJHQmVQVmwzcHNZWVI4bHBmSlpaUm9LRnk0CldJc05jQzJLbVZEdEtLZkFhQmxJ
            cUVaNERKemg4cm5vV2xtRUpQOXliUHcKLS0tIEJTS0pUY2FLV2NVOEZnMmY2d3Zk
            M1VqWVQyU0pPc2szbE81MGZtQ0V6SkkKJz8Yy2UXjgZ0cFez51xLkWc99VnNqbcA
            oRsXcJU0CfVZtng5i8At5q9Zjyy9AHaofcUbu0SjBXYXlZNIFvl5Mw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-01T11:02:14Z"
    mac: ENC[AES256_GCM,data:GS0WaIE6Lh91gziwQThK/bAiczM2NjUu56QkI3KWBQwIHIr5tmgclm4oe4i9XDrDQxGRh15MVnkEQLdWT8b+pD4BkCAtWfDs6NqMhz6yFLrOM6guSlsPSWeIiyPRM1yxIXYmKRpJ4e/Kx/bw/s4VflEAU77OQzD8yb2MHU+Ga5E=,iv:xUUrdhrb8cdXNPpXGmzL44aFwr1RCjhTEEe+swUW08Y=,tag:TnoBUzKPeZ5ofwD1PC32zQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
