apiVersion: v1
kind: Secret
metadata:
    name: sonarr-basic-auth
    namespace: media
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:D6la6ErP,iv:XStvyd/wE1ryW55CDTEducsZyeNNLMmDo/goyOGQ5vw=,tag:66HiMM+RwXU+3J7AbBhV+g==,type:str]
    password: ENC[AES256_GCM,data:IM+mwRMgOf2zoctWbwsyjhS7LZenElkh6dqxji2gVIlGtN4rgMydHnhvXNxV335x8i3jBv+YlaDCYTOPzMZ2ng==,iv:A/iZGQ216FRn4CXQq1FCihjFC6EEdhR4iSaBuJrt1UU=,tag:fLtUYLOx1BMQ+NSv+uk0zQ==,type:str]
sops:
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvU2hCTmpxSEo4WkRKMW1N
            TU1xSkVmdGZHbk01MGc0SjVlL3ZLOEU4UlZjCktzTVVFV2lyYzQ3QndvZFdkVy85
            M3FSejB4b1NYNjZtYTdCeWQvN2szMEUKLS0tIFA1OHdRNGFoYTlFVElPbXcwRlo0
            NkkwRTAxT1g3ai8yRG44cGdaL3lWcjgK45fWqMhXFUBa6C8cXsphfkMhVWomYBiF
            GramI7Prytxvl711d6AlhguHH+1q4YpBxWfRjwkGMve4El2Whi2M2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-17T21:13:26Z"
    mac: ENC[AES256_GCM,data:bEiTG44aI8uVwFQRmQVEy3yLsrlF7Orsavc0t52cVPYOgJQBiNTMkycYTKM6omxsWsFgr6Rhb4cIkB5uPHs/69eqikkTqUBzqCV9aml4qxOeqNWv+GsTv6D69YSSiTQMTYovzrL5uEfwJGlYrg/t8B8h3iBTM2VekK2tdlRk2Uk=,iv:gpY37+3xjkix5JUUfeAsVw4lmAU44qLlnAiwsjIBoys=,tag:6mcqbsS6ynkpL+lU+1dwkQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: sonarr-postgres-v18
    namespace: media
type: Opaque
stringData:
    s3-access-key: ENC[AES256_GCM,data:1qIaK4IiY/X9Bu+RMsvu2JMdlrqaDYgs3zQ=,iv:7lBw7UbqAj2ZqnrS1ddn4n1PghXsY6xUyVTuFTM/UFA=,tag:k1JqlteXH0Zjs9AvcMoNnA==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:HRuMHQOWxzR1jKLic5KBc71+Pf1UtxGd/THvxppMk7EiWOWIUz+k0raFUdwgfGHYUxpZSyTxLDLMgN8YNCjV4A==,iv:/iEphBPiaUQVNHy/aEfgp/drdiha/ROzg+lb8tnOnyc=,tag:2Ke6vBVWv9zQIZ9LYs01lQ==,type:str]
    region: ENC[AES256_GCM,data:uLfVfkBj,iv:zviPRz8t6ZTt4wuhaXDdwyH4c21BRqGRFAa7ainptl0=,tag:T4GbmPZIVqTnFg/YxYhhMg==,type:str]
    password: ENC[AES256_GCM,data:dXalQxRebCyh36J5m19IRqDj0CM8F3kXhYenZ86uNItmNhqyY2rSiwW6xIX22fpj8J1z+1UC0EqEhECoj+1hBQ==,iv:0dxD1RXUoewT5LS0iRiDBn0970Dm3sR6S4v/DnzUG3g=,tag:gm58E0DoODAKoqIf5yXW3A==,type:str]
sops:
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvU2hCTmpxSEo4WkRKMW1N
            TU1xSkVmdGZHbk01MGc0SjVlL3ZLOEU4UlZjCktzTVVFV2lyYzQ3QndvZFdkVy85
            M3FSejB4b1NYNjZtYTdCeWQvN2szMEUKLS0tIFA1OHdRNGFoYTlFVElPbXcwRlo0
            NkkwRTAxT1g3ai8yRG44cGdaL3lWcjgK45fWqMhXFUBa6C8cXsphfkMhVWomYBiF
            GramI7Prytxvl711d6AlhguHH+1q4YpBxWfRjwkGMve4El2Whi2M2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-17T21:13:26Z"
    mac: ENC[AES256_GCM,data:bEiTG44aI8uVwFQRmQVEy3yLsrlF7Orsavc0t52cVPYOgJQBiNTMkycYTKM6omxsWsFgr6Rhb4cIkB5uPHs/69eqikkTqUBzqCV9aml4qxOeqNWv+GsTv6D69YSSiTQMTYovzrL5uEfwJGlYrg/t8B8h3iBTM2VekK2tdlRk2Uk=,iv:gpY37+3xjkix5JUUfeAsVw4lmAU44qLlnAiwsjIBoys=,tag:6mcqbsS6ynkpL+lU+1dwkQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
