apiVersion: v1
kind: Secret
metadata:
    name: sonarr-basic-auth
    namespace: media
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:OqHzhODv,iv:I6nQDFH5uCWWSxc86IDzrexjokifN92jdr9T62K5tPU=,tag:kfPgJlGsdmrdSbA5gUVtBw==,type:str]
    password: ENC[AES256_GCM,data:H+/AXu+yykEjiaMLNcO1Rt9FIU7RQXwFfcthrHEjw7BKwBU4BpzyLt3aR3JXmdzUwlv/22+7RBwrife0ZqTtQw==,iv:1LlUOXGXNG35OYEC+TYKgtUrpH2y0q9bY1ejw8teSHw=,tag:ZL2T8zZx/z8r/39t/zTCSQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWV1Y0bWJOQWlzNlh3MTZl
            Tmx5QnAzZDUwWElkSm1nSmRsakVKcTNUdGcwCmtaamxWdVROWGlWUjJvcTMvdjcz
            eDhKeVlsWmkrcFlhOUFDVHJwZ3ZDQUkKLS0tIE1hS05wbzQ5TUljTlBtOHJESDJY
            NlQ4WXpCTVVCTWhEMnZGcEdJTGloN28KL8NEP0JRTs8uXK1Hw3a8ozlIQS2ZmYQY
            HB9kpMKwyGpoawP1d55trHpq7djC9/f9UUaFDRDW1e7zKQrDTdEIHQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T12:30:55Z"
    mac: ENC[AES256_GCM,data:TV2W34ouO0qPi0r3732VhlR65NsSJ3BDbKsg9X+c0o9raVgSEBt4jiIcgN9VwXkFdYAdos1dztf5NoKm5SIxx3gQ2G3NFeLHMt1b1phTsc5eurbpaixw0esssJ9aml4wA5dqgTwqWLnpZlh+i828BvzuUUIp/1SZ8/IojK5N06Y=,iv:zTuJEBHLFmY6hXjrtpp53fXA5i0iNJ7Nw9jc7r2kn4M=,tag:0TKOSqS138vkUHghCfF4rA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: sonarr-postgres-v17
    namespace: media
type: Opaque
stringData:
    s3-access-key: ENC[AES256_GCM,data:qc0pMfpvPMB786uP0Rx+4QHKv20=,iv:lQ5eZQ5iez1nXzQ/1H9bTEt92MUvKNlSnUWXVO71ftU=,tag:u5HDwvM5xL8NFD88VQxbHw==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:pQnc/vbUsHbNK5kNaoFhpqgizYWBanpJ5fv7DnS9PiL2X3R4Z24mdQ==,iv:21PMEESAr7kiRGHiqckVmdrq7VquYAR+SxegqPojwzM=,tag:87hpXLKXNqPKB0yaMdbRBA==,type:str]
    password: ENC[AES256_GCM,data:AB67WcQ8RtmVR/7399plqqsFPdje5rzTQGzt41qw601j6VSZk6vVlSPDHb2w51X4mg2HGSsmLc4T2NaEQEPjXQ==,iv:2uH9adV97H8mEit+lrIM6nnrDGI65uoMFG0L+KBchFc=,tag:f/nQr3LdyWGvIXU9MloL1w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWV1Y0bWJOQWlzNlh3MTZl
            Tmx5QnAzZDUwWElkSm1nSmRsakVKcTNUdGcwCmtaamxWdVROWGlWUjJvcTMvdjcz
            eDhKeVlsWmkrcFlhOUFDVHJwZ3ZDQUkKLS0tIE1hS05wbzQ5TUljTlBtOHJESDJY
            NlQ4WXpCTVVCTWhEMnZGcEdJTGloN28KL8NEP0JRTs8uXK1Hw3a8ozlIQS2ZmYQY
            HB9kpMKwyGpoawP1d55trHpq7djC9/f9UUaFDRDW1e7zKQrDTdEIHQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T12:30:55Z"
    mac: ENC[AES256_GCM,data:TV2W34ouO0qPi0r3732VhlR65NsSJ3BDbKsg9X+c0o9raVgSEBt4jiIcgN9VwXkFdYAdos1dztf5NoKm5SIxx3gQ2G3NFeLHMt1b1phTsc5eurbpaixw0esssJ9aml4wA5dqgTwqWLnpZlh+i828BvzuUUIp/1SZ8/IojK5N06Y=,iv:zTuJEBHLFmY6hXjrtpp53fXA5i0iNJ7Nw9jc7r2kn4M=,tag:0TKOSqS138vkUHghCfF4rA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
