apiVersion: v1
kind: Secret
metadata:
    name: readarr-basic-auth
    namespace: media
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:Tj+IJIfb4w==,iv:wccO/SY3fz39BjaeQXvndrcimhcF77yNJadv07IJGXk=,tag:mcNHhzhSVulwcyZKe9oS4w==,type:str]
    password: ENC[AES256_GCM,data:4JUuluBv1C9EvP2RTJY3z+4couRf9GL9t37bDpAlVRXQfkE2oVYnjIVOafF8W5GCHRPNpCU6/vln5/hvDHYUPg==,iv:HQKYrhH29ZyQgfRhlZDRT0xzLUNiBmxLaCYiaUJLu4M=,tag:K1Sv3RpDbSzjcd02DboAFg==,type:str]
sops:
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCWUc2UnpTVzY1dXoyZy9y
            V2Z1Snc2ZEJUVGMwTEU5bnh2czdYRUJBSG1ZCmx1TWxQY0dqcUJRWk5lSk9GT1o3
            MU9aRXJuREU1R2lDVlp1ekNVTXNRb0EKLS0tIGp6WDJmUFdBTEdSUnlVVEpncUww
            UVVmU1greVh1ZVl6QW9HRWFmbXJWbkkKhy69ZMZoX3RcMDboiw7wbTx0qeKW22X7
            VoFAKJsyRj37CAJCnAY2y4jPMEY28O63EJqLtjqDb7s+aGRKpDaBDA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-17T21:13:20Z"
    mac: ENC[AES256_GCM,data:dVqiaX77qbnzQaqAep++vPZ5sID5zcFVU79YnslUjmvRgSUy87/u3HEvCAaQT7a92sESsPxnqqZs6fG5o0tj4fxGL/w5PtE47SRa204CZ7j3RFhK+HWfEbPNV0BKiT7ZmOITryP+ej2mds55fQWluDb3aIvqL1zrvuL2wFkF170=,iv:cS5B9LLwstOcDQFBl/9xV2gg1QtIIOfiXHQFELZQOKA=,tag:n0Frq3ohoRniJ8h/X+aWuQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: readarr-postgres-v18
    namespace: media
type: Opaque
stringData:
    s3-access-key: ENC[AES256_GCM,data:HsEpiWkpwknZderoHID9dDu3wsLzX30vvU0=,iv:NmjI7gxp+Wc+xu1YRZYu4JayLKr9jvmAogSfiDqZmxA=,tag:IYRC0FHHEHrfOcnWUZ+dCA==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:pfoPJA7KLZx3p+s9IopIJbHL4i25vhcbcVx8ISqzpu5XVdBfjP0Y0TuscYCF0/OvNz+yazXyPvPBCUCKwP77aA==,iv:Z3S+7pg8C8rxnz797+6zX0Ln5REcO24DOlp3xExoZhc=,tag:FWN0TB5WRALhkEuGr/s+iw==,type:str]
    region: ENC[AES256_GCM,data:vHfDCsM6,iv:KFh5tHNmz2JRdrWSbt1kCBx1AQtPHfiR1nbg2Wn76AA=,tag:dmQGApf7n1errQ7RVpZ9Uw==,type:str]
    password: ENC[AES256_GCM,data:I9zb8jqWvN5n6XrdIFenOT4/GIq3KWz++g7w4f8IZHfqwIxUA3LmoYU+Wv6fMa6b5rLJbk8xU0ckg9FFRfxGsg==,iv:3MDAl3V2rZb0k29ywOFzt6QYinoTVXF3l9188uI6eyM=,tag:pJpT0d9sa2KeXz7UofWOww==,type:str]
sops:
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCWUc2UnpTVzY1dXoyZy9y
            V2Z1Snc2ZEJUVGMwTEU5bnh2czdYRUJBSG1ZCmx1TWxQY0dqcUJRWk5lSk9GT1o3
            MU9aRXJuREU1R2lDVlp1ekNVTXNRb0EKLS0tIGp6WDJmUFdBTEdSUnlVVEpncUww
            UVVmU1greVh1ZVl6QW9HRWFmbXJWbkkKhy69ZMZoX3RcMDboiw7wbTx0qeKW22X7
            VoFAKJsyRj37CAJCnAY2y4jPMEY28O63EJqLtjqDb7s+aGRKpDaBDA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-17T21:13:20Z"
    mac: ENC[AES256_GCM,data:dVqiaX77qbnzQaqAep++vPZ5sID5zcFVU79YnslUjmvRgSUy87/u3HEvCAaQT7a92sESsPxnqqZs6fG5o0tj4fxGL/w5PtE47SRa204CZ7j3RFhK+HWfEbPNV0BKiT7ZmOITryP+ej2mds55fQWluDb3aIvqL1zrvuL2wFkF170=,iv:cS5B9LLwstOcDQFBl/9xV2gg1QtIIOfiXHQFELZQOKA=,tag:n0Frq3ohoRniJ8h/X+aWuQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
