apiVersion: v1
kind: Secret
metadata:
    name: readarr-basic-auth
    namespace: media
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:8Or9G3s+sQ==,iv:21rmXrLSiK9WvKrcRRbEShDDunNTKaYlASQA8OvfPH8=,tag:8gQi23AYDnysDZeduF7HWA==,type:str]
    password: ENC[AES256_GCM,data:alABCQzv2LzHXC+6Ef8tZlUFeJVurkDmPa0lyYfJ6z6sLoxpCKj/5yEtDk3XQYifhjiBo7FNZ2kLyvoRIyQ4Mw==,iv:rgVkZ8rkhgesBVhYs7wTluRv8ARgclVHfIfpNoy7e4o=,tag:wjFLOk43CPT2RfuLoftO/A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFQ3ZScnY3THB5Wi9ZaS80
            K3poZHNiNEtQOVBHRjlZUE4vVVhIOURLenhzCjl4cEtFZlJUaVk2U3BZTURTWnRS
            bzRZK0lwc1hyWmJUazZtYUw1ekpBdjAKLS0tIFI5T0lwaS9jL0FEQXU4dzdPWGpY
            VzFrdzNyMkJLQUd2a2tBR2dELzlWcDAKM7irJwrQbto2rmu64J6jAuTcfI1n/mE1
            8OhC2hjoFBCc6ZuGVQeewEhG7mhfbFT5DCCiiwoWtsrRlPKPvk2czw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T11:31:47Z"
    mac: ENC[AES256_GCM,data:5G2zYDO4Wxg3tySfMwgiUD5uGnl843T7pUx27rHQtCxQTDTjewZ2bmCEpQwftuuZ1xsP/weYeU6pIbzo98kOQWpkUqWcd6VSyUuPEB5O+6KUFkIfYOFY7VRFajPofVy1MAovmbyUEevoJoPVo0z+fY/HxB73tkhOUvmqPUOc72A=,iv:ZbfznF23djpyKPhtgHEkZzJSB25Li+ixUHFokrfjV/s=,tag:c6m8rdGSi8qSPsiC6roD6g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: readarr-postgres-v18
    namespace: media
type: Opaque
stringData:
    s3-access-key: ENC[AES256_GCM,data:81mZffc0Ns6BOMo8teodkbas5Dw=,iv:DEjh31cRZae0BmKgDCezyymUxBxSoskkix5PYP0jK6c=,tag:LqGEznJQuUaKTmGdUpOrsw==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:v6aZRl8vq8vE5ttaTZsejqJOhfSpM4BQmajXl+0yfwAj0kh5ybRQKA==,iv:kOqJFJyWfQrlVE5ixh1/nqtQhBHJEArS8p3vY/A6z94=,tag:xToHP5rG80b1yodtbNF3qg==,type:str]
    password: ENC[AES256_GCM,data:LIi1fldJcplQp48Q4+DdaHdGNXDixzHHY4Ws0fXHCvKx0xHC1nbWTVfkRQHjJP4b+nEkthGip3JLXCcUMQhweA==,iv:MVL46oTMHhxW3rrvPhOc4upqMJBB+M6v04b6aQYpP2E=,tag:MGkmfF0cUTHcsZM1wDG5uw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFQ3ZScnY3THB5Wi9ZaS80
            K3poZHNiNEtQOVBHRjlZUE4vVVhIOURLenhzCjl4cEtFZlJUaVk2U3BZTURTWnRS
            bzRZK0lwc1hyWmJUazZtYUw1ekpBdjAKLS0tIFI5T0lwaS9jL0FEQXU4dzdPWGpY
            VzFrdzNyMkJLQUd2a2tBR2dELzlWcDAKM7irJwrQbto2rmu64J6jAuTcfI1n/mE1
            8OhC2hjoFBCc6ZuGVQeewEhG7mhfbFT5DCCiiwoWtsrRlPKPvk2czw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T11:31:47Z"
    mac: ENC[AES256_GCM,data:5G2zYDO4Wxg3tySfMwgiUD5uGnl843T7pUx27rHQtCxQTDTjewZ2bmCEpQwftuuZ1xsP/weYeU6pIbzo98kOQWpkUqWcd6VSyUuPEB5O+6KUFkIfYOFY7VRFajPofVy1MAovmbyUEevoJoPVo0z+fY/HxB73tkhOUvmqPUOc72A=,iv:ZbfznF23djpyKPhtgHEkZzJSB25Li+ixUHFokrfjV/s=,tag:c6m8rdGSi8qSPsiC6roD6g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
