apiVersion: v1
kind: Secret
metadata:
    name: readarr-basic-auth
    namespace: media
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:0+qUk69pQg==,iv:v0Y+G4pgfQq4VNUUeuOBnravnnRQPfEKOMaeZGeq8Sw=,tag:qQbpWfSu+Mkv+96PP3xs/g==,type:str]
    password: ENC[AES256_GCM,data:RbpuuBqRHjtj5/D5TOzvej9AEA+OxPQAa+dNgxMklBJaUUGfXxvZ7fUa8oItN9Xxi44QeURCSiohcRibsh8bSQ==,iv:BqB/uKpOj6VBQghviYeWF6lgQ/+jXApeHY98SswltTk=,tag:LUA2Al2EUe6Fx+fEMS9kpg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxaElIK2FySDhScG56NWls
            bVh6YUJPbHJhUEphOFY4WlVYeTdodExsSEE0CkNzMElHN0o2bHZ0am1QVFFjb042
            cWJmQll0UnB2TlVSMWdCaVhXL1ZJZG8KLS0tIE8rMFAyRkV0QXhiQmx4QXZzUjY1
            bXdNNVFmNFQzTGVESUV5aUpyMExPVDAKPExv3Mo0yDR6yD8qtsxPT5GltrDwzBM9
            gEZEsEWRRAostQFb6LgBNh6PNKoYg36WfmmAFqCO6n3F1xSEfQgAWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T01:44:59Z"
    mac: ENC[AES256_GCM,data:fmJZ7ZkSBlo2cAwuQDigr5zga448PDsUwvzbxOhBMJCUwE8SyKWNkac79JvJxGQUvfT2YAFLjfXGDHdnVO7yi1ghjxV3QmPIpVvr/C+o0LC7AaQEXXIeXynNyEAftj3HHdOaOLwSmJ/gruDux143rkigIxUh1/tFVt4qUmgvPAQ=,iv:c7dHNo8dxEKY+8J6TKGQNBzd07atSLkmQheST9z03pY=,tag:ig5tj9PY9yhk6zZMY/PEZA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: readarr-postgres-v17
    namespace: media
type: Opaque
stringData:
    s3-access-key: ENC[AES256_GCM,data:H/OWtgx80Bi5oFBp7QeKXhgI3qo=,iv:wRDWr3ZvWaI+kts7HDkqYasruTEWJEeoFeO+hSqNq98=,tag:ycGxZjNK1zQUMnE+YqROBw==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:1Z2nKvfahp6Xa3efuVQpKqnzNSxMzx01tXuGvocHXykhfqXFTav9gw==,iv:5hMpwOokoeP8VYSWdv9JcZ6pFxS2CWwfGi37dumABhQ=,tag:kLQSPhULPbXId8euHSPq9A==,type:str]
    password: ENC[AES256_GCM,data:3bG7xzNB1fpONiGNk14RmJB4LzRTDmDGz7j6gzKj6znh/Xwx0Zo3BgdaRvmRS0jjOA14af++70Z+/IGhVC1Kqw==,iv:g39xPaDEFR89LbI3EEMCJGR+2igH8z6nbfB4HErwWyQ=,tag:3827sgzwyAm9LYjpQaPONQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxaElIK2FySDhScG56NWls
            bVh6YUJPbHJhUEphOFY4WlVYeTdodExsSEE0CkNzMElHN0o2bHZ0am1QVFFjb042
            cWJmQll0UnB2TlVSMWdCaVhXL1ZJZG8KLS0tIE8rMFAyRkV0QXhiQmx4QXZzUjY1
            bXdNNVFmNFQzTGVESUV5aUpyMExPVDAKPExv3Mo0yDR6yD8qtsxPT5GltrDwzBM9
            gEZEsEWRRAostQFb6LgBNh6PNKoYg36WfmmAFqCO6n3F1xSEfQgAWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T01:44:59Z"
    mac: ENC[AES256_GCM,data:fmJZ7ZkSBlo2cAwuQDigr5zga448PDsUwvzbxOhBMJCUwE8SyKWNkac79JvJxGQUvfT2YAFLjfXGDHdnVO7yi1ghjxV3QmPIpVvr/C+o0LC7AaQEXXIeXynNyEAftj3HHdOaOLwSmJ/gruDux143rkigIxUh1/tFVt4qUmgvPAQ=,iv:c7dHNo8dxEKY+8J6TKGQNBzd07atSLkmQheST9z03pY=,tag:ig5tj9PY9yhk6zZMY/PEZA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: readarr-postgres-v18
    namespace: media
type: Opaque
stringData:
    s3-access-key: ENC[AES256_GCM,data:26lSbcj52XfcoqB9sVl/7jy+oi4=,iv:kZu02Z3MxuiNbV9sQAJNvF9hOqvWXtT6hwtF0bbGmEM=,tag:vUTJB2aILMZoLm3idrJoVw==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:9EFlO0TKJ5VOrIbNYHjII0TgxhzUeeElxW53sdUp8PGoPBHvW6923Q==,iv:xp6NIp+pgjDJEJfP6Zzvv2LJzJipyI0s85dNYn/Balk=,tag:ZeKf+a/5oKOHlnhk+iXVXw==,type:str]
    password: ENC[AES256_GCM,data:siZquEr8lbiARyjTzae9cKCp3y5qG6zZRpMT+Vx78ADlvAV57a57MHYlGyyxjrPyvgyHlt5NNRe2FExg5FmZhA==,iv:9ZPryd5U/vQ7yNlnU1cs6GO1cxES43ffeYq69Pn8znw=,tag:aDbM3WFKZkfHbuZ/uX/oug==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxaElIK2FySDhScG56NWls
            bVh6YUJPbHJhUEphOFY4WlVYeTdodExsSEE0CkNzMElHN0o2bHZ0am1QVFFjb042
            cWJmQll0UnB2TlVSMWdCaVhXL1ZJZG8KLS0tIE8rMFAyRkV0QXhiQmx4QXZzUjY1
            bXdNNVFmNFQzTGVESUV5aUpyMExPVDAKPExv3Mo0yDR6yD8qtsxPT5GltrDwzBM9
            gEZEsEWRRAostQFb6LgBNh6PNKoYg36WfmmAFqCO6n3F1xSEfQgAWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T01:44:59Z"
    mac: ENC[AES256_GCM,data:fmJZ7ZkSBlo2cAwuQDigr5zga448PDsUwvzbxOhBMJCUwE8SyKWNkac79JvJxGQUvfT2YAFLjfXGDHdnVO7yi1ghjxV3QmPIpVvr/C+o0LC7AaQEXXIeXynNyEAftj3HHdOaOLwSmJ/gruDux143rkigIxUh1/tFVt4qUmgvPAQ=,iv:c7dHNo8dxEKY+8J6TKGQNBzd07atSLkmQheST9z03pY=,tag:ig5tj9PY9yhk6zZMY/PEZA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
