---
- hosts: ExternalBackup

  roles:
  - apt
  - apparmor
  - kernel_hardening
  - profile
  - sshd
  - lvm2
  - node_exporter
  - nullmailer
  - power_mgmt
  - mdadm
  - docker_io
  - docker_compose
    #  - adguard_compose
    #  - certbot
    #  - haproxy
    #  - photoprism
    #  - smartd
    #  - samba
    #  - tailscale
    #  - watchtower
    #  - zfsonlinux
  - users
