---
- hosts: local_workstation

  roles:
    - apt
    - users
    - locale
    - nullmailer
    - profile
    - rclone
    - rsync
    - debian_desktop
    - kubernetes_tools
    - yt-dlp
    - sshd
    - zfs-dkms
