---
- hosts: remote_workstation

  roles:
    - apt
    - users
    - locale
    - node_exporter
    - nullmailer
    - profile
    - rclone
    - rsync
    - local_backup
    - local_dnsmasq
    - debian_desktop
    - kubernetes_tools
    - yt-dlp
    - sshd
    - wireguard
    - zfs-dkms
