apiVersion: v1
kind: Secret
metadata:
    name: rreading-glasses-basic-auth
    namespace: media
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:/X3rOAGnL9FjJQjdRBjXXQ==,iv:VzTLprmdvVoQ/eVjNwg1TOVhvwGQkYfmj8hBoLvJOt8=,tag:W6a7pL3vRT0npVR/vvUSow==,type:str]
    password: ENC[AES256_GCM,data:tlhft5kDbjmhhBZam4sFoloR/nf/2U1/4SdUb/zi0GgntwGEqQ0P7WEymve1g9CgFOTBQZki5TvTS/My222qBw==,iv:munoDHDSeZRDKl7anax1QwSmhKv+Hu36n9laY8Jnmuw=,tag:/qk92zTudKJOpNzZ6iZ8HQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmazhSUTg3U0d6MEc2YVJj
            R09HUG96bi9YOVdhZ0FyaDIwcjVXaHJ3WTNnClhyOXBoVVhkOWM0SG5lbXZxSnVO
            Mlh1Z29CQ2JHNExnMVZTdnJta0szdG8KLS0tIDZBQnEzWnAyTXVkYXNFL0ZzdXNM
            dkxhNGNIZlVGSUsrU2g4WTgvTWhZLzgK7xTxU4fNaw3wEEZ61e9bIJJXgo2j8ikn
            w1q76YnsJ6d/cG/X/7DiVyxuCRauBWLbXZtOnZr8Z/+iEz7arQCCmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-21T22:57:24Z"
    mac: ENC[AES256_GCM,data:7hjwgfuZwawyShdrik427g6b9Z9XiBiPCl1oT+0GyTIqT+INLs2MN2kQ4SDugOwGQrXmJLzmoXraUMFehipn+ahMhuFfg6KzrTKeabuaEJpfvPbu04JRioX7evfY0wOxuhzaBeAwItcXOCKcpE1IsqGl/GG3F3HUbKTjS/GhiWQ=,iv:ElZq6S0VOvSz1n+q5FGLgkwmKY/eqymGhmju/ZvHqqE=,tag:PNiZhC10Qvz5q1ecDafnwA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: rreading-glasses-postgres-v18
    namespace: media
type: Opaque
stringData:
    s3-access-key: ENC[AES256_GCM,data:MdczQ9neNM3m1J4UflDZ7m+UCE9BybQWdwE=,iv:QvQbIw5apqNqYIGa2zSlyf769tgS+LQmL2LXsY8PBdI=,tag:bKtugwOKDEJj0hdkpwntDw==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:TCJPYPA0ewN9cdnA3EvNjs+qjYZaOvzi30FXJjc/U/fxdSQvxhLy3nZVEn8qmjWBbbKMAdJwI1OGH5CPx4g1/g==,iv:o5rJL6Kwhk2KMh6BQGy9KPenj8ePyshP5RRrhnXk7mg=,tag:qtbdKKqc7zyeltmaLroEdA==,type:str]
    password: ENC[AES256_GCM,data:8dmy7K6AlEP/oS69aHXO1h1oZwDYZ0i6AqSdtAUP6klw3ygo5P4iAu3DTZjX4ubYyj01wkBg0L14PwK3DSoWZw==,iv:dCMq8WQHrTDt0gqF6106s0+Ykaw4hNuziqtxmwVWu8g=,tag:JkznnwhZAOIyknrrW1TF7A==,type:str]
    region: ENC[AES256_GCM,data:zyl8SxeR,iv:Kj1RaebEfiKW1onyc45dHjZBH4kozFp6//9KnjrqfqU=,tag:x8imYId2yeGDeuZjjpyGdw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmazhSUTg3U0d6MEc2YVJj
            R09HUG96bi9YOVdhZ0FyaDIwcjVXaHJ3WTNnClhyOXBoVVhkOWM0SG5lbXZxSnVO
            Mlh1Z29CQ2JHNExnMVZTdnJta0szdG8KLS0tIDZBQnEzWnAyTXVkYXNFL0ZzdXNM
            dkxhNGNIZlVGSUsrU2g4WTgvTWhZLzgK7xTxU4fNaw3wEEZ61e9bIJJXgo2j8ikn
            w1q76YnsJ6d/cG/X/7DiVyxuCRauBWLbXZtOnZr8Z/+iEz7arQCCmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-21T22:57:24Z"
    mac: ENC[AES256_GCM,data:7hjwgfuZwawyShdrik427g6b9Z9XiBiPCl1oT+0GyTIqT+INLs2MN2kQ4SDugOwGQrXmJLzmoXraUMFehipn+ahMhuFfg6KzrTKeabuaEJpfvPbu04JRioX7evfY0wOxuhzaBeAwItcXOCKcpE1IsqGl/GG3F3HUbKTjS/GhiWQ=,iv:ElZq6S0VOvSz1n+q5FGLgkwmKY/eqymGhmju/ZvHqqE=,tag:PNiZhC10Qvz5q1ecDafnwA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
