apiVersion: v1
kind: Secret
metadata:
    name: readmeabook-basic-auth
    namespace: media
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:B/vQzuPZcw9q79s=,iv:vKuY9Y2kp/4aUFM7cx/aKTT6+A4xlQXU/a5yAWvcNbc=,tag:ZPIQ029JXCMzfXyr8X1bpg==,type:str]
    password: ENC[AES256_GCM,data:EAZ+bEab+FucqOU100JNmFFhYhDHcoVHoj20HM46frfkLNWzIWzLqB9nBX0kJdtdw0u5VzJNJFJ+sqk2cOazwg==,iv:srJJy2t5T4EW/Tz5+r/KN6aPrbgttpvreZzXaOMFu+4=,tag:kX8JK1kln57x16I0XOVKlw==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:YBEg4zqCQbo0mR6N4rLCYZ0kHZCTUSz0lQDU5csowV24jYUkZtgbaQ0rRDRKh38CoFg0l025YyNkeOLnGgQvBISPpyPQ1bC8hlpneciVMy/aU6ItOu0DNBquIndvSmG6Gyo1UTAg8PaGaSRVyv2FWwoVyy/5V61L/BBlFI0kHzx0les9tRCx3zdZpFYvsINBXhWxF2LjUf1nmHYkcXw=,iv:QQJ4Zw/z4cQeqYf90K29xiHsf5giNIqRBRXeAPWSdgQ=,tag:hcuSRs/Y82u8rdfB6pILVw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsSk01ZGl5d3ZjZmIxRFlr
            eXFyT0x2ZDFXVlFocmtYcHY4Tm1lZWNtTUVvCmx6bFdnUkwxcEY3dW5RQ01zaTY5
            d1VKM2xBdkdkZlloVFpNN3c3V2ZpRHMKLS0tIEhXT3I1RjVsS0pTRG9Qa3I1UU02
            eVVMTnJXanRNVDJXWWQ1TTVsYkFJTU0K/5FzZeMcjMvYYGuuGufWpXW7HEQYGrXT
            2fQlnyzkv8kowCYNOv2lBEZ69dOrPsqxD6KFbdeQt2xJ42F/cbihYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-21T21:30:56Z"
    mac: ENC[AES256_GCM,data:ge0gTd1q0Znc4pAQk5/i2YrXOdqFS5RCjRbVfX3w+J+oksc5sOIO7vNUbEjcoyWxeVtUnquMt6rFfHFDaXHOLjYXM97hCQkWzgvbDnq4y3mkxTnOWf4+PRzu0OkkBEIqfpll1dp9OWBKduHGGnlyq2brtBb52k8og+iK22bwAWA=,iv:GWWHPYh1rcWxQg/NykM0y2o9n9CBFRDa/VtwhR1KsjM=,tag:Ego9wp0RaSIVHfQ/1Qmr0A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: readmeabook-postgres-v18
    namespace: media
type: Opaque
stringData:
    s3-access-key: ENC[AES256_GCM,data:TvJWXKE8nOgj4yTyaI/3Z8K8ZaWUw+Hbv60=,iv:eCIUKkljHDOTJBbYdeVhdrRieBz7iE7HUcE1gd44EL8=,tag:FV9Nw6JJOSbsdzUrAs/G/w==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:oDjAkdptgamRTMuxj3Pq1WxqXrrh+tasBiKVZO59LVWKWb2fZRXPDKax0u2o73DLgilu2LKs26q/2wlY3PfMJg==,iv:JO4fmsqNKV/YobPK838NreLIqw82W00dgFSSgMwkv4c=,tag:bNuLEM4sKskuIbjPR4vq/g==,type:str]
    region: ENC[AES256_GCM,data:EhJ58gOs,iv:VTiSmll7BG9CeZ31zjtmabkNLD/5gy643g8JVYjwlPw=,tag:w/hIW3FzOfjQwV4mvIPpvA==,type:str]
    password: ENC[AES256_GCM,data:GqVilxWV0OoFD8EH6mDWc2HIO16eZI93FvFzUD4zKNIYF+Syf723RL7Q6Wr7m6fSd6Tib1+J++im38GtzN9VYw==,iv:f38wotrt143c1w3FdPpY4xvLgX/pb4Mxm6ZjXc6pCB0=,tag:D0Cn8SJlxFksVM91ak07PA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsSk01ZGl5d3ZjZmIxRFlr
            eXFyT0x2ZDFXVlFocmtYcHY4Tm1lZWNtTUVvCmx6bFdnUkwxcEY3dW5RQ01zaTY5
            d1VKM2xBdkdkZlloVFpNN3c3V2ZpRHMKLS0tIEhXT3I1RjVsS0pTRG9Qa3I1UU02
            eVVMTnJXanRNVDJXWWQ1TTVsYkFJTU0K/5FzZeMcjMvYYGuuGufWpXW7HEQYGrXT
            2fQlnyzkv8kowCYNOv2lBEZ69dOrPsqxD6KFbdeQt2xJ42F/cbihYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-21T21:30:56Z"
    mac: ENC[AES256_GCM,data:ge0gTd1q0Znc4pAQk5/i2YrXOdqFS5RCjRbVfX3w+J+oksc5sOIO7vNUbEjcoyWxeVtUnquMt6rFfHFDaXHOLjYXM97hCQkWzgvbDnq4y3mkxTnOWf4+PRzu0OkkBEIqfpll1dp9OWBKduHGGnlyq2brtBb52k8og+iK22bwAWA=,iv:GWWHPYh1rcWxQg/NykM0y2o9n9CBFRDa/VtwhR1KsjM=,tag:Ego9wp0RaSIVHfQ/1Qmr0A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
