apiVersion: v1
kind: Secret
metadata:
    name: readmeabook-basic-auth
    namespace: media
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:LE8LE1nAVde7Kac=,iv:o7QAfL8GQ6Ob2k3KnS81mctBgzg/iip352hb6359BiE=,tag:8UtGHg7DzHwtGvds7hijgQ==,type:str]
    password: ENC[AES256_GCM,data:Av5EBU9mPjhokW7JZ5qFifueaYDnKjAEbBEJ6X1Fk/2Nu0SrX2ImP9PgkL8rddB6Kk2Epk+ioRlGJRcyvdUqZA==,iv:UNgRAaws77dzG1NZFcslpBKRmXWNkhiAnXxRV1J8UvU=,tag:OVAXsJA8Xomhbue497OscA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZLy9Pb2R6L3QvRGZIVFNo
            bjYzUEIxZWRtSFY3blAzREd2VWVrTHA0UFI0CjNjZzdablcwUEhXOVJMV0VxVU5v
            QnZhRlNUTzhjN0ZVbkxzbmVuRUhycHcKLS0tIFJKdHp4ay9NMHJNYW9qeEN4WE9H
            OW1ybDhHSDZtNFRNemNJMW9tUTZpajAKMekJui0/jVujFjxTDL7Ovne0R3SPkJcJ
            CQoT5aM/qDK22X6ZyD3tf4azBkZTID1bu30uzmM8nRwPHYVNUhmb0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-21T20:40:40Z"
    mac: ENC[AES256_GCM,data:MNoE0T+GcHxet5ipLu1t0G8vjtTwhBcHITsatdZhtYGglweEpiQ2X1qb5WWboXZb9w7AMeQooWXXICeHJqmApSzznxtdnf+siTzWq06FrMfNAOHufSzDwXmZkI3zCn9rcZiau5BrSezMWqtR7D5G9InJTlToAadbnP6JZ4GWgxQ=,iv:P7OG2RzPWBUCrVLTdCktElbTxxkAoNZRArQfK/RJinc=,tag:Q0DUHsVqhDUH0p2L391p/g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: readmeabook-postgres-v18
    namespace: media
type: Opaque
stringData:
    s3-access-key: ENC[AES256_GCM,data:p1QYEUkyX5G/XKjnGvr1HZ7irUjBC1uVkUw=,iv:U1Ck1a5H/5Gj3RNAjO3UjElm1X+IZSzkp7aNo4DjztY=,tag:F8jxbg/rLpSdZvdEO0Bblw==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:2fHR+rdnCtOBLv1xBx2mw57N0W2RYJ5hoPphwHQeq1lHikrJwO/4i7Rin3bQ3KVTolMj0GbnhfWBRkzqgA4Vcg==,iv:whfELPodmjrs/9AvOKVGoYZbHkNxMT7CR3oedjiz/Ck=,tag:tfifhhLq1/oUktSfLrBSBQ==,type:str]
    region: ENC[AES256_GCM,data:nTfoXe+3,iv:nKCHDmqN4weNcrGTUIXMXJGmzjru70LzlxyXsuB8VHQ=,tag:5MLDYqOvrclH9PU1ZqsbTg==,type:str]
    password: ENC[AES256_GCM,data:iYyxlSww2VErSBCkHKpbFFbrdezPIGH/dDrmEHQcp0gLzARexq39+GtduEWQJPCI4g4C4SwZSTIhtCcQIKi/iA==,iv:yGHsGosCeb7sv3Z0SDEr+yFbfKEk5wgMbq64Lbm5A2o=,tag:eNRqdtN5hOEN/ze1WIK76w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZLy9Pb2R6L3QvRGZIVFNo
            bjYzUEIxZWRtSFY3blAzREd2VWVrTHA0UFI0CjNjZzdablcwUEhXOVJMV0VxVU5v
            QnZhRlNUTzhjN0ZVbkxzbmVuRUhycHcKLS0tIFJKdHp4ay9NMHJNYW9qeEN4WE9H
            OW1ybDhHSDZtNFRNemNJMW9tUTZpajAKMekJui0/jVujFjxTDL7Ovne0R3SPkJcJ
            CQoT5aM/qDK22X6ZyD3tf4azBkZTID1bu30uzmM8nRwPHYVNUhmb0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-21T20:40:40Z"
    mac: ENC[AES256_GCM,data:MNoE0T+GcHxet5ipLu1t0G8vjtTwhBcHITsatdZhtYGglweEpiQ2X1qb5WWboXZb9w7AMeQooWXXICeHJqmApSzznxtdnf+siTzWq06FrMfNAOHufSzDwXmZkI3zCn9rcZiau5BrSezMWqtR7D5G9InJTlToAadbnP6JZ4GWgxQ=,iv:P7OG2RzPWBUCrVLTdCktElbTxxkAoNZRArQfK/RJinc=,tag:Q0DUHsVqhDUH0p2L391p/g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
