---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: piaware
  namespace: adsb
spec:
  selector:
    matchLabels:
      app: piaware
  replicas: 1
  template:
    metadata:
      labels:
        app: piaware
    spec:
      containers:
        - name: piaware
          image: ghcr.io/sdr-enthusiasts/docker-piaware:v8.2
          env:
            - name: TZ
              value: "${TIMEZONE}"
            - name: BEASTHOST
              value: "${BEASTHOST}"
            - name: LAT
              valueFrom:
                secretKeyRef:
                  name: adsb-lat-long-alt
                  key: lat
            - name: LONG
              valueFrom:
                secretKeyRef:
                  name: adsb-lat-long-alt
                  key: long
            - name: RECEIVER_TYPE
              value: "relay"
            - name: FEEDER_ID
              value: "${SECRET_PIAWARE_FEEDER_ID}"
          #livenessProbe:
            #exec:
              #command:
                #- /scripts/healthcheck.sh
            #initialDelaySeconds: 300
            #periodSeconds: 600
            #timeoutSeconds: 30
      restartPolicy: Always
