---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-release-prometheus_rules.yaml
  - helm-release-snapshot-controller.yaml
  - helm-release.yaml
  - networkpolicy.yaml