apiVersion: v1
kind: Secret
metadata:
    name: comics-basic-auth
    namespace: comics
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:qJpH2WRl,iv:AU0eBKXelHdel4D3yp6T2x91h5rzVpHwlectaD+Di3E=,tag:JWXgrJYzAyPztqiZUkVm6w==,type:str]
    password: ENC[AES256_GCM,data:1yEOSKCvdJlvURloDkzBBWQiF76gvgds9p8wWhXRtzIWyKkoE9FzY/o5WeOxVWRB5RQxU/Mtrawdk/zoa2DpTQ==,iv:o53r8RINzOI1Hx42MERJFbDkHmi+0J8JDkNpP5NnpkQ=,tag:Sb+DA39MDBKWB83cCGlW6Q==,type:str]
sops:
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyNnBrZldnOEIwaTFWazBM
            WVNCM0pjbW12OGMwRHlOaVZOVWl3N0h1dkFzCmo4WWI3TzVlUzNNV05RQ1ZtdjZD
            U0JGMUsycVNpd2J4K0UzYlBwVGRGVG8KLS0tIC9iN1dKbExuS2xIekNhNGx5WHFv
            ZUhpRnlHR3haNzJuanF3V3RSWnhCeE0KWTtcLeNN266AOyG/dBnvYqs09AhYiTm5
            4KbJ2LR6LoK02Pac3mdVpToTNuOiejGzBHqRBjLbAFQKlZhRKI06BQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-16T10:46:02Z"
    mac: ENC[AES256_GCM,data:OM6Y57tGu6HQK2U9ZDVLmLtdj66r+wtGOwF6xh/Hg06fp/D3LPlmW/Tcf/oCpMIV3L2O+81YCXLsGFVyqUVQYdPgSzoomxNsCU1Jx3SlhJ18zlsjK1cqziRWysdjr6AlXNaowYE9kdLrOmFV+WzTJirLkqr/GxFTWZOYadXuFWA=,iv:rgVqxGtaPcjGs0rw5+zxevt9BRbUcOxiZdSuEx69/Vs=,tag:WDdlLSgb1SmjXtkZYDk6LA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: comics-postgres-v18
    namespace: comics
type: Opaque
stringData:
    s3-access-key: ENC[AES256_GCM,data:moxhX6Lan7wkROmM1GayVwQiFHY=,iv:Db1kmoZ2L3UAsJF8dHexPuTy9V/MhctwiR1TEslTOJY=,tag:zvRlyfShL+289IuB80+Fbw==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:J7Khrm2q6ok7Pq1YEUaiRR3oZZaUiF/hb6Zg9Ge6qUb5NUqug3vgsw==,iv:gyneqz++eddwFajj4Zj7BoRvqU/Jla4gB3/EIjRz5hw=,tag:43LWht1EaXaXWQ9nsxTSmw==,type:str]
    password: ENC[AES256_GCM,data:sCxDQB/DhxTmgC349S2xkLRt+pQlR8WuWvUTCQhvpZ+0hrNcSGt2j2Hmp0CMxe6624ypV5StjF+etl853OPmVA==,iv:wPLowBxGKtN2ZyMynkar1UfBY7Dez2T/2dz39QlgAWo=,tag:Bo6R0n4jdbxMM45LGdgJkg==,type:str]
sops:
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyNnBrZldnOEIwaTFWazBM
            WVNCM0pjbW12OGMwRHlOaVZOVWl3N0h1dkFzCmo4WWI3TzVlUzNNV05RQ1ZtdjZD
            U0JGMUsycVNpd2J4K0UzYlBwVGRGVG8KLS0tIC9iN1dKbExuS2xIekNhNGx5WHFv
            ZUhpRnlHR3haNzJuanF3V3RSWnhCeE0KWTtcLeNN266AOyG/dBnvYqs09AhYiTm5
            4KbJ2LR6LoK02Pac3mdVpToTNuOiejGzBHqRBjLbAFQKlZhRKI06BQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-16T10:46:02Z"
    mac: ENC[AES256_GCM,data:OM6Y57tGu6HQK2U9ZDVLmLtdj66r+wtGOwF6xh/Hg06fp/D3LPlmW/Tcf/oCpMIV3L2O+81YCXLsGFVyqUVQYdPgSzoomxNsCU1Jx3SlhJ18zlsjK1cqziRWysdjr6AlXNaowYE9kdLrOmFV+WzTJirLkqr/GxFTWZOYadXuFWA=,iv:rgVqxGtaPcjGs0rw5+zxevt9BRbUcOxiZdSuEx69/Vs=,tag:WDdlLSgb1SmjXtkZYDk6LA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
