apiVersion: v1
kind: Secret
metadata:
    name: comics-basic-auth
    namespace: comics
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:C1RPy+FG,iv:gC2skx+L3eDG4+6I44eIfX4prJWHHXNaV9eoRZzpg6Y=,tag:ExHdwmrI1YmMXzOYrNq/ig==,type:str]
    password: ENC[AES256_GCM,data:N39rPWgF4hfTmM1il8VZ4YP3F9vn3aUsD8x6B0GseLt5wfdaphv3njOE3IJPy+w8L5n0skCzxRQMGbv/2xEoEQ==,iv:M69XphpLu7GWGQyEnnJXHnXhv6Ilrmk9/PbO/kXLBhY=,tag:msKqPzxFuk3gVioOWt1cnA==,type:str]
sops:
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkQ3B2emZ5R09jNGVGQVZi
            QWIxSUJTZUpvR3F5TkdlRGZNNEpwZ0lhNEZNCktDY2paOWxVT0hmVzZZT2tITlJL
            cmZHWERmMjI4V1lUM1VYK3pWbXpEeHMKLS0tIGRGSkcwd3hFRC9MT0liSGplempq
            THdYUHM3VmMwS3p2a2JpRWFXZkxJU2sK1FTIrtLJuEL/u88XRMFKcqEDUB+K0MMV
            ieRUIpmK2lLlUT6shZxRCCZ0b0bAB1bl8q8y6+cPgQZxWC/vy8n4yw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-17T17:27:26Z"
    mac: ENC[AES256_GCM,data:YOwBCgB3gTRR2rMZWoaAKMhm3mUzmQbSQeMclmbFbvNISfW43Bl/GXNr4AoxupuOPLsy3KCrMAWtSJbe+wQuFW0H7uWI9eFeQdBcZ5+es2BWvQ7YcktxLvp9eqw+sm64zx4V3YAR2o00KQJy5l640+50vK6QlTyrntDyoWCB1m0=,iv:I7AOg1ktxLyYiOm0v6kUt/VJuzhkiBYKBIHoXqfE37w=,tag:LXM2POQjjCdl+ZUvPz/WBg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: comics-postgres-v18
    namespace: comics
type: Opaque
stringData:
    s3-access-key: ENC[AES256_GCM,data:wF6wxjiiLmWQsFsK2iEUeC26wxB6Z+9+K9Y=,iv:rRXBA2HJq/YQFstIBmb52661PhoHwygOxIz3WDwld1I=,tag:oE2eaJe5HeK0qydcF96nIw==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:S7lEkdVvXUk1KoP5VzCizL6xMV+J3kxB4CHuxIQuhnuGFKCrdFLvm1pEma9kIQQnksFDOtfrFIyozm2fq4docg==,iv:FTQR/t7UKAoKrjjbSoExpCTxsx9drPpK8Q0G1TTOwcg=,tag:5/XiQdQfiam81SA/jxqbcw==,type:str]
    region: ENC[AES256_GCM,data:eA0UNzxP,iv:RnHBnwYsjGN/UqetxRNL2Xby1Nel2LCzTFiTVR0LMFI=,tag:vFTbXIZDffMM+Zg4uDXKhw==,type:str]
    password: ENC[AES256_GCM,data:IHtzASIK63Ltc4Usv+CRPILCr3yIg9861wyVL1/vsYeM7VbA6gNcj1kK8Vp3tpcrcDOdCMCl9bE5Nrk/rBzN4w==,iv:OpaO7opu+nAVs1ehxb//56YQy8R/ddWkK8b+IcqVaBQ=,tag:VqSZz2Ong7BKlvhLkLDj0A==,type:str]
sops:
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkQ3B2emZ5R09jNGVGQVZi
            QWIxSUJTZUpvR3F5TkdlRGZNNEpwZ0lhNEZNCktDY2paOWxVT0hmVzZZT2tITlJL
            cmZHWERmMjI4V1lUM1VYK3pWbXpEeHMKLS0tIGRGSkcwd3hFRC9MT0liSGplempq
            THdYUHM3VmMwS3p2a2JpRWFXZkxJU2sK1FTIrtLJuEL/u88XRMFKcqEDUB+K0MMV
            ieRUIpmK2lLlUT6shZxRCCZ0b0bAB1bl8q8y6+cPgQZxWC/vy8n4yw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-17T17:27:26Z"
    mac: ENC[AES256_GCM,data:YOwBCgB3gTRR2rMZWoaAKMhm3mUzmQbSQeMclmbFbvNISfW43Bl/GXNr4AoxupuOPLsy3KCrMAWtSJbe+wQuFW0H7uWI9eFeQdBcZ5+es2BWvQ7YcktxLvp9eqw+sm64zx4V3YAR2o00KQJy5l640+50vK6QlTyrntDyoWCB1m0=,iv:I7AOg1ktxLyYiOm0v6kUt/VJuzhkiBYKBIHoXqfE37w=,tag:LXM2POQjjCdl+ZUvPz/WBg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
