apiVersion: v1
kind: Secret
metadata:
    name: comics-basic-auth
    namespace: comics
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:A0sAnMUo,iv:+DSZ0I+5gLlCtYj09fHzz774mcHcJ9erEkcNC3QFDbk=,tag:d3eB+qlv9/wDLlVn+RC7gA==,type:str]
    password: ENC[AES256_GCM,data:wduwSHgrbvJ5IiNyvfszCua6S2H1BQpU4gNN+f0KMXUfH5ZfYyk24ioMVYvXCVKxwUy6/8XZX/vmqVJTMOFIPA==,iv:TeP9RsW6YJoxHR/WmRlsBTRr334OmaAYiPeaM/ehxXw=,tag:WJc+JOPmeqQIbrfo9MrT0Q==,type:str]
sops:
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOSUFRd1hzSGtSbDZCRzJJ
            TTU2aHZqdXZNZ2ZBbVFRRE9wUGp6OXgxVkdnCkxLdTVHNTJseGxncXpleTFSWTQ3
            SklHVnVzRXpRNjQ2NENwWEd6a3lxTkUKLS0tIEthUlFEN21GTkdWb1h3UGNTTEt1
            UjQzdXFxc3VrMGhJQ0FJNWJ1SnN5YkUK3ryXnplt1wCkkkJH3aoXQe+43Lidc2iW
            p3XZ4lXBz0IsFuXSG7leFltxepJoC9wKh9n1uwFu3o7c4dOTHKrIhA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-17T17:06:38Z"
    mac: ENC[AES256_GCM,data:5VzEyQyYXD+eA4xr+381iY7qCypQvoKhg1XuUtk6O3mBJHrtsW0QY7yB93eHP2Kb/eoI8yJgI95q1iEdvdf4KUXlmkzdWHJ8AK43nXTXp6KQDaYKZvY6xsDzTx2xjIlfZA4W05V2biKETC4PvyykK9Lvy+S79LNMZ/NfMFoECWQ=,iv:IVDHbmJRbar8UDURDxp7mZrfW/DJMqSxMm6ma77Yxrc=,tag:fDK4F2qhCE1Za4bBCCV5HQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: comics-postgres-v18
    namespace: comics
type: Opaque
stringData:
    s3-access-key: ENC[AES256_GCM,data:btNaZCvlawLINcaqRAyuOxO4XFc=,iv:HTTxSEzlX/UucKJP+XLykIxnm3FaIXJPIjkv0FZ/Dtk=,tag:JtIv7yznVuibQKpKgV3lQA==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:93MkzPFRPwy0dCgYT0le1G8T8/ZI2FVKapMmDWVqhY2CaXyV3PuM2g==,iv:vvyTuguhyO6KJ0M/BVXVqSiEGbZdQaH4+UQC6pcg9Mc=,tag:/HeDLAP/h+8Er8xVj2sRDA==,type:str]
    region: ENC[AES256_GCM,data:R2O+PT8J,iv:gJpZIHjO7lLotJSZebkLQNaz07KmFJMfXa251RoSLKQ=,tag:z88a777mTL5pRDunfVGSaQ==,type:str]
    password: ENC[AES256_GCM,data:m/uyjhHFYkBs43Amzox118N+K+xXS7TQf6guxT2QUVIqPEnKxaNy5zTMzZ6naK8FC9pTnOaQcdVbXXorBrPimA==,iv:blUEAMlyqOW4BmeIKMsDlSv+4SkiM6lSVfi7Q6Ekf3Q=,tag:dWsne35W4Ih6fVNvPoUXvQ==,type:str]
sops:
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOSUFRd1hzSGtSbDZCRzJJ
            TTU2aHZqdXZNZ2ZBbVFRRE9wUGp6OXgxVkdnCkxLdTVHNTJseGxncXpleTFSWTQ3
            SklHVnVzRXpRNjQ2NENwWEd6a3lxTkUKLS0tIEthUlFEN21GTkdWb1h3UGNTTEt1
            UjQzdXFxc3VrMGhJQ0FJNWJ1SnN5YkUK3ryXnplt1wCkkkJH3aoXQe+43Lidc2iW
            p3XZ4lXBz0IsFuXSG7leFltxepJoC9wKh9n1uwFu3o7c4dOTHKrIhA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-17T17:06:38Z"
    mac: ENC[AES256_GCM,data:5VzEyQyYXD+eA4xr+381iY7qCypQvoKhg1XuUtk6O3mBJHrtsW0QY7yB93eHP2Kb/eoI8yJgI95q1iEdvdf4KUXlmkzdWHJ8AK43nXTXp6KQDaYKZvY6xsDzTx2xjIlfZA4W05V2biKETC4PvyykK9Lvy+S79LNMZ/NfMFoECWQ=,iv:IVDHbmJRbar8UDURDxp7mZrfW/DJMqSxMm6ma77Yxrc=,tag:fDK4F2qhCE1Za4bBCCV5HQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
