apiVersion: v1
kind: Secret
metadata:
    name: joplin-basic-auth
    namespace: joplin
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:qjlufFSC,iv:tPmqhjURswS+0Sh0Mzj29PK9w1G1WPRuwwQhipZ0IXQ=,tag:ZUDcHnqz8+64o+CE6Viq9A==,type:str]
    password: ENC[AES256_GCM,data:3xu+1uRw6rEGau/KjTJ6j1BBCInQYh8UBXP02xcn7uhAo8rFUaxJoBBb2/cAzau+EMhh4dvkPk50HDhvb1Pkpg==,iv:0TzNueCKrhnrtzgWLdrK2xG9javqRrzQfhm1tEXA/oU=,tag:6Fh9Uug8SNkyhAPqWBmQ7w==,type:str]
sops:
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6THpPRVJDL3pDWlVzWXd5
            dUVlZnJKT3kwYXduYXR6WC9tbndjOFR6LzJjCmQxMEtnREtTTFloRTdYaWFMM21u
            a1lyaDZJS29lWWtKaE5GaVFxS2ovTjgKLS0tIDN0T2NYVDJyZWhoOUxwUzJGTkps
            M05ScDF0ZTYrZFViMmM2VG1MODdVZVkKA/BGrbKSotjYWOGfOKaUuwRfkl9CcMtW
            5KW3Yovq0V/wTkCdONYKdUhCDCUCQwHe4yUFF+oUUKx2J9YTZ9EwPg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-17T21:13:04Z"
    mac: ENC[AES256_GCM,data:ornHsJYpRtBGMVlIVoTjnHO/BxGoYHTSdEsuMf//jv7HJlVJMjyPzLRaTN/KQVQ61OcpJyEx8iKOAOiX8BCzYPJCnsISuCbDL2sjNpvO+JKnlBrkWmTD7oH8s3DOrm6jplnn46dXrHd+TFBV4181TglpaYK83Caw87dOepXvrfg=,iv:pbMPqBXRt3NDAg6OQqczxDFUVGVhWcvnzknCcQnyknw=,tag:eV2yFmxbQ5B3BemLyX1JBA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: joplin-postgres-v18
    namespace: joplin
type: Opaque
stringData:
    s3-access-key: ENC[AES256_GCM,data:M9V/+bmYOLi/L2FlA5DEKn4utXNLNLFIi6Y=,iv:acpVGBgMJo2yhL8YEyAQZsSR6l5zBqpXlohA8fCnAHs=,tag:Y0VcBo3A/K1naHQIK83bqw==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:0JKO+myVX1jFwJpp3rxa4TShdaXQnBmBK7mGA1ZiWmsPclTRII0apDW8N8l5OlPfZ2lriHkzHxiznVWndl5vog==,iv:8yOm2zFzLM13svqQfWaOvXFCHqjUQkQhRNHAtn/IKh8=,tag:cky7OP4O7Xp+UGnQwyaDew==,type:str]
    region: ENC[AES256_GCM,data:hXNDNWVa,iv:zIGRL30prBZQVmB5DUInA3IH5v8nF0QKigsXcGC5pPM=,tag:Q0lGuGXvbqwgZLwDx0QU7w==,type:str]
    password: ENC[AES256_GCM,data:DvlE0AMB72hs1/ZYZYeyfKRp4HE2UZF1isPL1AFr6UQ+4olHyksn2yh90x4XNNP46rZ322Rbl0ArsWMhngYCiQ==,iv:8I5djN3iyv6UIck/ESguCsBLgD+tK3UpoYvOu4KpyFg=,tag:345aqz69dK4seeYquMjiUg==,type:str]
sops:
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6THpPRVJDL3pDWlVzWXd5
            dUVlZnJKT3kwYXduYXR6WC9tbndjOFR6LzJjCmQxMEtnREtTTFloRTdYaWFMM21u
            a1lyaDZJS29lWWtKaE5GaVFxS2ovTjgKLS0tIDN0T2NYVDJyZWhoOUxwUzJGTkps
            M05ScDF0ZTYrZFViMmM2VG1MODdVZVkKA/BGrbKSotjYWOGfOKaUuwRfkl9CcMtW
            5KW3Yovq0V/wTkCdONYKdUhCDCUCQwHe4yUFF+oUUKx2J9YTZ9EwPg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-17T21:13:04Z"
    mac: ENC[AES256_GCM,data:ornHsJYpRtBGMVlIVoTjnHO/BxGoYHTSdEsuMf//jv7HJlVJMjyPzLRaTN/KQVQ61OcpJyEx8iKOAOiX8BCzYPJCnsISuCbDL2sjNpvO+JKnlBrkWmTD7oH8s3DOrm6jplnn46dXrHd+TFBV4181TglpaYK83Caw87dOepXvrfg=,iv:pbMPqBXRt3NDAg6OQqczxDFUVGVhWcvnzknCcQnyknw=,tag:eV2yFmxbQ5B3BemLyX1JBA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
