apiVersion: v1
kind: Secret
metadata:
    name: joplin-basic-auth
    namespace: joplin
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:JLuuboRU,iv:R9N3yc5Wvd0uwrl4nKbrwrg0QFYzSRSnUlkAx0hq+io=,tag:fx3EkxGzLTxwVyHkn+tY8A==,type:str]
    password: ENC[AES256_GCM,data:Z4KDoMiOiHxE+1C0PuM56gWgxP1+/x1taF16fzD3IBgEr7IVVJl+10qLJL6W/DCW6kqFOV4SXK5nfrJtf9W/oA==,iv:+1FpQAU//6vKC1XVDPNUbAFpK4WGdk2cAouxrZvg8Ws=,tag:INm44lGtQ6K6nJHF5qu1YQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6RWs4ZVBSQjFvMFZGODBa
            NVZ5REQzaEZ3a3hYZjl2eEdoSm1ub3dGbkRJCmYyZDBSUmdPcldPUnJsWlgxbWpG
            VWx5Ny9DKzJTcFJ1V2pPbWVXUkJiKzAKLS0tIGdQc1NtQ1dKb1VBYnFLamQ2b3ky
            d0xUZUJxZ01pOVZCc0NIcGlDWmlRTlEKNX6o0qvK3YPfwyOzA1ad+O2QOp9b2yWO
            wy8RealPcyb+HlkTNLF/jHfe5RU+mvGN+nVtMqRRwJ0nyj83c4y3mA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-21T21:55:41Z"
    mac: ENC[AES256_GCM,data:i3HDpuTJrFsWe5U21CLfImL8wQqOK6CrImcx6Trf+HHDvJthANo7gKwVz5qn1dcEGlKWYe1r8Y5lub0/9UNJ6uy3Ya0Wq/Qf/AWb54egeuLlMsHMA7eZ7bxriL9B2XzPHUWoTNfX4WB2TTgT9ARhjV5Porz7WJE4m2AT1T2cS2Q=,iv:K6kkno2DKLlbfxdVuSRShFKEao9gzYeGXe3SS7fp3c4=,tag:q0zHNJTGmreFVatZHhaBUg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: joplin-postgres-v18
    namespace: joplin
type: Opaque
stringData:
    s3-access-key: ENC[AES256_GCM,data:ShGwNXKy4RhdOdNXf3PNIrfhR9k=,iv:Gy3laZGhLgx94QznuiDH+k3XzB5Xz+6BxXABdkiOVp8=,tag:cdDKCzQsFbkYieBICPKisA==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:8XnTsvlRtqjRcA76O9wrMdlwgcHQ1m8aKzf69ALpSFugLPNrUEM5rA==,iv:P4HrMsD3eTnaDyXoejKpCoFcV+jvZJnM+6purCFTB6E=,tag:waAydLiPRNcPfYHaC96drw==,type:str]
    password: ENC[AES256_GCM,data:OEkytHuPdKIIStUu0HX4gU8/ujdVxoBxY/uoyFe51M0PxGuIIDhVhhoxY7vQ0AAWayuG+BScl+bR2P8hC95aCA==,iv:SNqfp4iRYU9PICuWL8GGmqCkbtcRz+dsgjW8IwB0a0I=,tag:IkIQPff86d7D2lfxAnuxDg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6RWs4ZVBSQjFvMFZGODBa
            NVZ5REQzaEZ3a3hYZjl2eEdoSm1ub3dGbkRJCmYyZDBSUmdPcldPUnJsWlgxbWpG
            VWx5Ny9DKzJTcFJ1V2pPbWVXUkJiKzAKLS0tIGdQc1NtQ1dKb1VBYnFLamQ2b3ky
            d0xUZUJxZ01pOVZCc0NIcGlDWmlRTlEKNX6o0qvK3YPfwyOzA1ad+O2QOp9b2yWO
            wy8RealPcyb+HlkTNLF/jHfe5RU+mvGN+nVtMqRRwJ0nyj83c4y3mA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-21T21:55:41Z"
    mac: ENC[AES256_GCM,data:i3HDpuTJrFsWe5U21CLfImL8wQqOK6CrImcx6Trf+HHDvJthANo7gKwVz5qn1dcEGlKWYe1r8Y5lub0/9UNJ6uy3Ya0Wq/Qf/AWb54egeuLlMsHMA7eZ7bxriL9B2XzPHUWoTNfX4WB2TTgT9ARhjV5Porz7WJE4m2AT1T2cS2Q=,iv:K6kkno2DKLlbfxdVuSRShFKEao9gzYeGXe3SS7fp3c4=,tag:q0zHNJTGmreFVatZHhaBUg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
