apiVersion: v1
kind: Secret
metadata:
    name: endurain-basic-auth
    namespace: endurain
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:nXa6Fv0kNCk=,iv:hTJg8WUEotepBjGTsQ5GyUJVUnybzhnOpmFyGS0lFvw=,tag:aJ66aN+lZVimovoAM3tIWg==,type:str]
    password: ENC[AES256_GCM,data:8TTngV69Ph84GgDzd8Yg5nSjJTVA/wKZpHPPfz6VeaikxRD4i291Wo3Iznvcij9JW0Xn8GR2YZU3cO1jq552mw==,iv:J1YWTfFhxaaxzOWQyvMXPOA3Xeao4r4kweg7JWuOyAc=,tag:Mb8ZPc66FOdkigyJUVmWBQ==,type:str]
sops:
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwbDMya08zaDhETWZZcnMw
            ZEdROGhhbHpxeXl0dng5VFBrdnZOa0dKc3hVClpRM1dOWDZsWXM2TFluaUVKVFpU
            c0gxYkJkMGJ6aHNGSW5zS2d4aHphaFkKLS0tIDJqeVBPdjd4RkpYZ2lpczA5UXhv
            K1dkallCOWtTWlNOQ1hYWHNXVGJGRGMKGYsPbAq3QZCFXlSgxkbhH7YL8gwqYTb8
            aR4w0lPs9vK3JZEeMlAFyxCOnDgDtS+ReAOau6GJ9O9e1wjxOQrr4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-17T21:12:43Z"
    mac: ENC[AES256_GCM,data:uPDuJbMOPldHbEJBoFwJytGh2CQ+oityVULCoTsrO3hnYPfV1lF79ucbfh4FIPHS6+ZcDDZZ1uu0JtLmJS70MF/rT6d+FPsh1LvSJs6acEcMA5RTy2Ll6PlWSUuSA8/vmhz7K6O68kp3Ukp5+PWAeacs1QubbIT8pdLEqgnuOdc=,iv:wHMV3YL182gh3ZHBYK7HLdR5Tn7XcE063HNrFPv/mqk=,tag:zBZbrwlJoP1OpaF9j19mwA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: endurain-postgres-v18
    namespace: endurain
type: Opaque
stringData:
    s3-access-key: ENC[AES256_GCM,data:tXXPryxx8TvlYnzoeKc3yflt/taW7PHjq+8=,iv:5ewNnxq4NLcYdv1KzqWRi3Ypca2VqAZBk0Acwd/33UI=,tag:jiY623DZUIlTzD79prEGXg==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:f3tz8u3igIqPhqmDwAcXT8AGwe3y6X7734rfcctSFq7p3XiKU1oCJpFVhOiY2GAdbHmaeMvl1dbn22R8Ke0qLQ==,iv:6ssQQ0DFIuFlgr47r20r/z5tO38Xpx3eh/DycRmSU/w=,tag:wbrz6jg3SYQsIa6KvvWrBA==,type:str]
    region: ENC[AES256_GCM,data:jlvdG5kO,iv:dKXiRM/kbu6bdhl3sw3VWoO+YaXhZYR2u/IhQHzwgBw=,tag:t85eeD6KSl+2kXSvxtJs3A==,type:str]
    password: ENC[AES256_GCM,data:oNUBp8b3b/3uMYJFUUDaAaIQtBCU27dz+Nso4vZhCBwNlNaDlrzzMcXNfk5RBxkg4JmypccPdqqw68cCRm0S9Q==,iv:YP/Xg8FDd4etXqWcw6y3tC97PzrxmONWjKavSnMtre0=,tag:7GdCbAe3mTnF/fCCd98Wtw==,type:str]
sops:
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwbDMya08zaDhETWZZcnMw
            ZEdROGhhbHpxeXl0dng5VFBrdnZOa0dKc3hVClpRM1dOWDZsWXM2TFluaUVKVFpU
            c0gxYkJkMGJ6aHNGSW5zS2d4aHphaFkKLS0tIDJqeVBPdjd4RkpYZ2lpczA5UXhv
            K1dkallCOWtTWlNOQ1hYWHNXVGJGRGMKGYsPbAq3QZCFXlSgxkbhH7YL8gwqYTb8
            aR4w0lPs9vK3JZEeMlAFyxCOnDgDtS+ReAOau6GJ9O9e1wjxOQrr4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-17T21:12:43Z"
    mac: ENC[AES256_GCM,data:uPDuJbMOPldHbEJBoFwJytGh2CQ+oityVULCoTsrO3hnYPfV1lF79ucbfh4FIPHS6+ZcDDZZ1uu0JtLmJS70MF/rT6d+FPsh1LvSJs6acEcMA5RTy2Ll6PlWSUuSA8/vmhz7K6O68kp3Ukp5+PWAeacs1QubbIT8pdLEqgnuOdc=,iv:wHMV3YL182gh3ZHBYK7HLdR5Tn7XcE063HNrFPv/mqk=,tag:zBZbrwlJoP1OpaF9j19mwA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
