apiVersion: v1
kind: Secret
metadata:
    name: endurain-basic-auth
    namespace: endurain
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:TZ615LOdqpo=,iv:MDRb4VnzTu2OETtRZ5uQgoutpXcwVz1w5fiSH8zHNLI=,tag:wx9b9obf0K/WPlYsKN4H1A==,type:str]
    password: ENC[AES256_GCM,data:ZE88g5Q8ewnLzF6IsOqEYl8f3IoLbQTur9uHTfDyPxn4OONZyBG4Jv1F2A+8HRwJQOTqyVuGxMzDKb5tzFehqQ==,iv:HcUCa2t+mRvoImbzv0qpfC5eoGiGEnzTeJmqX/knxz8=,tag:BTa0DPI+LdCr8Cy6MdC//Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWWUgzb29Mbk9menJlNjhF
            TWxaM3hJSVdFeTRvVVdUa3hEQzZhUzlwR3l3ClJTZXFnVFRLVnpnSjBlOXl2RHBO
            WHlsZ2JZTnE3VHRpaEpvMk94VVVnY2cKLS0tIG1qWW1jaTV3YndqUEFQT245aDdv
            SklvLzJLa2ZqVU5tUWZSdlJURVk4ZHMKj53yIV80cyHPT2TP3AakwsF3l9QbIsXu
            /Yn8qSnn/t6jFiV39h/OXdKtJyRXqfM0bSOKwZH9juGCNnWOilS2JA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-20T09:22:23Z"
    mac: ENC[AES256_GCM,data:NPLtyaX5/yVtU72io6HSjQnn7oxy2rbzHRvzgBefJuxcZ3CWjuZgqIdPP3CsGdV9u1TSqtp5sR8VwHc4wwUy0vDeWIcXDHPHEionD21bTnT9HpQvW5WYbiFXjO809EK6TJJIGCgXKtiZ/ogXMKt/lOb94hHmtWetKRNo67fbKKg=,iv:R84+BA4E2lxxaoZ2Ogc8TaRx2heCaERqd4qeXp1Ck+U=,tag:Kd9EevCWFdkX/aCiel0VUw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: endurain-postgres-v18
    namespace: endurain
type: Opaque
stringData:
    s3-access-key: ENC[AES256_GCM,data:oc/VeDgvjbjly5kiHtd60t8OtPs=,iv:xZ5Qz/Fa7cWWeGCCBX4efStNNMRr4m1f6bEDlrX8piA=,tag:JZv/pzT3ChoLL/ozM9AiPQ==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:zy0ERTNgabHLvq5Sm5wHuR9V7xXwyy/lfY9W939OMWaD5fKnwMVgaA==,iv:U1DcwovrfoPSIVeJKmEd/QjRA97Zzu/7fXlN4xqqkRc=,tag:b72tcOBJoxMHqvwiaJVUjg==,type:str]
    password: ENC[AES256_GCM,data:2juRTwErieClIO6oxWNdjgdNirwYYWb/s1V9diql3mmxJ/CyqvWfutqSu1TwQq/ud09ZN2qnYEFBVCGtp7NQPw==,iv:yWVYl0nWWlWKSxfMYy2FH0PT24uwNvGsj7O8ms6Niys=,tag:ToZfzpxut41Fl6bLIumHYQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWWUgzb29Mbk9menJlNjhF
            TWxaM3hJSVdFeTRvVVdUa3hEQzZhUzlwR3l3ClJTZXFnVFRLVnpnSjBlOXl2RHBO
            WHlsZ2JZTnE3VHRpaEpvMk94VVVnY2cKLS0tIG1qWW1jaTV3YndqUEFQT245aDdv
            SklvLzJLa2ZqVU5tUWZSdlJURVk4ZHMKj53yIV80cyHPT2TP3AakwsF3l9QbIsXu
            /Yn8qSnn/t6jFiV39h/OXdKtJyRXqfM0bSOKwZH9juGCNnWOilS2JA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-20T09:22:23Z"
    mac: ENC[AES256_GCM,data:NPLtyaX5/yVtU72io6HSjQnn7oxy2rbzHRvzgBefJuxcZ3CWjuZgqIdPP3CsGdV9u1TSqtp5sR8VwHc4wwUy0vDeWIcXDHPHEionD21bTnT9HpQvW5WYbiFXjO809EK6TJJIGCgXKtiZ/ogXMKt/lOb94hHmtWetKRNo67fbKKg=,iv:R84+BA4E2lxxaoZ2Ogc8TaRx2heCaERqd4qeXp1Ck+U=,tag:Kd9EevCWFdkX/aCiel0VUw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
