apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: endurain-config
    namespace: endurain
stringData:
    FERNET_KEY: ENC[AES256_GCM,data:vbb6uANuLdwiEbSn3CpbZSsi/GNFHseHhaN3fml1aZdbBKMvXujUkNsaC6k=,iv:sEqY9fNpqsQeKbJV8EnuJ1oVCKT9/s5eN+g2IUFNhAU=,tag:DRqSk7VXTW3tWrSScuiisA==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:eMoXC1i7MgZfP7kQMySR9XPyQZt2Q/G8igrk/LwmAKzzyME6/r3wj31PSDA4UrRejpEY68RkyoctEod9kUETww==,iv:9uNwbUtodfqgmTS5g6Vbf5L2thp3svS2/bNYK8K+z/Y=,tag:8DGwllcO2nKQTnS6GjKAMA==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:/Z1DBzuPisksdochvq9tWLlF46JS3wzLxqM/dKAtSrXeRVB1hkRcGurzdl19OsppLqnWzdguXS2/D27lJctz8Q==,iv:nGFK9XYbeGK60MrEHKDP9Ti028GB89cavYwi167EaHo=,tag:ezGc6/0MrvU371ZQR9O6Vw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13s49lz9hcwqdlgyyde5zr2ynryc5jsydmyvpvhx0klqd0ylkkq0szd3xtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHU2NwRTVuT1hlV2tRcWFL
            YTJqc2dBUHRyOERwbkF1OFJrcFR4NnZpUkZrClpaSmRZdEJ4cm1scjJDN2lhVzZs
            TEJXWXVwVlh3Wmo5WlhGSlVTYnNyMlEKLS0tIG40VUV4ZG9zcXk1bGh5WUU1Qlpx
            OEpMTkp3OFJUcmtPbWYyVVdQZXZRbWcKDG37StDavJ123IfTp+4p/3NDkTe2FjAY
            RFHjdcfuDqPwVf/cXTNrlrWxkg73gysePdvtZSOTLo7PNwhbi8tUsA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-20T15:04:34Z"
    mac: ENC[AES256_GCM,data:N6BB8ta7vBx7Mq9rYOg2QbMe/Gmfz7PTWeKXB+8FHKhEdH9FqAltm74XYW+71VCOeQg37hUVB6IOPaeAxCQk/6Q95NzcUkDqQ3EAQjkO4n0ool6Xt9G5iE854Usihi7MHSOwJUhNFPtjniMja0JTSIn7Vg2ug/7nnpnpAMaILFA=,iv:4QssEN/bxLiEMUz2n1FyV3+rlE8AahlJu+s4MmieiMY=,tag:lg93hlcFrUXmwQfSatrMKQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
