---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-release-cluster.yaml
  - helm-release-monitoring.yaml
  - helm-release.yaml
  - namespace.yaml
  - networkpolicy.yaml