---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny
  namespace: rook-ceph
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: rook-ceph-catch-all
  namespace: rook-ceph
spec:
  podSelector:
    matchExpressions:
      - key: app
        operator: Exists
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchExpressions:
              - key: app
                operator: Exists
  egress:
    - to:
        - podSelector:
            matchExpressions:
              - key: app
                operator: Exists
    - to: # mgr
      - ipBlock:
          cidr: 0.0.0.0/0
      ports:
        - port: 3300
          protocol: TCP
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: rook-ceph-catch-all
  namespace: rook-ceph
spec:
  endpointSelector:
    matchExpressions:
      - key: app
        operator: Exists
  egress:
    - toEntities:
      - host
      - kube-apiserver
      - remote-node
  ingress:
    - fromEntities:
      - host
      - remote-node
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: ceph-csi-controller-manager
  namespace: rook-ceph
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: ceph-csi
  egress:
    - toEntities:
      - kube-apiserver
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: rook-ceph-exporter
  namespace: rook-ceph
spec:
  podSelector:
    matchLabels:
      app: rook-ceph-exporter
      ceph_daemon_id: exporter
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
          podSelector:
            matchLabels:
              app.kubernetes.io/name: prometheus
      ports:
        - port: 9926
          protocol: TCP
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: rook-ceph-mon
              app.kubernetes.io/name: ceph-mon
              ceph_daemon_type: mon
      ports:
        - port: 3300
          protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: rook-ceph-mgr
  namespace: rook-ceph
spec:
  podSelector:
    matchLabels:
      app: rook-ceph-mgr
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
          podSelector:
            matchLabels:
              app.kubernetes.io/name: prometheus
      ports:
        - port: 9283
          protocol: TCP
  egress: []
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: rook-ceph-operator
  namespace: rook-ceph
spec:
  podSelector:
    matchLabels:
      app: rook-ceph-operator
  policyTypes:
    - Ingress
    - Egress
  ingress: []
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - port: 53
          protocol: UDP
    - to:
        - podSelector:
            matchLabels:
              app: rook-ceph-mon
              app.kubernetes.io/name: ceph-mon
              ceph_daemon_type: mon
      ports:
        - port: 3300
          protocol: TCP
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: ceph-mgr
              ceph_daemon_type: mgr
      ports:
        - port: 6800
          protocol: TCP
    - to:
        - podSelector:
            matchLabels:
              app: rook-ceph-osd
              app.kubernetes.io/name: ceph-osd
              ceph_daemon_type: osd
      ports:
        - port: 6800
          protocol: TCP
    - to:
        - podSelector:
            matchLabels:
              app: rook-ceph-rgw
              app.kubernetes.io/name: ceph-rgw
              ceph_daemon_type: rgw
      ports:
        - port: 8080
          protocol: TCP
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: rook-ceph-operator
  namespace: rook-ceph
spec:
  endpointSelector:
    matchLabels:
      app: rook-ceph-operator
  egress:
    - toEntities:
      - kube-apiserver
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: rook-ceph-tools
  namespace: rook-ceph
spec:
  podSelector:
    matchLabels:
      app: rook-ceph-tools
  policyTypes:
    - Ingress
    - Egress
  ingress: []
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - port: 53
          protocol: UDP
    - to:
        - podSelector:
            matchLabels:
              app: rook-ceph-mon
              app.kubernetes.io/name: ceph-mon
              ceph_daemon_type: mon
      ports:
        - port: 3300
          protocol: TCP
        - port: 6789
          protocol: TCP
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: ceph-mgr
              ceph_daemon_type: mgr
      ports:
        - port: 6800
          protocol: TCP