---

services:
  openclaw:
    image: ghcr.io/openclaw/openclaw:2026.2.15@sha256:20fb8df4e6c6d893de5b8445394583258fdf0f98179e82cdfa24062c6bed5de0
    ports:
      - "{{ openclaw_compose_web_port }}:18789"
    volumes:
      - "{{ openclaw_compose_config_path }}:/home/node"
    environment:
      TZ: "Europe/Oslo"
    restart: always
