---
services:
  openclaw:
    image: ghcr.io/openclaw/openclaw:2026.2.17@sha256:1f28ead56a68352c2bbbbd4fb45523a237f271dc3be827b073b9274986a2a829
    ports:
      - "18789:18789"
      - "18790:18790"
    volumes:
      - "{{ openclaw_compose_config_path }}/openclaw:/home/node"
    environment:
      HOME: /home/node
      TERM: xterm-256color
    restart: always
    command:
      [
        "node",
        "dist/index.js",
        "gateway",
        "--bind",
        "0.0.0.0",
        "--port",
        "18789",
      ]
  openclaw-cli:
    image: ghcr.io/openclaw/openclaw:2026.2.17@sha256:1f28ead56a68352c2bbbbd4fb45523a237f271dc3be827b073b9274986a2a829
    environment:
      HOME: /home/node
      TERM: xterm-256color
      BROWSER: echo
    volumes:
      - "{{ openclaw_compose_config_path }}/openclaw:/home/node"
    stdin_open: true
    tty: true
    init: true
    entrypoint: ["node", "dist/index.js"]
  signal-cli:
    image: docker.io/bbernhard/signal-cli-rest-api:0.97@sha256:5fcb8e8620f20f944d747627841ca97f19104acb3e1adb1d5c8983b5db422529
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - "{{ openclaw_compose_config_path }}/signal:/home/.local/share/signal-cli"
    environment:
      MODE: json-rpc
    restart: always
